// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 244b350b8c090c2e87fe089696c37c9b1c3fcd724910f8c84dc665ec423b443d
// Version: v1.2.0 (https://github.com/pk910/dynamic-ssz)
package bellatrix

import (
	"encoding/binary"

	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *ExecutionPayloadHeader) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *ExecutionPayloadHeader) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(ExecutionPayloadHeader)
	}
	dstlen := len(dst)
	{ // Field #0 'ParentHash'
		dst = append(dst, t.ParentHash[:32]...)
	}
	{ // Field #1 'FeeRecipient'
		dst = append(dst, t.FeeRecipient[:20]...)
	}
	{ // Field #2 'StateRoot'
		dst = append(dst, t.StateRoot[:32]...)
	}
	{ // Field #3 'ReceiptsRoot'
		dst = append(dst, t.ReceiptsRoot[:32]...)
	}
	{ // Field #4 'LogsBloom'
		dst = append(dst, t.LogsBloom[:256]...)
	}
	{ // Field #5 'PrevRandao'
		dst = append(dst, t.PrevRandao[:32]...)
	}
	{ // Field #6 'BlockNumber'
		dst = binary.LittleEndian.AppendUint64(dst, t.BlockNumber)
	}
	{ // Field #7 'GasLimit'
		dst = binary.LittleEndian.AppendUint64(dst, t.GasLimit)
	}
	{ // Field #8 'GasUsed'
		dst = binary.LittleEndian.AppendUint64(dst, t.GasUsed)
	}
	{ // Field #9 'Timestamp'
		dst = binary.LittleEndian.AppendUint64(dst, t.Timestamp)
	}
	// Offset #10 'ExtraData'
	offset10 := len(dst)
	dst = append(dst, 0, 0, 0, 0)
	{ // Field #11 'BaseFeePerGas'
		dst = append(dst, t.BaseFeePerGas[:32]...)
	}
	{ // Field #12 'BlockHash'
		dst = append(dst, t.BlockHash[:32]...)
	}
	{ // Field #13 'TransactionsRoot'
		dst = append(dst, t.TransactionsRoot[:32]...)
	}
	{ // Dynamic Field #10 'ExtraData'
		binary.LittleEndian.PutUint32(dst[offset10:], uint32(len(dst)-dstlen))
		vlen := len(t.ExtraData)
		if vlen > 32 {
			return nil, sszutils.ErrListTooBig
		}
		dst = append(dst, t.ExtraData[:]...)
	}
	return dst, nil
}

func (t *ExecutionPayloadHeader) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 536 {
		return sszutils.ErrUnexpectedEOF
	}
	{ // Field #0 'ParentHash' (static)
		buf := buf[0:32]
		copy(t.ParentHash[:], buf)
	}
	{ // Field #1 'FeeRecipient' (static)
		buf := buf[32:52]
		copy(t.FeeRecipient[:], buf)
	}
	{ // Field #2 'StateRoot' (static)
		buf := buf[52:84]
		copy(t.StateRoot[:], buf)
	}
	{ // Field #3 'ReceiptsRoot' (static)
		buf := buf[84:116]
		copy(t.ReceiptsRoot[:], buf)
	}
	{ // Field #4 'LogsBloom' (static)
		buf := buf[116:372]
		copy(t.LogsBloom[:], buf)
	}
	{ // Field #5 'PrevRandao' (static)
		buf := buf[372:404]
		copy(t.PrevRandao[:], buf)
	}
	{ // Field #6 'BlockNumber' (static)
		buf := buf[404:412]
		t.BlockNumber = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #7 'GasLimit' (static)
		buf := buf[412:420]
		t.GasLimit = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #8 'GasUsed' (static)
		buf := buf[420:428]
		t.GasUsed = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #9 'Timestamp' (static)
		buf := buf[428:436]
		t.Timestamp = binary.LittleEndian.Uint64(buf)
	}
	// Field #10 'ExtraData' (offset)
	offset10 := int(binary.LittleEndian.Uint32(buf[436:440]))
	if offset10 != 536 {
		return sszutils.ErrOffset
	}
	{ // Field #11 'BaseFeePerGas' (static)
		buf := buf[440:472]
		copy(t.BaseFeePerGas[:], buf)
	}
	{ // Field #12 'BlockHash' (static)
		buf := buf[472:504]
		copy(t.BlockHash[:], buf)
	}
	{ // Field #13 'TransactionsRoot' (static)
		buf := buf[504:536]
		copy(t.TransactionsRoot[:], buf)
	}
	{ // Field #10 'ExtraData' (dynamic)
		buf := buf[offset10:]
		val1 := t.ExtraData
		val1 = sszutils.ExpandSlice(val1, len(buf))
		copy(val1[:], buf)
		t.ExtraData = val1
	}
	return nil
}

func (t *ExecutionPayloadHeader) SizeSSZ() (size int) {
	if t == nil {
		t = new(ExecutionPayloadHeader)
	}
	// Field #0 'ParentHash' static (32 bytes)
	// Field #1 'FeeRecipient' static (20 bytes)
	// Field #2 'StateRoot' static (32 bytes)
	// Field #3 'ReceiptsRoot' static (32 bytes)
	// Field #4 'LogsBloom' static (256 bytes)
	// Field #5 'PrevRandao' static (32 bytes)
	// Field #6 'BlockNumber' static (8 bytes)
	// Field #7 'GasLimit' static (8 bytes)
	// Field #8 'GasUsed' static (8 bytes)
	// Field #9 'Timestamp' static (8 bytes)
	// Field #10 'ExtraData' offset (4 bytes)
	// Field #11 'BaseFeePerGas' static (32 bytes)
	// Field #12 'BlockHash' static (32 bytes)
	// Field #13 'TransactionsRoot' static (32 bytes)
	size += 536
	{ // Dynamic field #10 'ExtraData'
		size += len(t.ExtraData)
	}
	return size
}

func (t *ExecutionPayloadHeader) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
func (t *ExecutionPayloadHeader) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(ExecutionPayloadHeader)
	}
	idx := hh.Index()
	{ // Field #0 'ParentHash'
		hh.PutBytes(t.ParentHash[:32])
	}
	{ // Field #1 'FeeRecipient'
		hh.PutBytes(t.FeeRecipient[:20])
	}
	{ // Field #2 'StateRoot'
		hh.PutBytes(t.StateRoot[:32])
	}
	{ // Field #3 'ReceiptsRoot'
		hh.PutBytes(t.ReceiptsRoot[:32])
	}
	{ // Field #4 'LogsBloom'
		hh.PutBytes(t.LogsBloom[:256])
	}
	{ // Field #5 'PrevRandao'
		hh.PutBytes(t.PrevRandao[:32])
	}
	{ // Field #6 'BlockNumber'
		hh.PutUint64(t.BlockNumber)
	}
	{ // Field #7 'GasLimit'
		hh.PutUint64(t.GasLimit)
	}
	{ // Field #8 'GasUsed'
		hh.PutUint64(t.GasUsed)
	}
	{ // Field #9 'Timestamp'
		hh.PutUint64(t.Timestamp)
	}
	{ // Field #10 'ExtraData'
		vlen := uint64(len(t.ExtraData))
		if vlen > 32 {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		hh.AppendBytes32(t.ExtraData[:])
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(32, vlen, 1))
	}
	{ // Field #11 'BaseFeePerGas'
		hh.PutBytes(t.BaseFeePerGas[:32])
	}
	{ // Field #12 'BlockHash'
		hh.PutBytes(t.BlockHash[:32])
	}
	{ // Field #13 'TransactionsRoot'
		hh.PutBytes(t.TransactionsRoot[:32])
	}
	hh.Merkleize(idx)
	return nil
}

