// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 9e20fd3405985d94b43bfada89f02e74162f1d896bbb3142b315aec4585c8810
// Version: v1.2.1 (https://github.com/pk910/dynamic-ssz)
package altair

import (
	"encoding/binary"

	"github.com/attestantio/go-eth2-client/spec/phase0"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *ContributionAndProof) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *ContributionAndProof) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(ContributionAndProof)
	}
	{ // Field #0 'AggregatorIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.AggregatorIndex))
	}
	{ // Field #1 'Contribution'
		t := t.Contribution
		if t == nil {
			t = new(SyncCommitteeContribution)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, err
		}
	}
	{ // Field #2 'SelectionProof'
		dst = append(dst, t.SelectionProof[:96]...)
	}
	return dst, nil
}

func (t *ContributionAndProof) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 264 {
		return sszutils.ErrUnexpectedEOF
	}
	{ // Field #0 'AggregatorIndex' (static)
		buf := buf[0:8]
		t.AggregatorIndex = phase0.ValidatorIndex(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #1 'Contribution' (static)
		buf := buf[8:168]
		if t.Contribution == nil {
			t.Contribution = new(SyncCommitteeContribution)
		}
		if err = t.Contribution.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	{ // Field #2 'SelectionProof' (static)
		buf := buf[168:264]
		copy(t.SelectionProof[:], buf)
	}
	return nil
}

func (t *ContributionAndProof) SizeSSZ() (size int) {
	return 264
}

func (t *ContributionAndProof) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
func (t *ContributionAndProof) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(ContributionAndProof)
	}
	idx := hh.Index()
	{ // Field #0 'AggregatorIndex'
		hh.PutUint64(uint64(t.AggregatorIndex))
	}
	{ // Field #1 'Contribution'
		t := t.Contribution
		if t == nil {
			t = new(SyncCommitteeContribution)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	{ // Field #2 'SelectionProof'
		hh.PutBytes(t.SelectionProof[:96])
	}
	hh.Merkleize(idx)
	return nil
}

