// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 06b0f060d7d1555e470df3f6d738509ec737ecfdc1d3bac308173e8fc0b2dad8
// Version: v1.2.1 (https://github.com/pk910/dynamic-ssz)
package altair

import (
	"encoding/binary"

	"github.com/attestantio/go-eth2-client/spec/phase0"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *SyncCommitteeMessage) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *SyncCommitteeMessage) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(SyncCommitteeMessage)
	}
	{ // Field #0 'Slot'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.Slot))
	}
	{ // Field #1 'BeaconBlockRoot'
		dst = append(dst, t.BeaconBlockRoot[:32]...)
	}
	{ // Field #2 'ValidatorIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.ValidatorIndex))
	}
	{ // Field #3 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	return dst, nil
}

func (t *SyncCommitteeMessage) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 144 {
		return sszutils.ErrUnexpectedEOF
	}
	{ // Field #0 'Slot' (static)
		buf := buf[0:8]
		t.Slot = phase0.Slot(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #1 'BeaconBlockRoot' (static)
		buf := buf[8:40]
		copy(t.BeaconBlockRoot[:], buf)
	}
	{ // Field #2 'ValidatorIndex' (static)
		buf := buf[40:48]
		t.ValidatorIndex = phase0.ValidatorIndex(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #3 'Signature' (static)
		buf := buf[48:144]
		copy(t.Signature[:], buf)
	}
	return nil
}

func (t *SyncCommitteeMessage) SizeSSZ() (size int) {
	return 144
}

func (t *SyncCommitteeMessage) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
func (t *SyncCommitteeMessage) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SyncCommitteeMessage)
	}
	idx := hh.Index()
	{ // Field #0 'Slot'
		hh.PutUint64(uint64(t.Slot))
	}
	{ // Field #1 'BeaconBlockRoot'
		hh.PutBytes(t.BeaconBlockRoot[:32])
	}
	{ // Field #2 'ValidatorIndex'
		hh.PutUint64(uint64(t.ValidatorIndex))
	}
	{ // Field #3 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}

