// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 8d3a32a80cc3a4a203b7dba43d7faa314dcbfcbbf2cc6cabfcd52bb3eaece8bb
// Version: v1.2.0 (https://github.com/pk910/dynamic-ssz)
package altair

import (
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *SyncAggregate) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *SyncAggregate) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(SyncAggregate)
	}
	{ // Field #0 'SyncCommitteeBits'
		vlen := len(t.SyncCommitteeBits)
		if vlen > 64 {
			return nil, sszutils.ErrVectorLength
		}
		dst = append(dst, t.SyncCommitteeBits[:vlen]...)
		if vlen < 64 {
			dst = sszutils.AppendZeroPadding(dst, (64 - vlen) * 1)
		}
	}
	{ // Field #1 'SyncCommitteeSignature'
		dst = append(dst, t.SyncCommitteeSignature[:96]...)
	}
	return dst, nil
}

func (t *SyncAggregate) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 160 {
		return sszutils.ErrUnexpectedEOF
	}
	{ // Field #0 'SyncCommitteeBits' (static)
		buf := buf[0:64]
		t.SyncCommitteeBits = sszutils.ExpandSlice(t.SyncCommitteeBits, 64)
		copy(t.SyncCommitteeBits[:], buf)
	}
	{ // Field #1 'SyncCommitteeSignature' (static)
		buf := buf[64:160]
		copy(t.SyncCommitteeSignature[:], buf)
	}
	return nil
}

func (t *SyncAggregate) SizeSSZ() (size int) {
	return 160
}

func (t *SyncAggregate) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
func (t *SyncAggregate) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SyncAggregate)
	}
	idx := hh.Index()
	{ // Field #0 'SyncCommitteeBits'
		vlen := len(t.SyncCommitteeBits)
		if vlen > 64 {
			return sszutils.ErrVectorLength
		}
		val := t.SyncCommitteeBits[:]
		if vlen < 64 {
			val = sszutils.AppendZeroPadding(val, (64-vlen)*1)
		}
		hh.PutBytes(val[:64])
	}
	{ // Field #1 'SyncCommitteeSignature'
		hh.PutBytes(t.SyncCommitteeSignature[:96])
	}
	hh.Merkleize(idx)
	return nil
}

