// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: e7acde2cc828805144264b37c53dea12c2e007cdc1502146fb01776b417c057e
// Version: v1.2.1 (https://github.com/pk910/dynamic-ssz)
package v1

import (
	"github.com/attestantio/go-eth2-client/spec/deneb"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t Blobs) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t Blobs) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	vlen := len(t)
	for i := range vlen {
		if t[i] == nil {
			t[i] = new(deneb.Blob)
		}
		dst = append(dst, t[i][:131072]...)
	}
	return dst, nil
}

func (t Blobs) UnmarshalSSZ(buf []byte) (err error) {
	itemCount := len(buf) / 131072
	if len(buf)%131072 != 0 {
		return sszutils.ErrUnexpectedEOF
	}
	t = sszutils.ExpandSlice(t, itemCount)
	for i := range itemCount {
		if t[i] == nil {
			t[i] = new(deneb.Blob)
		}
		buf := buf[131072*i : 131072*(i+1)]
		copy(t[i][:], buf)
	}
	return nil
}

func (t Blobs) SizeSSZ() (size int) {
	size += len(t) * 131072
	return size
}

func (t Blobs) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
func (t Blobs) HashTreeRootWith(hh sszutils.HashWalker) error {
	idx := hh.Index()
	vlen := uint64(len(t))
	for i := range int(vlen) {
		if t[i] == nil {
			t[i] = new(deneb.Blob)
		}
		hh.PutBytes(t[i][:131072])
	}
	hh.Merkleize(idx)
	return nil
}

