// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 7e3871f4a0a602537be97ab2b5ed55ec2b335bac132e4395284a80d6fb3cc810
// Version: v1.2.0 (https://github.com/pk910/dynamic-ssz)
package electra

import (
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *ConsolidationRequest) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *ConsolidationRequest) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(ConsolidationRequest)
	}
	{ // Field #0 'SourceAddress'
		dst = append(dst, t.SourceAddress[:20]...)
	}
	{ // Field #1 'SourcePubkey'
		dst = append(dst, t.SourcePubkey[:48]...)
	}
	{ // Field #2 'TargetPubkey'
		dst = append(dst, t.TargetPubkey[:48]...)
	}
	return dst, nil
}

func (t *ConsolidationRequest) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 116 {
		return sszutils.ErrUnexpectedEOF
	}
	{ // Field #0 'SourceAddress' (static)
		buf := buf[0:20]
		copy(t.SourceAddress[:], buf)
	}
	{ // Field #1 'SourcePubkey' (static)
		buf := buf[20:68]
		copy(t.SourcePubkey[:], buf)
	}
	{ // Field #2 'TargetPubkey' (static)
		buf := buf[68:116]
		copy(t.TargetPubkey[:], buf)
	}
	return nil
}

func (t *ConsolidationRequest) SizeSSZ() (size int) {
	return 116
}

func (t *ConsolidationRequest) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
func (t *ConsolidationRequest) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(ConsolidationRequest)
	}
	idx := hh.Index()
	{ // Field #0 'SourceAddress'
		hh.PutBytes(t.SourceAddress[:20])
	}
	{ // Field #1 'SourcePubkey'
		hh.PutBytes(t.SourcePubkey[:48])
	}
	{ // Field #2 'TargetPubkey'
		hh.PutBytes(t.TargetPubkey[:48])
	}
	hh.Merkleize(idx)
	return nil
}

