// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: b23ddb72247c257747054bb77985ae10fd22d64c3c6e429475e75c32435bfbc6
// Version: v1.2.1 (https://github.com/pk910/dynamic-ssz)
package electra

import (
	"encoding/binary"

	"github.com/attestantio/go-eth2-client/spec/phase0"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *PendingPartialWithdrawal) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *PendingPartialWithdrawal) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(PendingPartialWithdrawal)
	}
	{ // Field #0 'ValidatorIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.ValidatorIndex))
	}
	{ // Field #1 'Amount'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.Amount))
	}
	{ // Field #2 'WithdrawableEpoch'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.WithdrawableEpoch))
	}
	return dst, nil
}

func (t *PendingPartialWithdrawal) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 24 {
		return sszutils.ErrUnexpectedEOF
	}
	{ // Field #0 'ValidatorIndex' (static)
		buf := buf[0:8]
		t.ValidatorIndex = phase0.ValidatorIndex(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #1 'Amount' (static)
		buf := buf[8:16]
		t.Amount = phase0.Gwei(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #2 'WithdrawableEpoch' (static)
		buf := buf[16:24]
		t.WithdrawableEpoch = phase0.Epoch(binary.LittleEndian.Uint64(buf))
	}
	return nil
}

func (t *PendingPartialWithdrawal) SizeSSZ() (size int) {
	return 24
}

func (t *PendingPartialWithdrawal) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
func (t *PendingPartialWithdrawal) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(PendingPartialWithdrawal)
	}
	idx := hh.Index()
	{ // Field #0 'ValidatorIndex'
		hh.PutUint64(uint64(t.ValidatorIndex))
	}
	{ // Field #1 'Amount'
		hh.PutUint64(uint64(t.Amount))
	}
	{ // Field #2 'WithdrawableEpoch'
		hh.PutUint64(uint64(t.WithdrawableEpoch))
	}
	hh.Merkleize(idx)
	return nil
}

