// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 6cc0074ff376a5900fd37fa43c1eb4e9e3f4699ec5467686a51dc7b0e84a8eec
// Version: v1.2.1 (https://github.com/pk910/dynamic-ssz)
package electra

import (
	"encoding/binary"

	"github.com/attestantio/go-eth2-client/spec/phase0"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *SingleAttestation) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *SingleAttestation) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(SingleAttestation)
	}
	{ // Field #0 'CommitteeIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.CommitteeIndex))
	}
	{ // Field #1 'AttesterIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.AttesterIndex))
	}
	{ // Field #2 'Data'
		t := t.Data
		if t == nil {
			t = new(phase0.AttestationData)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, err
		}
	}
	{ // Field #3 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	return dst, nil
}

func (t *SingleAttestation) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 240 {
		return sszutils.ErrUnexpectedEOF
	}
	{ // Field #0 'CommitteeIndex' (static)
		buf := buf[0:8]
		t.CommitteeIndex = phase0.CommitteeIndex(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #1 'AttesterIndex' (static)
		buf := buf[8:16]
		t.AttesterIndex = phase0.ValidatorIndex(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #2 'Data' (static)
		buf := buf[16:144]
		if t.Data == nil {
			t.Data = new(phase0.AttestationData)
		}
		if err = t.Data.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	{ // Field #3 'Signature' (static)
		buf := buf[144:240]
		copy(t.Signature[:], buf)
	}
	return nil
}

func (t *SingleAttestation) SizeSSZ() (size int) {
	return 240
}

func (t *SingleAttestation) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
func (t *SingleAttestation) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SingleAttestation)
	}
	idx := hh.Index()
	{ // Field #0 'CommitteeIndex'
		hh.PutUint64(uint64(t.CommitteeIndex))
	}
	{ // Field #1 'AttesterIndex'
		hh.PutUint64(uint64(t.AttesterIndex))
	}
	{ // Field #2 'Data'
		t := t.Data
		if t == nil {
			t = new(phase0.AttestationData)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	{ // Field #3 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}

