// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: becaabdd18674f5a84a14d7a95c3f7f71712038570adbcbb5341f57f2a322ded
// Version: v1.2.1 (https://github.com/pk910/dynamic-ssz)
package electra

import (
	"encoding/binary"

	"github.com/attestantio/go-eth2-client/spec/phase0"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *WithdrawalRequest) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *WithdrawalRequest) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(WithdrawalRequest)
	}
	{ // Field #0 'SourceAddress'
		dst = append(dst, t.SourceAddress[:20]...)
	}
	{ // Field #1 'ValidatorPubkey'
		dst = append(dst, t.ValidatorPubkey[:48]...)
	}
	{ // Field #2 'Amount'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.Amount))
	}
	return dst, nil
}

func (t *WithdrawalRequest) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 76 {
		return sszutils.ErrUnexpectedEOF
	}
	{ // Field #0 'SourceAddress' (static)
		buf := buf[0:20]
		copy(t.SourceAddress[:], buf)
	}
	{ // Field #1 'ValidatorPubkey' (static)
		buf := buf[20:68]
		copy(t.ValidatorPubkey[:], buf)
	}
	{ // Field #2 'Amount' (static)
		buf := buf[68:76]
		t.Amount = phase0.Gwei(binary.LittleEndian.Uint64(buf))
	}
	return nil
}

func (t *WithdrawalRequest) SizeSSZ() (size int) {
	return 76
}

func (t *WithdrawalRequest) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
func (t *WithdrawalRequest) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(WithdrawalRequest)
	}
	idx := hh.Index()
	{ // Field #0 'SourceAddress'
		hh.PutBytes(t.SourceAddress[:20])
	}
	{ // Field #1 'ValidatorPubkey'
		hh.PutBytes(t.ValidatorPubkey[:48])
	}
	{ // Field #2 'Amount'
		hh.PutUint64(uint64(t.Amount))
	}
	hh.Merkleize(idx)
	return nil
}

