// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 45f1c1364e2651bc935d50012aaf82895651e2e278db7cb71e536775455734c5
// Version: v1.2.1 (https://github.com/pk910/dynamic-ssz)
package gloas

import (
	"encoding/binary"

	"github.com/attestantio/go-eth2-client/spec/altair"
	"github.com/attestantio/go-eth2-client/spec/capella"
	"github.com/attestantio/go-eth2-client/spec/electra"
	"github.com/attestantio/go-eth2-client/spec/phase0"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *BeaconBlockBody) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *BeaconBlockBody) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(BeaconBlockBody)
	}
	dstlen := len(dst)
	{ // Field #0 'RANDAOReveal'
		dst = append(dst, t.RANDAOReveal[:96]...)
	}
	{ // Field #1 'ETH1Data'
		t := t.ETH1Data
		if t == nil {
			t = new(phase0.ETH1Data)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, err
		}
	}
	{ // Field #2 'Graffiti'
		dst = append(dst, t.Graffiti[:32]...)
	}
	// Offset #3 'ProposerSlashings'
	offset3 := len(dst)
	dst = append(dst, 0, 0, 0, 0)
	// Offset #4 'AttesterSlashings'
	offset4 := len(dst)
	dst = append(dst, 0, 0, 0, 0)
	// Offset #5 'Attestations'
	offset5 := len(dst)
	dst = append(dst, 0, 0, 0, 0)
	// Offset #6 'Deposits'
	offset6 := len(dst)
	dst = append(dst, 0, 0, 0, 0)
	// Offset #7 'VoluntaryExits'
	offset7 := len(dst)
	dst = append(dst, 0, 0, 0, 0)
	{ // Field #8 'SyncAggregate'
		t := t.SyncAggregate
		if t == nil {
			t = new(altair.SyncAggregate)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, err
		}
	}
	// Offset #9 'BLSToExecutionChanges'
	offset9 := len(dst)
	dst = append(dst, 0, 0, 0, 0)
	{ // Field #10 'SignedExecutionPayloadBid'
		t := t.SignedExecutionPayloadBid
		if t == nil {
			t = new(SignedExecutionPayloadBid)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, err
		}
	}
	// Offset #11 'PayloadAttestations'
	offset11 := len(dst)
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #3 'ProposerSlashings'
		binary.LittleEndian.PutUint32(dst[offset3:], uint32(len(dst)-dstlen))
		t := t.ProposerSlashings
		vlen := len(t)
		if vlen > 16 {
			return nil, sszutils.ErrListTooBig
		}
		for i := range vlen {
			t := t[i]
			if t == nil {
				t = new(phase0.ProposerSlashing)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, err
			}
		}
	}
	{ // Dynamic Field #4 'AttesterSlashings'
		binary.LittleEndian.PutUint32(dst[offset4:], uint32(len(dst)-dstlen))
		t := t.AttesterSlashings
		vlen := len(t)
		if vlen > 1 {
			return nil, sszutils.ErrListTooBig
		}
		dstlen := len(dst)
		dst = sszutils.AppendZeroPadding(dst, vlen*4)
		for i := range vlen {
			binary.LittleEndian.PutUint32(dst[dstlen+(i*4):], uint32(len(dst)-dstlen))
			t := t[i]
			if t == nil {
				t = new(electra.AttesterSlashing)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, err
			}
		}
	}
	{ // Dynamic Field #5 'Attestations'
		binary.LittleEndian.PutUint32(dst[offset5:], uint32(len(dst)-dstlen))
		t := t.Attestations
		vlen := len(t)
		if vlen > 8 {
			return nil, sszutils.ErrListTooBig
		}
		dstlen := len(dst)
		dst = sszutils.AppendZeroPadding(dst, vlen*4)
		for i := range vlen {
			binary.LittleEndian.PutUint32(dst[dstlen+(i*4):], uint32(len(dst)-dstlen))
			t := t[i]
			if t == nil {
				t = new(electra.Attestation)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, err
			}
		}
	}
	{ // Dynamic Field #6 'Deposits'
		binary.LittleEndian.PutUint32(dst[offset6:], uint32(len(dst)-dstlen))
		t := t.Deposits
		vlen := len(t)
		if vlen > 16 {
			return nil, sszutils.ErrListTooBig
		}
		for i := range vlen {
			t := t[i]
			if t == nil {
				t = new(phase0.Deposit)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, err
			}
		}
	}
	{ // Dynamic Field #7 'VoluntaryExits'
		binary.LittleEndian.PutUint32(dst[offset7:], uint32(len(dst)-dstlen))
		t := t.VoluntaryExits
		vlen := len(t)
		if vlen > 16 {
			return nil, sszutils.ErrListTooBig
		}
		for i := range vlen {
			t := t[i]
			if t == nil {
				t = new(phase0.SignedVoluntaryExit)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, err
			}
		}
	}
	{ // Dynamic Field #9 'BLSToExecutionChanges'
		binary.LittleEndian.PutUint32(dst[offset9:], uint32(len(dst)-dstlen))
		t := t.BLSToExecutionChanges
		vlen := len(t)
		if vlen > 16 {
			return nil, sszutils.ErrListTooBig
		}
		for i := range vlen {
			t := t[i]
			if t == nil {
				t = new(capella.SignedBLSToExecutionChange)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, err
			}
		}
	}
	{ // Dynamic Field #11 'PayloadAttestations'
		binary.LittleEndian.PutUint32(dst[offset11:], uint32(len(dst)-dstlen))
		t := t.PayloadAttestations
		vlen := len(t)
		if vlen > 4 {
			return nil, sszutils.ErrListTooBig
		}
		dstlen := len(dst)
		dst = sszutils.AppendZeroPadding(dst, vlen*4)
		for i := range vlen {
			binary.LittleEndian.PutUint32(dst[dstlen+(i*4):], uint32(len(dst)-dstlen))
			t := t[i]
			if t == nil {
				t = new(PayloadAttestation)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, err
			}
		}
	}
	return dst, nil
}

func (t *BeaconBlockBody) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 704 {
		return sszutils.ErrUnexpectedEOF
	}
	{ // Field #0 'RANDAOReveal' (static)
		buf := buf[0:96]
		copy(t.RANDAOReveal[:], buf)
	}
	{ // Field #1 'ETH1Data' (static)
		buf := buf[96:168]
		if t.ETH1Data == nil {
			t.ETH1Data = new(phase0.ETH1Data)
		}
		if err = t.ETH1Data.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	{ // Field #2 'Graffiti' (static)
		buf := buf[168:200]
		copy(t.Graffiti[:], buf)
	}
	// Field #3 'ProposerSlashings' (offset)
	offset3 := int(binary.LittleEndian.Uint32(buf[200:204]))
	if offset3 != 704 {
		return sszutils.ErrOffset
	}
	// Field #4 'AttesterSlashings' (offset)
	offset4 := int(binary.LittleEndian.Uint32(buf[204:208]))
	if offset4 < offset3 || offset4 > buflen {
		return sszutils.ErrOffset
	}
	// Field #5 'Attestations' (offset)
	offset5 := int(binary.LittleEndian.Uint32(buf[208:212]))
	if offset5 < offset4 || offset5 > buflen {
		return sszutils.ErrOffset
	}
	// Field #6 'Deposits' (offset)
	offset6 := int(binary.LittleEndian.Uint32(buf[212:216]))
	if offset6 < offset5 || offset6 > buflen {
		return sszutils.ErrOffset
	}
	// Field #7 'VoluntaryExits' (offset)
	offset7 := int(binary.LittleEndian.Uint32(buf[216:220]))
	if offset7 < offset6 || offset7 > buflen {
		return sszutils.ErrOffset
	}
	{ // Field #8 'SyncAggregate' (static)
		buf := buf[220:380]
		if t.SyncAggregate == nil {
			t.SyncAggregate = new(altair.SyncAggregate)
		}
		if err = t.SyncAggregate.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	// Field #9 'BLSToExecutionChanges' (offset)
	offset9 := int(binary.LittleEndian.Uint32(buf[380:384]))
	if offset9 < offset7 || offset9 > buflen {
		return sszutils.ErrOffset
	}
	{ // Field #10 'SignedExecutionPayloadBid' (static)
		buf := buf[384:700]
		if t.SignedExecutionPayloadBid == nil {
			t.SignedExecutionPayloadBid = new(SignedExecutionPayloadBid)
		}
		if err = t.SignedExecutionPayloadBid.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	// Field #11 'PayloadAttestations' (offset)
	offset11 := int(binary.LittleEndian.Uint32(buf[700:704]))
	if offset11 < offset9 || offset11 > buflen {
		return sszutils.ErrOffset
	}
	{ // Field #3 'ProposerSlashings' (dynamic)
		buf := buf[offset3:offset4]
		val1 := t.ProposerSlashings
		itemCount := len(buf) / 416
		if len(buf)%416 != 0 {
			return sszutils.ErrUnexpectedEOF
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for i := range itemCount {
			if val1[i] == nil {
				val1[i] = new(phase0.ProposerSlashing)
			}
			buf := buf[416*i : 416*(i+1)]
			if err = val1[i].UnmarshalSSZ(buf); err != nil {
				return err
			}
		}
		t.ProposerSlashings = val1
	}
	{ // Field #4 'AttesterSlashings' (dynamic)
		buf := buf[offset4:offset5]
		val2 := t.AttesterSlashings
		startOffset := int(0)
		if len(buf) != 0 {
			if len(buf) < 4 {
				return sszutils.ErrUnexpectedEOF
			}
			startOffset = int(binary.LittleEndian.Uint32(buf[0:4]))
		}
		itemCount := startOffset / 4
		if startOffset%4 != 0 || len(buf) < startOffset {
			return sszutils.ErrUnexpectedEOF
		}
		val2 = sszutils.ExpandSlice(val2, itemCount)
		for i := range itemCount {
			var endOffset int
			if i < itemCount-1 {
				endOffset = int(binary.LittleEndian.Uint32(buf[(i+1)*4 : (i+2)*4]))
			} else {
				endOffset = len(buf)
			}
			if endOffset < startOffset || endOffset > len(buf) {
				return sszutils.ErrOffset
			}
			buf := buf[startOffset:endOffset]
			startOffset = endOffset
			val3 := val2[i]
			if val3 == nil {
				val3 = new(electra.AttesterSlashing)
			}
			if err = val3.UnmarshalSSZ(buf); err != nil {
				return err
			}
			val2[i] = val3
		}
		t.AttesterSlashings = val2
	}
	{ // Field #5 'Attestations' (dynamic)
		buf := buf[offset5:offset6]
		val4 := t.Attestations
		startOffset := int(0)
		if len(buf) != 0 {
			if len(buf) < 4 {
				return sszutils.ErrUnexpectedEOF
			}
			startOffset = int(binary.LittleEndian.Uint32(buf[0:4]))
		}
		itemCount := startOffset / 4
		if startOffset%4 != 0 || len(buf) < startOffset {
			return sszutils.ErrUnexpectedEOF
		}
		val4 = sszutils.ExpandSlice(val4, itemCount)
		for i := range itemCount {
			var endOffset int
			if i < itemCount-1 {
				endOffset = int(binary.LittleEndian.Uint32(buf[(i+1)*4 : (i+2)*4]))
			} else {
				endOffset = len(buf)
			}
			if endOffset < startOffset || endOffset > len(buf) {
				return sszutils.ErrOffset
			}
			buf := buf[startOffset:endOffset]
			startOffset = endOffset
			val5 := val4[i]
			if val5 == nil {
				val5 = new(electra.Attestation)
			}
			if err = val5.UnmarshalSSZ(buf); err != nil {
				return err
			}
			val4[i] = val5
		}
		t.Attestations = val4
	}
	{ // Field #6 'Deposits' (dynamic)
		buf := buf[offset6:offset7]
		val6 := t.Deposits
		itemCount := len(buf) / 1240
		if len(buf)%1240 != 0 {
			return sszutils.ErrUnexpectedEOF
		}
		val6 = sszutils.ExpandSlice(val6, itemCount)
		for i := range itemCount {
			if val6[i] == nil {
				val6[i] = new(phase0.Deposit)
			}
			buf := buf[1240*i : 1240*(i+1)]
			if err = val6[i].UnmarshalSSZ(buf); err != nil {
				return err
			}
		}
		t.Deposits = val6
	}
	{ // Field #7 'VoluntaryExits' (dynamic)
		buf := buf[offset7:offset9]
		val7 := t.VoluntaryExits
		itemCount := len(buf) / 112
		if len(buf)%112 != 0 {
			return sszutils.ErrUnexpectedEOF
		}
		val7 = sszutils.ExpandSlice(val7, itemCount)
		for i := range itemCount {
			if val7[i] == nil {
				val7[i] = new(phase0.SignedVoluntaryExit)
			}
			buf := buf[112*i : 112*(i+1)]
			if err = val7[i].UnmarshalSSZ(buf); err != nil {
				return err
			}
		}
		t.VoluntaryExits = val7
	}
	{ // Field #9 'BLSToExecutionChanges' (dynamic)
		buf := buf[offset9:offset11]
		val8 := t.BLSToExecutionChanges
		itemCount := len(buf) / 172
		if len(buf)%172 != 0 {
			return sszutils.ErrUnexpectedEOF
		}
		val8 = sszutils.ExpandSlice(val8, itemCount)
		for i := range itemCount {
			if val8[i] == nil {
				val8[i] = new(capella.SignedBLSToExecutionChange)
			}
			buf := buf[172*i : 172*(i+1)]
			if err = val8[i].UnmarshalSSZ(buf); err != nil {
				return err
			}
		}
		t.BLSToExecutionChanges = val8
	}
	{ // Field #11 'PayloadAttestations' (dynamic)
		buf := buf[offset11:]
		val9 := t.PayloadAttestations
		startOffset := int(0)
		if len(buf) != 0 {
			if len(buf) < 4 {
				return sszutils.ErrUnexpectedEOF
			}
			startOffset = int(binary.LittleEndian.Uint32(buf[0:4]))
		}
		itemCount := startOffset / 4
		if startOffset%4 != 0 || len(buf) < startOffset {
			return sszutils.ErrUnexpectedEOF
		}
		val9 = sszutils.ExpandSlice(val9, itemCount)
		for i := range itemCount {
			var endOffset int
			if i < itemCount-1 {
				endOffset = int(binary.LittleEndian.Uint32(buf[(i+1)*4 : (i+2)*4]))
			} else {
				endOffset = len(buf)
			}
			if endOffset < startOffset || endOffset > len(buf) {
				return sszutils.ErrOffset
			}
			buf := buf[startOffset:endOffset]
			startOffset = endOffset
			val10 := val9[i]
			if val10 == nil {
				val10 = new(PayloadAttestation)
			}
			if err = val10.UnmarshalSSZ(buf); err != nil {
				return err
			}
			val9[i] = val10
		}
		t.PayloadAttestations = val9
	}
	return nil
}

func (t *BeaconBlockBody) SizeSSZ() (size int) {
	if t == nil {
		t = new(BeaconBlockBody)
	}
	// Field #0 'RANDAOReveal' static (96 bytes)
	// Field #1 'ETH1Data' static (72 bytes)
	// Field #2 'Graffiti' static (32 bytes)
	// Field #3 'ProposerSlashings' offset (4 bytes)
	// Field #4 'AttesterSlashings' offset (4 bytes)
	// Field #5 'Attestations' offset (4 bytes)
	// Field #6 'Deposits' offset (4 bytes)
	// Field #7 'VoluntaryExits' offset (4 bytes)
	// Field #8 'SyncAggregate' static (160 bytes)
	// Field #9 'BLSToExecutionChanges' offset (4 bytes)
	// Field #10 'SignedExecutionPayloadBid' static (316 bytes)
	// Field #11 'PayloadAttestations' offset (4 bytes)
	size += 704
	{ // Dynamic field #3 'ProposerSlashings'
		size += len(t.ProposerSlashings) * 416
	}
	{ // Dynamic field #4 'AttesterSlashings'
		t := t.AttesterSlashings
		vlen := len(t)
		size += vlen * 4 // Offsets
		for i1 := range vlen {
			size += t[i1].SizeSSZ()
		}
	}
	{ // Dynamic field #5 'Attestations'
		t := t.Attestations
		vlen := len(t)
		size += vlen * 4 // Offsets
		for i2 := range vlen {
			size += t[i2].SizeSSZ()
		}
	}
	{ // Dynamic field #6 'Deposits'
		size += len(t.Deposits) * 1240
	}
	{ // Dynamic field #7 'VoluntaryExits'
		size += len(t.VoluntaryExits) * 112
	}
	{ // Dynamic field #9 'BLSToExecutionChanges'
		size += len(t.BLSToExecutionChanges) * 172
	}
	{ // Dynamic field #11 'PayloadAttestations'
		t := t.PayloadAttestations
		vlen := len(t)
		size += vlen * 4 // Offsets
		for i3 := range vlen {
			size += t[i3].SizeSSZ()
		}
	}
	return size
}

func (t *BeaconBlockBody) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
func (t *BeaconBlockBody) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BeaconBlockBody)
	}
	idx := hh.Index()
	{ // Field #0 'RANDAOReveal'
		hh.PutBytes(t.RANDAOReveal[:96])
	}
	{ // Field #1 'ETH1Data'
		t := t.ETH1Data
		if t == nil {
			t = new(phase0.ETH1Data)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	{ // Field #2 'Graffiti'
		hh.PutBytes(t.Graffiti[:32])
	}
	{ // Field #3 'ProposerSlashings'
		t := t.ProposerSlashings
		vlen := uint64(len(t))
		if vlen > 16 {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := range int(vlen) {
			t := t[i]
			if t == nil {
				t = new(phase0.ProposerSlashing)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return err
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(16, vlen, 32))
	}
	{ // Field #4 'AttesterSlashings'
		t := t.AttesterSlashings
		vlen := uint64(len(t))
		if vlen > 1 {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := range int(vlen) {
			t := t[i]
			if t == nil {
				t = new(electra.AttesterSlashing)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return err
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(1, vlen, 32))
	}
	{ // Field #5 'Attestations'
		t := t.Attestations
		vlen := uint64(len(t))
		if vlen > 8 {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := range int(vlen) {
			t := t[i]
			if t == nil {
				t = new(electra.Attestation)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return err
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(8, vlen, 32))
	}
	{ // Field #6 'Deposits'
		t := t.Deposits
		vlen := uint64(len(t))
		if vlen > 16 {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := range int(vlen) {
			t := t[i]
			if t == nil {
				t = new(phase0.Deposit)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return err
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(16, vlen, 32))
	}
	{ // Field #7 'VoluntaryExits'
		t := t.VoluntaryExits
		vlen := uint64(len(t))
		if vlen > 16 {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := range int(vlen) {
			t := t[i]
			if t == nil {
				t = new(phase0.SignedVoluntaryExit)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return err
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(16, vlen, 32))
	}
	{ // Field #8 'SyncAggregate'
		t := t.SyncAggregate
		if t == nil {
			t = new(altair.SyncAggregate)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	{ // Field #9 'BLSToExecutionChanges'
		t := t.BLSToExecutionChanges
		vlen := uint64(len(t))
		if vlen > 16 {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := range int(vlen) {
			t := t[i]
			if t == nil {
				t = new(capella.SignedBLSToExecutionChange)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return err
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(16, vlen, 32))
	}
	{ // Field #10 'SignedExecutionPayloadBid'
		t := t.SignedExecutionPayloadBid
		if t == nil {
			t = new(SignedExecutionPayloadBid)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	{ // Field #11 'PayloadAttestations'
		t := t.PayloadAttestations
		vlen := uint64(len(t))
		if vlen > 4 {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := range int(vlen) {
			t := t[i]
			if t == nil {
				t = new(PayloadAttestation)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return err
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(4, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}

