// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 2814233bb3b8337c061ff6e590643587ba7f097131ad6f291a424c8a8ee5d512
// Version: v1.2.0 (https://github.com/pk910/dynamic-ssz)
package gloas

import (
	"encoding/binary"

	"github.com/attestantio/go-eth2-client/spec/phase0"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *Builder) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *Builder) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(Builder)
	}
	{ // Field #0 'PublicKey'
		dst = append(dst, t.PublicKey[:48]...)
	}
	{ // Field #1 'Version'
		dst = append(dst, byte(t.Version))
	}
	{ // Field #2 'ExecutionAddress'
		dst = append(dst, t.ExecutionAddress[:20]...)
	}
	{ // Field #3 'Balance'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.Balance))
	}
	{ // Field #4 'DepositEpoch'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.DepositEpoch))
	}
	{ // Field #5 'WithdrawableEpoch'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.WithdrawableEpoch))
	}
	return dst, nil
}

func (t *Builder) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 93 {
		return sszutils.ErrUnexpectedEOF
	}
	{ // Field #0 'PublicKey' (static)
		buf := buf[0:48]
		copy(t.PublicKey[:], buf)
	}
	{ // Field #1 'Version' (static)
		buf := buf[48:49]
		t.Version = buf[0]
	}
	{ // Field #2 'ExecutionAddress' (static)
		buf := buf[49:69]
		copy(t.ExecutionAddress[:], buf)
	}
	{ // Field #3 'Balance' (static)
		buf := buf[69:77]
		t.Balance = phase0.Gwei(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #4 'DepositEpoch' (static)
		buf := buf[77:85]
		t.DepositEpoch = phase0.Epoch(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #5 'WithdrawableEpoch' (static)
		buf := buf[85:93]
		t.WithdrawableEpoch = phase0.Epoch(binary.LittleEndian.Uint64(buf))
	}
	return nil
}

func (t *Builder) SizeSSZ() (size int) {
	return 93
}

func (t *Builder) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
func (t *Builder) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(Builder)
	}
	idx := hh.Index()
	{ // Field #0 'PublicKey'
		hh.PutBytes(t.PublicKey[:48])
	}
	{ // Field #1 'Version'
		hh.PutUint8(t.Version)
	}
	{ // Field #2 'ExecutionAddress'
		hh.PutBytes(t.ExecutionAddress[:20])
	}
	{ // Field #3 'Balance'
		hh.PutUint64(uint64(t.Balance))
	}
	{ // Field #4 'DepositEpoch'
		hh.PutUint64(uint64(t.DepositEpoch))
	}
	{ // Field #5 'WithdrawableEpoch'
		hh.PutUint64(uint64(t.WithdrawableEpoch))
	}
	hh.Merkleize(idx)
	return nil
}

