// Code generated by fastssz. DO NOT EDIT.
// Hash: da971fd7603047585d3acf750304f2185322d7661ae317da0a383920e8630cfa
// Version: 0.1.3
package gloas

import (
	"github.com/attestantio/go-eth2-client/spec/phase0"
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the Builder object
func (b *Builder) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the Builder object to a target array
func (b *Builder) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'PublicKey'
	dst = append(dst, b.PublicKey[:]...)

	// Field (1) 'Version'
	dst = ssz.MarshalUint8(dst, b.Version)

	// Field (2) 'ExecutionAddress'
	dst = append(dst, b.ExecutionAddress[:]...)

	// Field (3) 'Balance'
	dst = ssz.MarshalUint64(dst, uint64(b.Balance))

	// Field (4) 'DepositEpoch'
	dst = ssz.MarshalUint64(dst, uint64(b.DepositEpoch))

	// Field (5) 'WithdrawableEpoch'
	dst = ssz.MarshalUint64(dst, uint64(b.WithdrawableEpoch))

	return
}

// UnmarshalSSZ ssz unmarshals the Builder object
func (b *Builder) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 93 {
		return ssz.ErrSize
	}

	// Field (0) 'PublicKey'
	copy(b.PublicKey[:], buf[0:48])

	// Field (1) 'Version'
	b.Version = ssz.UnmarshallUint8(buf[48:49])

	// Field (2) 'ExecutionAddress'
	copy(b.ExecutionAddress[:], buf[49:69])

	// Field (3) 'Balance'
	b.Balance = phase0.Gwei(ssz.UnmarshallUint64(buf[69:77]))

	// Field (4) 'DepositEpoch'
	b.DepositEpoch = phase0.Epoch(ssz.UnmarshallUint64(buf[77:85]))

	// Field (5) 'WithdrawableEpoch'
	b.WithdrawableEpoch = phase0.Epoch(ssz.UnmarshallUint64(buf[85:93]))

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the Builder object
func (b *Builder) SizeSSZ() (size int) {
	size = 93
	return
}

// HashTreeRoot ssz hashes the Builder object
func (b *Builder) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the Builder object with a hasher
func (b *Builder) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'PublicKey'
	hh.PutBytes(b.PublicKey[:])

	// Field (1) 'Version'
	hh.PutUint8(b.Version)

	// Field (2) 'ExecutionAddress'
	hh.PutBytes(b.ExecutionAddress[:])

	// Field (3) 'Balance'
	hh.PutUint64(uint64(b.Balance))

	// Field (4) 'DepositEpoch'
	hh.PutUint64(uint64(b.DepositEpoch))

	// Field (5) 'WithdrawableEpoch'
	hh.PutUint64(uint64(b.WithdrawableEpoch))

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the Builder object
func (b *Builder) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(b)
}
