// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 93a3638d29d1033f5d77582e002a25ce16b7709e67d9a577dca2e2eee05fc03a
// Version: v1.2.1 (https://github.com/pk910/dynamic-ssz)
package gloas

import (
	"encoding/binary"

	"github.com/attestantio/go-eth2-client/spec/phase0"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *BuilderPendingWithdrawal) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *BuilderPendingWithdrawal) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(BuilderPendingWithdrawal)
	}
	{ // Field #0 'FeeRecipient'
		dst = append(dst, t.FeeRecipient[:20]...)
	}
	{ // Field #1 'Amount'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.Amount))
	}
	{ // Field #2 'BuilderIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.BuilderIndex))
	}
	return dst, nil
}

func (t *BuilderPendingWithdrawal) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 36 {
		return sszutils.ErrUnexpectedEOF
	}
	{ // Field #0 'FeeRecipient' (static)
		buf := buf[0:20]
		copy(t.FeeRecipient[:], buf)
	}
	{ // Field #1 'Amount' (static)
		buf := buf[20:28]
		t.Amount = phase0.Gwei(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #2 'BuilderIndex' (static)
		buf := buf[28:36]
		t.BuilderIndex = BuilderIndex(binary.LittleEndian.Uint64(buf))
	}
	return nil
}

func (t *BuilderPendingWithdrawal) SizeSSZ() (size int) {
	return 36
}

func (t *BuilderPendingWithdrawal) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
func (t *BuilderPendingWithdrawal) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BuilderPendingWithdrawal)
	}
	idx := hh.Index()
	{ // Field #0 'FeeRecipient'
		hh.PutBytes(t.FeeRecipient[:20])
	}
	{ // Field #1 'Amount'
		hh.PutUint64(uint64(t.Amount))
	}
	{ // Field #2 'BuilderIndex'
		hh.PutUint64(uint64(t.BuilderIndex))
	}
	hh.Merkleize(idx)
	return nil
}

