// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 5c047d08712b5b457e3755b11439fec4573531a4bc91cb732e26e8bc832e793e
// Version: v1.2.0 (https://github.com/pk910/dynamic-ssz)
package gloas

import (
	"encoding/binary"

	"github.com/attestantio/go-eth2-client/spec/phase0"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *BuilderPendingPayment) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *BuilderPendingPayment) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(BuilderPendingPayment)
	}
	{ // Field #0 'Weight'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.Weight))
	}
	{ // Field #1 'Withdrawal'
		t := t.Withdrawal
		if t == nil {
			t = new(BuilderPendingWithdrawal)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, err
		}
	}
	return dst, nil
}

func (t *BuilderPendingPayment) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 44 {
		return sszutils.ErrUnexpectedEOF
	}
	{ // Field #0 'Weight' (static)
		buf := buf[0:8]
		t.Weight = phase0.Gwei(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #1 'Withdrawal' (static)
		buf := buf[8:44]
		if t.Withdrawal == nil {
			t.Withdrawal = new(BuilderPendingWithdrawal)
		}
		if err = t.Withdrawal.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return nil
}

func (t *BuilderPendingPayment) SizeSSZ() (size int) {
	return 44
}

func (t *BuilderPendingPayment) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
func (t *BuilderPendingPayment) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BuilderPendingPayment)
	}
	idx := hh.Index()
	{ // Field #0 'Weight'
		hh.PutUint64(uint64(t.Weight))
	}
	{ // Field #1 'Withdrawal'
		t := t.Withdrawal
		if t == nil {
			t = new(BuilderPendingWithdrawal)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	hh.Merkleize(idx)
	return nil
}

