// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: db12409bf50b91c6f52f202af267d9568353d439dc64ed6728a2359ff4ff198a
// Version: v1.2.1 (https://github.com/pk910/dynamic-ssz)
package gloas

import (
	"encoding/binary"

	"github.com/attestantio/go-eth2-client/spec/deneb"
	"github.com/attestantio/go-eth2-client/spec/electra"
	"github.com/attestantio/go-eth2-client/spec/phase0"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *ExecutionPayloadEnvelope) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *ExecutionPayloadEnvelope) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(ExecutionPayloadEnvelope)
	}
	dstlen := len(dst)
	// Offset #0 'Payload'
	offset0 := len(dst)
	dst = append(dst, 0, 0, 0, 0)
	// Offset #1 'ExecutionRequests'
	offset1 := len(dst)
	dst = append(dst, 0, 0, 0, 0)
	{ // Field #2 'BuilderIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.BuilderIndex))
	}
	{ // Field #3 'BeaconBlockRoot'
		dst = append(dst, t.BeaconBlockRoot[:32]...)
	}
	{ // Field #4 'Slot'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.Slot))
	}
	// Offset #5 'BlobKZGCommitments'
	offset5 := len(dst)
	dst = append(dst, 0, 0, 0, 0)
	{ // Field #6 'StateRoot'
		dst = append(dst, t.StateRoot[:32]...)
	}
	{ // Dynamic Field #0 'Payload'
		binary.LittleEndian.PutUint32(dst[offset0:], uint32(len(dst)-dstlen))
		t := t.Payload
		if t == nil {
			t = new(deneb.ExecutionPayload)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, err
		}
	}
	{ // Dynamic Field #1 'ExecutionRequests'
		binary.LittleEndian.PutUint32(dst[offset1:], uint32(len(dst)-dstlen))
		t := t.ExecutionRequests
		if t == nil {
			t = new(electra.ExecutionRequests)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, err
		}
	}
	{ // Dynamic Field #5 'BlobKZGCommitments'
		binary.LittleEndian.PutUint32(dst[offset5:], uint32(len(dst)-dstlen))
		t := t.BlobKZGCommitments
		vlen := len(t)
		if vlen > 4096 {
			return nil, sszutils.ErrListTooBig
		}
		for i := range vlen {
			dst = append(dst, t[i][:48]...)
		}
	}
	return dst, nil
}

func (t *ExecutionPayloadEnvelope) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 92 {
		return sszutils.ErrUnexpectedEOF
	}
	// Field #0 'Payload' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 92 {
		return sszutils.ErrOffset
	}
	// Field #1 'ExecutionRequests' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[4:8]))
	if offset1 < offset0 || offset1 > buflen {
		return sszutils.ErrOffset
	}
	{ // Field #2 'BuilderIndex' (static)
		buf := buf[8:16]
		t.BuilderIndex = BuilderIndex(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #3 'BeaconBlockRoot' (static)
		buf := buf[16:48]
		copy(t.BeaconBlockRoot[:], buf)
	}
	{ // Field #4 'Slot' (static)
		buf := buf[48:56]
		t.Slot = phase0.Slot(binary.LittleEndian.Uint64(buf))
	}
	// Field #5 'BlobKZGCommitments' (offset)
	offset5 := int(binary.LittleEndian.Uint32(buf[56:60]))
	if offset5 < offset1 || offset5 > buflen {
		return sszutils.ErrOffset
	}
	{ // Field #6 'StateRoot' (static)
		buf := buf[60:92]
		copy(t.StateRoot[:], buf)
	}
	{ // Field #0 'Payload' (dynamic)
		buf := buf[offset0:offset1]
		val1 := t.Payload
		if val1 == nil {
			val1 = new(deneb.ExecutionPayload)
		}
		if err = val1.UnmarshalSSZ(buf); err != nil {
			return err
		}
		t.Payload = val1
	}
	{ // Field #1 'ExecutionRequests' (dynamic)
		buf := buf[offset1:offset5]
		val2 := t.ExecutionRequests
		if val2 == nil {
			val2 = new(electra.ExecutionRequests)
		}
		if err = val2.UnmarshalSSZ(buf); err != nil {
			return err
		}
		t.ExecutionRequests = val2
	}
	{ // Field #5 'BlobKZGCommitments' (dynamic)
		buf := buf[offset5:]
		val3 := t.BlobKZGCommitments
		itemCount := len(buf) / 48
		if len(buf)%48 != 0 {
			return sszutils.ErrUnexpectedEOF
		}
		val3 = sszutils.ExpandSlice(val3, itemCount)
		for i := range itemCount {
			buf := buf[48*i : 48*(i+1)]
			copy(val3[i][:], buf)
		}
		t.BlobKZGCommitments = val3
	}
	return nil
}

func (t *ExecutionPayloadEnvelope) SizeSSZ() (size int) {
	if t == nil {
		t = new(ExecutionPayloadEnvelope)
	}
	// Field #0 'Payload' offset (4 bytes)
	// Field #1 'ExecutionRequests' offset (4 bytes)
	// Field #2 'BuilderIndex' static (8 bytes)
	// Field #3 'BeaconBlockRoot' static (32 bytes)
	// Field #4 'Slot' static (8 bytes)
	// Field #5 'BlobKZGCommitments' offset (4 bytes)
	// Field #6 'StateRoot' static (32 bytes)
	size += 92
	{ // Dynamic field #0 'Payload'
		size += t.Payload.SizeSSZ()
	}
	{ // Dynamic field #1 'ExecutionRequests'
		size += t.ExecutionRequests.SizeSSZ()
	}
	{ // Dynamic field #5 'BlobKZGCommitments'
		size += len(t.BlobKZGCommitments) * 48
	}
	return size
}

func (t *ExecutionPayloadEnvelope) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
func (t *ExecutionPayloadEnvelope) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(ExecutionPayloadEnvelope)
	}
	idx := hh.Index()
	{ // Field #0 'Payload'
		t := t.Payload
		if t == nil {
			t = new(deneb.ExecutionPayload)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	{ // Field #1 'ExecutionRequests'
		t := t.ExecutionRequests
		if t == nil {
			t = new(electra.ExecutionRequests)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	{ // Field #2 'BuilderIndex'
		hh.PutUint64(uint64(t.BuilderIndex))
	}
	{ // Field #3 'BeaconBlockRoot'
		hh.PutBytes(t.BeaconBlockRoot[:32])
	}
	{ // Field #4 'Slot'
		hh.PutUint64(uint64(t.Slot))
	}
	{ // Field #5 'BlobKZGCommitments'
		t := t.BlobKZGCommitments
		vlen := uint64(len(t))
		if vlen > 4096 {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := range int(vlen) {
			hh.PutBytes(t[i][:48])
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(4096, vlen, 32))
	}
	{ // Field #6 'StateRoot'
		hh.PutBytes(t.StateRoot[:32])
	}
	hh.Merkleize(idx)
	return nil
}

