// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: b11cc2a2d8d878dd38c73756e3a16b183c77bc4a93c918e26cc06f54e54bb102
// Version: v1.3.0 (https://github.com/pk910/dynamic-ssz)
package gloas

import (
	"encoding/binary"

	"github.com/attestantio/go-eth2-client/spec/deneb"
	"github.com/attestantio/go-eth2-client/spec/electra"
	"github.com/attestantio/go-eth2-client/spec/phase0"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

// MarshalSSZ marshals the *ExecutionPayloadEnvelope to SSZ-encoded bytes.
func (t *ExecutionPayloadEnvelope) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *ExecutionPayloadEnvelope to SSZ-encoded bytes, appending to the provided buffer.
func (t *ExecutionPayloadEnvelope) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(ExecutionPayloadEnvelope)
	}
	dstlen := len(dst)
	// Offset Field #0 'Payload'
	// Offset Field #1 'ExecutionRequests'
	dst = append(dst, 0, 0, 0, 0, 0, 0, 0, 0)
	{ // Static Field #2 'BuilderIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.BuilderIndex))
	}
	{ // Static Field #3 'BeaconBlockRoot'
		dst = append(dst, t.BeaconBlockRoot[:32]...)
	}
	{ // Static Field #4 'Slot'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.Slot))
	}
	{ // Static Field #5 'StateRoot'
		dst = append(dst, t.StateRoot[:32]...)
	}
	{ // Dynamic Field #0 'Payload'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.Payload
		if t == nil {
			t = new(deneb.ExecutionPayload)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "Payload")
		}
	}
	{ // Dynamic Field #1 'ExecutionRequests'
		binary.LittleEndian.PutUint32(dst[dstlen+4:], uint32(len(dst)-dstlen))
		t := t.ExecutionRequests
		if t == nil {
			t = new(electra.ExecutionRequests)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "ExecutionRequests")
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *ExecutionPayloadEnvelope from SSZ-encoded bytes.
func (t *ExecutionPayloadEnvelope) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 88 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 88)
	}
	// Field #0 'Payload' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 88 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 88), "Payload:o")
	}
	// Field #1 'ExecutionRequests' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[4:8]))
	if offset1 < offset0 || offset1 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset1, offset0, buflen), "ExecutionRequests:o")
	}
	{ // Field #2 'BuilderIndex' (static)
		buf := buf[8:16]
		t.BuilderIndex = BuilderIndex(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #3 'BeaconBlockRoot' (static)
		buf := buf[16:48]
		copy(t.BeaconBlockRoot[:], buf)
	}
	{ // Field #4 'Slot' (static)
		buf := buf[48:56]
		t.Slot = phase0.Slot(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #5 'StateRoot' (static)
		buf := buf[56:88]
		copy(t.StateRoot[:], buf)
	}
	{ // Field #0 'Payload' (dynamic)
		buf := buf[offset0:offset1]
		if t.Payload == nil {
			t.Payload = new(deneb.ExecutionPayload)
		}
		if err = t.Payload.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "Payload")
		}
	}
	{ // Field #1 'ExecutionRequests' (dynamic)
		buf := buf[offset1:]
		if t.ExecutionRequests == nil {
			t.ExecutionRequests = new(electra.ExecutionRequests)
		}
		if err = t.ExecutionRequests.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "ExecutionRequests")
		}
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *ExecutionPayloadEnvelope.
func (t *ExecutionPayloadEnvelope) SizeSSZ() (size int) {
	if t == nil {
		t = new(ExecutionPayloadEnvelope)
	}
	// Field #0 'Payload' offset (4 bytes)
	// Field #1 'ExecutionRequests' offset (4 bytes)
	// Field #2 'BuilderIndex' static (8 bytes)
	// Field #3 'BeaconBlockRoot' static (32 bytes)
	// Field #4 'Slot' static (8 bytes)
	// Field #5 'StateRoot' static (32 bytes)
	size += 88
	{ // Dynamic field #0 'Payload'
		size += t.Payload.SizeSSZ()
	}
	{ // Dynamic field #1 'ExecutionRequests'
		size += t.ExecutionRequests.SizeSSZ()
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *ExecutionPayloadEnvelope.
func (t *ExecutionPayloadEnvelope) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
// HashTreeRootWith computes the SSZ hash tree root of the *ExecutionPayloadEnvelope using the given hash walker.
func (t *ExecutionPayloadEnvelope) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(ExecutionPayloadEnvelope)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Payload'
		t := t.Payload
		if t == nil {
			t = new(deneb.ExecutionPayload)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "Payload")
		}
	}
	{ // Field #1 'ExecutionRequests'
		t := t.ExecutionRequests
		if t == nil {
			t = new(electra.ExecutionRequests)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "ExecutionRequests")
		}
	}
	{ // Field #2 'BuilderIndex'
		hh.PutUint64(uint64(t.BuilderIndex))
	}
	{ // Field #3 'BeaconBlockRoot'
		hh.PutBytes(t.BeaconBlockRoot[:32])
	}
	{ // Field #4 'Slot'
		hh.PutUint64(uint64(t.Slot))
	}
	{ // Field #5 'StateRoot'
		hh.PutBytes(t.StateRoot[:32])
	}
	hh.Merkleize(idx)
	return nil
}
