// Code generated by fastssz. DO NOT EDIT.
// Hash: da971fd7603047585d3acf750304f2185322d7661ae317da0a383920e8630cfa
// Version: 0.1.3
package gloas

import (
	"github.com/attestantio/go-eth2-client/spec/phase0"
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the ExecutionPayloadBid object
func (e *ExecutionPayloadBid) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(e)
}

// MarshalSSZTo ssz marshals the ExecutionPayloadBid object to a target array
func (e *ExecutionPayloadBid) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'ParentBlockHash'
	dst = append(dst, e.ParentBlockHash[:]...)

	// Field (1) 'ParentBlockRoot'
	dst = append(dst, e.ParentBlockRoot[:]...)

	// Field (2) 'BlockHash'
	dst = append(dst, e.BlockHash[:]...)

	// Field (3) 'PrevRandao'
	dst = append(dst, e.PrevRandao[:]...)

	// Field (4) 'FeeRecipient'
	dst = append(dst, e.FeeRecipient[:]...)

	// Field (5) 'GasLimit'
	dst = ssz.MarshalUint64(dst, e.GasLimit)

	// Field (6) 'BuilderIndex'
	dst = ssz.MarshalUint64(dst, uint64(e.BuilderIndex))

	// Field (7) 'Slot'
	dst = ssz.MarshalUint64(dst, uint64(e.Slot))

	// Field (8) 'Value'
	dst = ssz.MarshalUint64(dst, uint64(e.Value))

	// Field (9) 'ExecutionPayment'
	dst = ssz.MarshalUint64(dst, uint64(e.ExecutionPayment))

	// Field (10) 'BlobKZGCommitmentsRoot'
	dst = append(dst, e.BlobKZGCommitmentsRoot[:]...)

	return
}

// UnmarshalSSZ ssz unmarshals the ExecutionPayloadBid object
func (e *ExecutionPayloadBid) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 220 {
		return ssz.ErrSize
	}

	// Field (0) 'ParentBlockHash'
	copy(e.ParentBlockHash[:], buf[0:32])

	// Field (1) 'ParentBlockRoot'
	copy(e.ParentBlockRoot[:], buf[32:64])

	// Field (2) 'BlockHash'
	copy(e.BlockHash[:], buf[64:96])

	// Field (3) 'PrevRandao'
	copy(e.PrevRandao[:], buf[96:128])

	// Field (4) 'FeeRecipient'
	copy(e.FeeRecipient[:], buf[128:148])

	// Field (5) 'GasLimit'
	e.GasLimit = ssz.UnmarshallUint64(buf[148:156])

	// Field (6) 'BuilderIndex'
	e.BuilderIndex = BuilderIndex(ssz.UnmarshallUint64(buf[156:164]))

	// Field (7) 'Slot'
	e.Slot = phase0.Slot(ssz.UnmarshallUint64(buf[164:172]))

	// Field (8) 'Value'
	e.Value = phase0.Gwei(ssz.UnmarshallUint64(buf[172:180]))

	// Field (9) 'ExecutionPayment'
	e.ExecutionPayment = phase0.Gwei(ssz.UnmarshallUint64(buf[180:188]))

	// Field (10) 'BlobKZGCommitmentsRoot'
	copy(e.BlobKZGCommitmentsRoot[:], buf[188:220])

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the ExecutionPayloadBid object
func (e *ExecutionPayloadBid) SizeSSZ() (size int) {
	size = 220
	return
}

// HashTreeRoot ssz hashes the ExecutionPayloadBid object
func (e *ExecutionPayloadBid) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(e)
}

// HashTreeRootWith ssz hashes the ExecutionPayloadBid object with a hasher
func (e *ExecutionPayloadBid) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'ParentBlockHash'
	hh.PutBytes(e.ParentBlockHash[:])

	// Field (1) 'ParentBlockRoot'
	hh.PutBytes(e.ParentBlockRoot[:])

	// Field (2) 'BlockHash'
	hh.PutBytes(e.BlockHash[:])

	// Field (3) 'PrevRandao'
	hh.PutBytes(e.PrevRandao[:])

	// Field (4) 'FeeRecipient'
	hh.PutBytes(e.FeeRecipient[:])

	// Field (5) 'GasLimit'
	hh.PutUint64(e.GasLimit)

	// Field (6) 'BuilderIndex'
	hh.PutUint64(uint64(e.BuilderIndex))

	// Field (7) 'Slot'
	hh.PutUint64(uint64(e.Slot))

	// Field (8) 'Value'
	hh.PutUint64(uint64(e.Value))

	// Field (9) 'ExecutionPayment'
	hh.PutUint64(uint64(e.ExecutionPayment))

	// Field (10) 'BlobKZGCommitmentsRoot'
	hh.PutBytes(e.BlobKZGCommitmentsRoot[:])

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the ExecutionPayloadBid object
func (e *ExecutionPayloadBid) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(e)
}
