// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 1b3d663890caf51d0df5a027717db34c3381587418cd9fb140babc571433ba11
// Version: v1.2.1 (https://github.com/pk910/dynamic-ssz)
package gloas

import (
	"encoding/binary"

	"github.com/attestantio/go-eth2-client/spec/phase0"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *ExecutionPayloadBid) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *ExecutionPayloadBid) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(ExecutionPayloadBid)
	}
	{ // Field #0 'ParentBlockHash'
		dst = append(dst, t.ParentBlockHash[:32]...)
	}
	{ // Field #1 'ParentBlockRoot'
		dst = append(dst, t.ParentBlockRoot[:32]...)
	}
	{ // Field #2 'BlockHash'
		dst = append(dst, t.BlockHash[:32]...)
	}
	{ // Field #3 'PrevRandao'
		dst = append(dst, t.PrevRandao[:32]...)
	}
	{ // Field #4 'FeeRecipient'
		dst = append(dst, t.FeeRecipient[:20]...)
	}
	{ // Field #5 'GasLimit'
		dst = binary.LittleEndian.AppendUint64(dst, t.GasLimit)
	}
	{ // Field #6 'BuilderIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.BuilderIndex))
	}
	{ // Field #7 'Slot'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.Slot))
	}
	{ // Field #8 'Value'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.Value))
	}
	{ // Field #9 'ExecutionPayment'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.ExecutionPayment))
	}
	{ // Field #10 'BlobKZGCommitmentsRoot'
		dst = append(dst, t.BlobKZGCommitmentsRoot[:32]...)
	}
	return dst, nil
}

func (t *ExecutionPayloadBid) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 220 {
		return sszutils.ErrUnexpectedEOF
	}
	{ // Field #0 'ParentBlockHash' (static)
		buf := buf[0:32]
		copy(t.ParentBlockHash[:], buf)
	}
	{ // Field #1 'ParentBlockRoot' (static)
		buf := buf[32:64]
		copy(t.ParentBlockRoot[:], buf)
	}
	{ // Field #2 'BlockHash' (static)
		buf := buf[64:96]
		copy(t.BlockHash[:], buf)
	}
	{ // Field #3 'PrevRandao' (static)
		buf := buf[96:128]
		copy(t.PrevRandao[:], buf)
	}
	{ // Field #4 'FeeRecipient' (static)
		buf := buf[128:148]
		copy(t.FeeRecipient[:], buf)
	}
	{ // Field #5 'GasLimit' (static)
		buf := buf[148:156]
		t.GasLimit = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #6 'BuilderIndex' (static)
		buf := buf[156:164]
		t.BuilderIndex = BuilderIndex(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #7 'Slot' (static)
		buf := buf[164:172]
		t.Slot = phase0.Slot(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #8 'Value' (static)
		buf := buf[172:180]
		t.Value = phase0.Gwei(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #9 'ExecutionPayment' (static)
		buf := buf[180:188]
		t.ExecutionPayment = phase0.Gwei(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #10 'BlobKZGCommitmentsRoot' (static)
		buf := buf[188:220]
		copy(t.BlobKZGCommitmentsRoot[:], buf)
	}
	return nil
}

func (t *ExecutionPayloadBid) SizeSSZ() (size int) {
	return 220
}

func (t *ExecutionPayloadBid) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
func (t *ExecutionPayloadBid) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(ExecutionPayloadBid)
	}
	idx := hh.Index()
	{ // Field #0 'ParentBlockHash'
		hh.PutBytes(t.ParentBlockHash[:32])
	}
	{ // Field #1 'ParentBlockRoot'
		hh.PutBytes(t.ParentBlockRoot[:32])
	}
	{ // Field #2 'BlockHash'
		hh.PutBytes(t.BlockHash[:32])
	}
	{ // Field #3 'PrevRandao'
		hh.PutBytes(t.PrevRandao[:32])
	}
	{ // Field #4 'FeeRecipient'
		hh.PutBytes(t.FeeRecipient[:20])
	}
	{ // Field #5 'GasLimit'
		hh.PutUint64(t.GasLimit)
	}
	{ // Field #6 'BuilderIndex'
		hh.PutUint64(uint64(t.BuilderIndex))
	}
	{ // Field #7 'Slot'
		hh.PutUint64(uint64(t.Slot))
	}
	{ // Field #8 'Value'
		hh.PutUint64(uint64(t.Value))
	}
	{ // Field #9 'ExecutionPayment'
		hh.PutUint64(uint64(t.ExecutionPayment))
	}
	{ // Field #10 'BlobKZGCommitmentsRoot'
		hh.PutBytes(t.BlobKZGCommitmentsRoot[:32])
	}
	hh.Merkleize(idx)
	return nil
}

