// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 069dca98bfd4cef9ab2165e7ee41605bf903b76aab19e5801011017efc138c60
// Version: v1.2.1 (https://github.com/pk910/dynamic-ssz)
package gloas

import (
	"encoding/binary"

	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *PayloadAttestation) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *PayloadAttestation) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(PayloadAttestation)
	}
	dstlen := len(dst)
	// Offset #0 'AggregationBits'
	offset0 := len(dst)
	dst = append(dst, 0, 0, 0, 0)
	{ // Field #1 'Data'
		t := t.Data
		if t == nil {
			t = new(PayloadAttestationData)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, err
		}
	}
	{ // Field #2 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	{ // Dynamic Field #0 'AggregationBits'
		binary.LittleEndian.PutUint32(dst[offset0:], uint32(len(dst)-dstlen))
		t := t.AggregationBits
		vlen := len(t)
		if vlen > 64 {
			return nil, sszutils.ErrListTooBig
		}
		bval := []byte(t[:])
		if vlen == 0 {
			bval = []byte{0x01}
		} else if bval[vlen-1] == 0x00 {
			return nil, sszutils.ErrBitlistNotTerminated
		}
		dst = append(dst, bval...)
	}
	return dst, nil
}

func (t *PayloadAttestation) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 142 {
		return sszutils.ErrUnexpectedEOF
	}
	// Field #0 'AggregationBits' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 142 {
		return sszutils.ErrOffset
	}
	{ // Field #1 'Data' (static)
		buf := buf[4:46]
		if t.Data == nil {
			t.Data = new(PayloadAttestationData)
		}
		if err = t.Data.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	{ // Field #2 'Signature' (static)
		buf := buf[46:142]
		copy(t.Signature[:], buf)
	}
	{ // Field #0 'AggregationBits' (dynamic)
		buf := buf[offset0:]
		val1 := t.AggregationBits
		blen := len(buf)
		if blen == 0 || buf[blen-1] == 0x00 {
			return sszutils.ErrBitlistNotTerminated
		}
		val1 = sszutils.ExpandSlice(val1, blen)
		copy(val1[:], buf)
		t.AggregationBits = val1
	}
	return nil
}

func (t *PayloadAttestation) SizeSSZ() (size int) {
	if t == nil {
		t = new(PayloadAttestation)
	}
	// Field #0 'AggregationBits' offset (4 bytes)
	// Field #1 'Data' static (42 bytes)
	// Field #2 'Signature' static (96 bytes)
	size += 142
	{ // Dynamic field #0 'AggregationBits'
		size += len(t.AggregationBits)
	}
	return size
}

func (t *PayloadAttestation) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
func (t *PayloadAttestation) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(PayloadAttestation)
	}
	idx := hh.Index()
	{ // Field #0 'AggregationBits'
		t := t.AggregationBits
		idx := hh.Index()
		bitlist, size := hasher.ParseBitlistWithHasher(hh, t[:])
		if size > 64 {
			return sszutils.ErrListTooBig
		}
		hh.AppendBytes32(bitlist)
		hh.MerkleizeWithMixin(idx, size, (64+255)/256)
	}
	{ // Field #1 'Data'
		t := t.Data
		if t == nil {
			t = new(PayloadAttestationData)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	{ // Field #2 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}

