// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: bc7c6dc18dab78bc139b97fbd8777cc5cc5aa36fd9e267e054cad05789205c6d
// Version: v1.2.0 (https://github.com/pk910/dynamic-ssz)
package gloas

import (
	"encoding/binary"

	"github.com/attestantio/go-eth2-client/spec/phase0"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *PayloadAttestationData) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *PayloadAttestationData) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(PayloadAttestationData)
	}
	{ // Field #0 'BeaconBlockRoot'
		dst = append(dst, t.BeaconBlockRoot[:32]...)
	}
	{ // Field #1 'Slot'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.Slot))
	}
	{ // Field #2 'PayloadPresent'
		dst = sszutils.MarshalBool(dst, t.PayloadPresent)
	}
	{ // Field #3 'BlobDataAvailable'
		dst = sszutils.MarshalBool(dst, t.BlobDataAvailable)
	}
	return dst, nil
}

func (t *PayloadAttestationData) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 42 {
		return sszutils.ErrUnexpectedEOF
	}
	{ // Field #0 'BeaconBlockRoot' (static)
		buf := buf[0:32]
		copy(t.BeaconBlockRoot[:], buf)
	}
	{ // Field #1 'Slot' (static)
		buf := buf[32:40]
		t.Slot = phase0.Slot(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #2 'PayloadPresent' (static)
		buf := buf[40:41]
		if buf[0] != 1 && buf[0] != 0 {
			return sszutils.ErrInvalidValueRange
		}
		t.PayloadPresent = buf[0] == 1
	}
	{ // Field #3 'BlobDataAvailable' (static)
		buf := buf[41:42]
		if buf[0] != 1 && buf[0] != 0 {
			return sszutils.ErrInvalidValueRange
		}
		t.BlobDataAvailable = buf[0] == 1
	}
	return nil
}

func (t *PayloadAttestationData) SizeSSZ() (size int) {
	return 42
}

func (t *PayloadAttestationData) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
func (t *PayloadAttestationData) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(PayloadAttestationData)
	}
	idx := hh.Index()
	{ // Field #0 'BeaconBlockRoot'
		hh.PutBytes(t.BeaconBlockRoot[:32])
	}
	{ // Field #1 'Slot'
		hh.PutUint64(uint64(t.Slot))
	}
	{ // Field #2 'PayloadPresent'
		hh.PutBool(t.PayloadPresent)
	}
	{ // Field #3 'BlobDataAvailable'
		hh.PutBool(t.BlobDataAvailable)
	}
	hh.Merkleize(idx)
	return nil
}

