// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 3908ebeeeffed33153f7c3f68780c43415eba9226b0a17b9aa73ddbe3e0a9892
// Version: v1.2.1 (https://github.com/pk910/dynamic-ssz)
package gloas

import (
	"encoding/binary"

	"github.com/attestantio/go-eth2-client/spec/phase0"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *PayloadAttestationMessage) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *PayloadAttestationMessage) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(PayloadAttestationMessage)
	}
	{ // Field #0 'ValidatorIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.ValidatorIndex))
	}
	{ // Field #1 'Data'
		t := t.Data
		if t == nil {
			t = new(PayloadAttestationData)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, err
		}
	}
	{ // Field #2 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	return dst, nil
}

func (t *PayloadAttestationMessage) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 146 {
		return sszutils.ErrUnexpectedEOF
	}
	{ // Field #0 'ValidatorIndex' (static)
		buf := buf[0:8]
		t.ValidatorIndex = phase0.ValidatorIndex(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #1 'Data' (static)
		buf := buf[8:50]
		if t.Data == nil {
			t.Data = new(PayloadAttestationData)
		}
		if err = t.Data.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	{ // Field #2 'Signature' (static)
		buf := buf[50:146]
		copy(t.Signature[:], buf)
	}
	return nil
}

func (t *PayloadAttestationMessage) SizeSSZ() (size int) {
	return 146
}

func (t *PayloadAttestationMessage) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
func (t *PayloadAttestationMessage) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(PayloadAttestationMessage)
	}
	idx := hh.Index()
	{ // Field #0 'ValidatorIndex'
		hh.PutUint64(uint64(t.ValidatorIndex))
	}
	{ // Field #1 'Data'
		t := t.Data
		if t == nil {
			t = new(PayloadAttestationData)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	{ // Field #2 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}

