// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: d364ccca834fb67bd4d5a37608621f3922221764a89d029bce7228a62874d901
// Version: v1.2.2 (https://github.com/pk910/dynamic-ssz)
package gloas

import (
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *PayloadAttestation) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *PayloadAttestation) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(PayloadAttestation)
	}
	{ // Field #0 'AggregationBits'
		vlen := len(t.AggregationBits)
		if vlen > 64 {
			return nil, sszutils.ErrVectorLength
		}
		dst = append(dst, t.AggregationBits[:vlen]...)
		if vlen < 64 {
			dst = sszutils.AppendZeroPadding(dst, (64-vlen)*1)
		}
	}
	{ // Field #1 'Data'
		t := t.Data
		if t == nil {
			t = new(PayloadAttestationData)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, err
		}
	}
	{ // Field #2 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	return dst, nil
}

func (t *PayloadAttestation) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 202 {
		return sszutils.ErrUnexpectedEOF
	}
	{ // Field #0 'AggregationBits' (static)
		buf := buf[0:64]
		t.AggregationBits = sszutils.ExpandSlice(t.AggregationBits, 64)
		copy(t.AggregationBits[:], buf)
	}
	{ // Field #1 'Data' (static)
		buf := buf[64:106]
		if t.Data == nil {
			t.Data = new(PayloadAttestationData)
		}
		if err = t.Data.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	{ // Field #2 'Signature' (static)
		buf := buf[106:202]
		copy(t.Signature[:], buf)
	}
	return nil
}

func (t *PayloadAttestation) SizeSSZ() (size int) {
	return 202
}

func (t *PayloadAttestation) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
func (t *PayloadAttestation) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(PayloadAttestation)
	}
	idx := hh.Index()
	{ // Field #0 'AggregationBits'
		vlen := len(t.AggregationBits)
		if vlen > 64 {
			return sszutils.ErrVectorLength
		}
		val := t.AggregationBits[:]
		if vlen < 64 {
			val = sszutils.AppendZeroPadding(val, (64-vlen)*1)
		}
		hh.PutBytes(val[:64])
	}
	{ // Field #1 'Data'
		t := t.Data
		if t == nil {
			t = new(PayloadAttestationData)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	{ // Field #2 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}
