// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 8295c875069e1c44bb07f12b924408d40f59e683f603a1b4dbfd850b532c2c31
// Version: v1.2.2 (https://github.com/pk910/dynamic-ssz)
package gloas

import (
	"encoding/binary"

	"github.com/attestantio/go-eth2-client/spec/phase0"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *ProposerPreferences) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *ProposerPreferences) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(ProposerPreferences)
	}
	{ // Field #0 'ProposalSlot'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.ProposalSlot))
	}
	{ // Field #1 'ValidatorIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.ValidatorIndex))
	}
	{ // Field #2 'FeeRecipient'
		dst = append(dst, t.FeeRecipient[:20]...)
	}
	{ // Field #3 'GasLimit'
		dst = binary.LittleEndian.AppendUint64(dst, t.GasLimit)
	}
	return dst, nil
}

func (t *ProposerPreferences) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 44 {
		return sszutils.ErrUnexpectedEOF
	}
	{ // Field #0 'ProposalSlot' (static)
		buf := buf[0:8]
		t.ProposalSlot = phase0.Slot(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #1 'ValidatorIndex' (static)
		buf := buf[8:16]
		t.ValidatorIndex = phase0.ValidatorIndex(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #2 'FeeRecipient' (static)
		buf := buf[16:36]
		copy(t.FeeRecipient[:], buf)
	}
	{ // Field #3 'GasLimit' (static)
		buf := buf[36:44]
		t.GasLimit = binary.LittleEndian.Uint64(buf)
	}
	return nil
}

func (t *ProposerPreferences) SizeSSZ() (size int) {
	return 44
}

func (t *ProposerPreferences) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
func (t *ProposerPreferences) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(ProposerPreferences)
	}
	idx := hh.Index()
	{ // Field #0 'ProposalSlot'
		hh.PutUint64(uint64(t.ProposalSlot))
	}
	{ // Field #1 'ValidatorIndex'
		hh.PutUint64(uint64(t.ValidatorIndex))
	}
	{ // Field #2 'FeeRecipient'
		hh.PutBytes(t.FeeRecipient[:20])
	}
	{ // Field #3 'GasLimit'
		hh.PutUint64(t.GasLimit)
	}
	hh.Merkleize(idx)
	return nil
}
