// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 5d9918f3e3417d668ed01ca31b8b7549926d1707979d1f06c8dccca37c4f0137
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package gloas

import (
	"encoding/binary"

	"github.com/ethpandaops/go-eth2-client/spec/phase0"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

// MarshalSSZ marshals the *ProposerPreferences to SSZ-encoded bytes.
func (t *ProposerPreferences) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *ProposerPreferences to SSZ-encoded bytes, appending to the provided buffer.
func (t *ProposerPreferences) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(ProposerPreferences)
	}
	{ // Static Field #0 'DependentRoot'
		dst = append(dst, t.DependentRoot[:32]...)
	}
	{ // Static Field #1 'ProposalSlot'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.ProposalSlot))
	}
	{ // Static Field #2 'ValidatorIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.ValidatorIndex))
	}
	{ // Static Field #3 'FeeRecipient'
		dst = append(dst, t.FeeRecipient[:20]...)
	}
	{ // Static Field #4 'GasLimit'
		dst = binary.LittleEndian.AppendUint64(dst, t.GasLimit)
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *ProposerPreferences from SSZ-encoded bytes.
func (t *ProposerPreferences) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 76 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 76)
	}
	{ // Field #0 'DependentRoot' (static)
		buf := buf[0:32]
		copy(t.DependentRoot[:], buf)
	}
	{ // Field #1 'ProposalSlot' (static)
		buf := buf[32:40]
		t.ProposalSlot = phase0.Slot(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #2 'ValidatorIndex' (static)
		buf := buf[40:48]
		t.ValidatorIndex = phase0.ValidatorIndex(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #3 'FeeRecipient' (static)
		buf := buf[48:68]
		copy(t.FeeRecipient[:], buf)
	}
	{ // Field #4 'GasLimit' (static)
		buf := buf[68:76]
		t.GasLimit = binary.LittleEndian.Uint64(buf)
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *ProposerPreferences.
func (t *ProposerPreferences) SizeSSZ() (size int) {
	return 76
}

// HashTreeRoot computes the SSZ hash tree root of the *ProposerPreferences.
func (t *ProposerPreferences) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *ProposerPreferences using the given hash walker.
func (t *ProposerPreferences) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(ProposerPreferences)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'DependentRoot'
		hh.PutBytes(t.DependentRoot[:32])
	}
	{ // Field #1 'ProposalSlot'
		hh.PutUint64(uint64(t.ProposalSlot))
	}
	{ // Field #2 'ValidatorIndex'
		hh.PutUint64(uint64(t.ValidatorIndex))
	}
	{ // Field #3 'FeeRecipient'
		hh.PutBytes(t.FeeRecipient[:20])
	}
	{ // Field #4 'GasLimit'
		hh.PutUint64(t.GasLimit)
	}
	hh.Merkleize(idx)
	return nil
}
