// Code generated by fastssz. DO NOT EDIT.
// Hash: da971fd7603047585d3acf750304f2185322d7661ae317da0a383920e8630cfa
// Version: 0.1.3
package gloas

import (
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the SignedExecutionPayloadBid object
func (s *SignedExecutionPayloadBid) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(s)
}

// MarshalSSZTo ssz marshals the SignedExecutionPayloadBid object to a target array
func (s *SignedExecutionPayloadBid) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'Message'
	if s.Message == nil {
		s.Message = new(ExecutionPayloadBid)
	}
	if dst, err = s.Message.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (1) 'Signature'
	dst = append(dst, s.Signature[:]...)

	return
}

// UnmarshalSSZ ssz unmarshals the SignedExecutionPayloadBid object
func (s *SignedExecutionPayloadBid) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 316 {
		return ssz.ErrSize
	}

	// Field (0) 'Message'
	if s.Message == nil {
		s.Message = new(ExecutionPayloadBid)
	}
	if err = s.Message.UnmarshalSSZ(buf[0:220]); err != nil {
		return err
	}

	// Field (1) 'Signature'
	copy(s.Signature[:], buf[220:316])

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the SignedExecutionPayloadBid object
func (s *SignedExecutionPayloadBid) SizeSSZ() (size int) {
	size = 316
	return
}

// HashTreeRoot ssz hashes the SignedExecutionPayloadBid object
func (s *SignedExecutionPayloadBid) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(s)
}

// HashTreeRootWith ssz hashes the SignedExecutionPayloadBid object with a hasher
func (s *SignedExecutionPayloadBid) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Message'
	if s.Message == nil {
		s.Message = new(ExecutionPayloadBid)
	}
	if err = s.Message.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'Signature'
	hh.PutBytes(s.Signature[:])

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the SignedExecutionPayloadBid object
func (s *SignedExecutionPayloadBid) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(s)
}
