// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 7d96fe43cab503be95871a1c0cc68580faf04ad620c11eee8880fe10a3ce80da
// Version: v1.2.0 (https://github.com/pk910/dynamic-ssz)
package gloas

import (
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *SignedExecutionPayloadBid) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *SignedExecutionPayloadBid) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(SignedExecutionPayloadBid)
	}
	{ // Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(ExecutionPayloadBid)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, err
		}
	}
	{ // Field #1 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	return dst, nil
}

func (t *SignedExecutionPayloadBid) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 316 {
		return sszutils.ErrUnexpectedEOF
	}
	{ // Field #0 'Message' (static)
		buf := buf[0:220]
		if t.Message == nil {
			t.Message = new(ExecutionPayloadBid)
		}
		if err = t.Message.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	{ // Field #1 'Signature' (static)
		buf := buf[220:316]
		copy(t.Signature[:], buf)
	}
	return nil
}

func (t *SignedExecutionPayloadBid) SizeSSZ() (size int) {
	return 316
}

func (t *SignedExecutionPayloadBid) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
func (t *SignedExecutionPayloadBid) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SignedExecutionPayloadBid)
	}
	idx := hh.Index()
	{ // Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(ExecutionPayloadBid)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	{ // Field #1 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}

