// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 6c435b7f02ad0723332b14bc83595f6d377bd14e86f8bfb5386f853eb837153b
// Version: v1.2.1 (https://github.com/pk910/dynamic-ssz)
package gloas

import (
	"encoding/binary"

	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *SignedExecutionPayloadBid) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *SignedExecutionPayloadBid) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(SignedExecutionPayloadBid)
	}
	dstlen := len(dst)
	// Offset #0 'Message'
	offset0 := len(dst)
	dst = append(dst, 0, 0, 0, 0)
	{ // Field #1 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	{ // Dynamic Field #0 'Message'
		binary.LittleEndian.PutUint32(dst[offset0:], uint32(len(dst)-dstlen))
		t := t.Message
		if t == nil {
			t = new(ExecutionPayloadBid)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, err
		}
	}
	return dst, nil
}

func (t *SignedExecutionPayloadBid) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 100 {
		return sszutils.ErrUnexpectedEOF
	}
	// Field #0 'Message' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 100 {
		return sszutils.ErrOffset
	}
	{ // Field #1 'Signature' (static)
		buf := buf[4:100]
		copy(t.Signature[:], buf)
	}
	{ // Field #0 'Message' (dynamic)
		buf := buf[offset0:]
		if t.Message == nil {
			t.Message = new(ExecutionPayloadBid)
		}
		if err = t.Message.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return nil
}

func (t *SignedExecutionPayloadBid) SizeSSZ() (size int) {
	if t == nil {
		t = new(SignedExecutionPayloadBid)
	}
	// Field #0 'Message' offset (4 bytes)
	// Field #1 'Signature' static (96 bytes)
	size += 100
	{ // Dynamic field #0 'Message'
		size += t.Message.SizeSSZ()
	}
	return size
}

func (t *SignedExecutionPayloadBid) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
func (t *SignedExecutionPayloadBid) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SignedExecutionPayloadBid)
	}
	idx := hh.Index()
	{ // Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(ExecutionPayloadBid)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	{ // Field #1 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}
