// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: dff6ab46869c0b3a9d9551a917e7dc3d6c5722fa3a010acf946c23b271079109
// Version: v1.2.1 (https://github.com/pk910/dynamic-ssz)
package phase0

import (
	"encoding/binary"

	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *Checkpoint) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *Checkpoint) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(Checkpoint)
	}
	{ // Field #0 'Epoch'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.Epoch))
	}
	{ // Field #1 'Root'
		dst = append(dst, t.Root[:32]...)
	}
	return dst, nil
}

func (t *Checkpoint) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 40 {
		return sszutils.ErrUnexpectedEOF
	}
	{ // Field #0 'Epoch' (static)
		buf := buf[0:8]
		t.Epoch = Epoch(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #1 'Root' (static)
		buf := buf[8:40]
		copy(t.Root[:], buf)
	}
	return nil
}

func (t *Checkpoint) SizeSSZ() (size int) {
	return 40
}

func (t *Checkpoint) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
func (t *Checkpoint) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(Checkpoint)
	}
	idx := hh.Index()
	{ // Field #0 'Epoch'
		hh.PutUint64(uint64(t.Epoch))
	}
	{ // Field #1 'Root'
		hh.PutBytes(t.Root[:32])
	}
	hh.Merkleize(idx)
	return nil
}

