// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 5986a01be9fd7a475da7f3c9a5ab16e72013bb07c8670a66ab9ff942a120e272
// Version: v1.2.0 (https://github.com/pk910/dynamic-ssz)
package phase0

import (
	"encoding/binary"

	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *ETH1Data) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *ETH1Data) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(ETH1Data)
	}
	{ // Field #0 'DepositRoot'
		dst = append(dst, t.DepositRoot[:32]...)
	}
	{ // Field #1 'DepositCount'
		dst = binary.LittleEndian.AppendUint64(dst, t.DepositCount)
	}
	{ // Field #2 'BlockHash'
		vlen := len(t.BlockHash)
		if vlen > 32 {
			return nil, sszutils.ErrVectorLength
		}
		dst = append(dst, t.BlockHash[:vlen]...)
		if vlen < 32 {
			dst = sszutils.AppendZeroPadding(dst, (32 - vlen) * 1)
		}
	}
	return dst, nil
}

func (t *ETH1Data) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 72 {
		return sszutils.ErrUnexpectedEOF
	}
	{ // Field #0 'DepositRoot' (static)
		buf := buf[0:32]
		copy(t.DepositRoot[:], buf)
	}
	{ // Field #1 'DepositCount' (static)
		buf := buf[32:40]
		t.DepositCount = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #2 'BlockHash' (static)
		buf := buf[40:72]
		t.BlockHash = sszutils.ExpandSlice(t.BlockHash, 32)
		copy(t.BlockHash[:], buf)
	}
	return nil
}

func (t *ETH1Data) SizeSSZ() (size int) {
	return 72
}

func (t *ETH1Data) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
func (t *ETH1Data) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(ETH1Data)
	}
	idx := hh.Index()
	{ // Field #0 'DepositRoot'
		hh.PutBytes(t.DepositRoot[:32])
	}
	{ // Field #1 'DepositCount'
		hh.PutUint64(t.DepositCount)
	}
	{ // Field #2 'BlockHash'
		vlen := len(t.BlockHash)
		if vlen > 32 {
			return sszutils.ErrVectorLength
		}
		val := t.BlockHash[:]
		if vlen < 32 {
			val = sszutils.AppendZeroPadding(val, (32-vlen)*1)
		}
		hh.PutBytes(val[:32])
	}
	hh.Merkleize(idx)
	return nil
}

