// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 91a137896656e955b63ed32573a031ecbf0a5ede37f83d5ca47b16da17e01c92
// Version: v1.2.0 (https://github.com/pk910/dynamic-ssz)
package phase0

import (
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *ForkData) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *ForkData) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(ForkData)
	}
	{ // Field #0 'CurrentVersion'
		dst = append(dst, t.CurrentVersion[:4]...)
	}
	{ // Field #1 'GenesisValidatorsRoot'
		dst = append(dst, t.GenesisValidatorsRoot[:32]...)
	}
	return dst, nil
}

func (t *ForkData) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 36 {
		return sszutils.ErrUnexpectedEOF
	}
	{ // Field #0 'CurrentVersion' (static)
		buf := buf[0:4]
		copy(t.CurrentVersion[:], buf)
	}
	{ // Field #1 'GenesisValidatorsRoot' (static)
		buf := buf[4:36]
		copy(t.GenesisValidatorsRoot[:], buf)
	}
	return nil
}

func (t *ForkData) SizeSSZ() (size int) {
	return 36
}

func (t *ForkData) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
func (t *ForkData) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(ForkData)
	}
	idx := hh.Index()
	{ // Field #0 'CurrentVersion'
		hh.PutBytes(t.CurrentVersion[:4])
	}
	{ // Field #1 'GenesisValidatorsRoot'
		hh.PutBytes(t.GenesisValidatorsRoot[:32])
	}
	hh.Merkleize(idx)
	return nil
}

