// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: c41265af228ecb5aab443e67ea3129ecd00a29aa255de52f37afef01eeed1e2d
// Version: v1.2.0 (https://github.com/pk910/dynamic-ssz)
package phase0

import (
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *SignedBeaconBlockHeader) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *SignedBeaconBlockHeader) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(SignedBeaconBlockHeader)
	}
	{ // Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(BeaconBlockHeader)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, err
		}
	}
	{ // Field #1 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	return dst, nil
}

func (t *SignedBeaconBlockHeader) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 208 {
		return sszutils.ErrUnexpectedEOF
	}
	{ // Field #0 'Message' (static)
		buf := buf[0:112]
		if t.Message == nil {
			t.Message = new(BeaconBlockHeader)
		}
		if err = t.Message.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	{ // Field #1 'Signature' (static)
		buf := buf[112:208]
		copy(t.Signature[:], buf)
	}
	return nil
}

func (t *SignedBeaconBlockHeader) SizeSSZ() (size int) {
	return 208
}

func (t *SignedBeaconBlockHeader) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
func (t *SignedBeaconBlockHeader) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SignedBeaconBlockHeader)
	}
	idx := hh.Index()
	{ // Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(BeaconBlockHeader)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	{ // Field #1 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}

