// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 5c5b80e0f363806ec7b6d12b1ac5ffb3238eb78b1d7855bc2db3de4a6189565f
// Version: v1.2.2 (https://github.com/pk910/dynamic-ssz)
package fulu

import (
	"encoding/binary"

	"github.com/attestantio/go-eth2-client/spec/electra"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *BlockContents) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *BlockContents) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(BlockContents)
	}
	dstlen := len(dst)
	// Offset #0 'Block'
	offset0 := len(dst)
	dst = append(dst, 0, 0, 0, 0)
	// Offset #1 'KZGProofs'
	offset1 := len(dst)
	dst = append(dst, 0, 0, 0, 0)
	// Offset #2 'Blobs'
	offset2 := len(dst)
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #0 'Block'
		binary.LittleEndian.PutUint32(dst[offset0:], uint32(len(dst)-dstlen))
		t := t.Block
		if t == nil {
			t = new(electra.BeaconBlock)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, err
		}
	}
	{ // Dynamic Field #1 'KZGProofs'
		binary.LittleEndian.PutUint32(dst[offset1:], uint32(len(dst)-dstlen))
		t := t.KZGProofs
		vlen := len(t)
		if vlen > 33554432 {
			return nil, sszutils.ErrListTooBig
		}
		for i := range vlen {
			dst = append(dst, t[i][:48]...)
		}
	}
	{ // Dynamic Field #2 'Blobs'
		binary.LittleEndian.PutUint32(dst[offset2:], uint32(len(dst)-dstlen))
		t := t.Blobs
		vlen := len(t)
		if vlen > 4096 {
			return nil, sszutils.ErrListTooBig
		}
		for i := range vlen {
			dst = append(dst, t[i][:131072]...)
		}
	}
	return dst, nil
}

func (t *BlockContents) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 12 {
		return sszutils.ErrUnexpectedEOF
	}
	// Field #0 'Block' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 12 {
		return sszutils.ErrOffset
	}
	// Field #1 'KZGProofs' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[4:8]))
	if offset1 < offset0 || offset1 > buflen {
		return sszutils.ErrOffset
	}
	// Field #2 'Blobs' (offset)
	offset2 := int(binary.LittleEndian.Uint32(buf[8:12]))
	if offset2 < offset1 || offset2 > buflen {
		return sszutils.ErrOffset
	}
	{ // Field #0 'Block' (dynamic)
		buf := buf[offset0:offset1]
		if t.Block == nil {
			t.Block = new(electra.BeaconBlock)
		}
		if err = t.Block.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	{ // Field #1 'KZGProofs' (dynamic)
		buf := buf[offset1:offset2]
		val1 := t.KZGProofs
		itemCount := len(buf) / 48
		if len(buf)%48 != 0 {
			return sszutils.ErrUnexpectedEOF
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for i := range itemCount {
			buf := buf[48*i : 48*(i+1)]
			copy(val1[i][:], buf)
		}
		t.KZGProofs = val1
	}
	{ // Field #2 'Blobs' (dynamic)
		buf := buf[offset2:]
		val2 := t.Blobs
		itemCount := len(buf) / 131072
		if len(buf)%131072 != 0 {
			return sszutils.ErrUnexpectedEOF
		}
		val2 = sszutils.ExpandSlice(val2, itemCount)
		for i := range itemCount {
			buf := buf[131072*i : 131072*(i+1)]
			copy(val2[i][:], buf)
		}
		t.Blobs = val2
	}
	return nil
}

func (t *BlockContents) SizeSSZ() (size int) {
	if t == nil {
		t = new(BlockContents)
	}
	// Field #0 'Block' offset (4 bytes)
	// Field #1 'KZGProofs' offset (4 bytes)
	// Field #2 'Blobs' offset (4 bytes)
	size += 12
	{ // Dynamic field #0 'Block'
		size += t.Block.SizeSSZ()
	}
	{ // Dynamic field #1 'KZGProofs'
		size += len(t.KZGProofs) * 48
	}
	{ // Dynamic field #2 'Blobs'
		size += len(t.Blobs) * 131072
	}
	return size
}

func (t *BlockContents) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
func (t *BlockContents) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BlockContents)
	}
	idx := hh.Index()
	{ // Field #0 'Block'
		t := t.Block
		if t == nil {
			t = new(electra.BeaconBlock)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	{ // Field #1 'KZGProofs'
		t := t.KZGProofs
		vlen := uint64(len(t))
		if vlen > 33554432 {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := range int(vlen) {
			hh.PutBytes(t[i][:48])
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(33554432, vlen, 32))
	}
	{ // Field #2 'Blobs'
		t := t.Blobs
		vlen := uint64(len(t))
		if vlen > 4096 {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := range int(vlen) {
			hh.PutBytes(t[i][:131072])
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(4096, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}
