// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: be8b20dd858008877593528b9dc181af32d24dbaa8b2afac2cca443e33381669
// Version: v1.2.0 (https://github.com/pk910/dynamic-ssz)
package bellatrix

import (
	"encoding/binary"

	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *ExecutionPayloadTransactions) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *ExecutionPayloadTransactions) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(ExecutionPayloadTransactions)
	}
	dstlen := len(dst)
	// Offset #0 'Transactions'
	offset0 := len(dst)
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #0 'Transactions'
		binary.LittleEndian.PutUint32(dst[offset0:], uint32(len(dst)-dstlen))
		t := t.Transactions
		vlen := len(t)
		if vlen > 1048576 {
			return nil, sszutils.ErrListTooBig
		}
		dstlen := len(dst)
		dst = sszutils.AppendZeroPadding(dst, vlen*4)
		for i := range vlen {
			binary.LittleEndian.PutUint32(dst[dstlen+(i*4):], uint32(len(dst)-dstlen))
			vlen := len(t[i])
			if vlen > 1073741824 {
				return nil, sszutils.ErrListTooBig
			}
			dst = append(dst, t[i][:]...)
		}
	}
	return dst, nil
}

func (t *ExecutionPayloadTransactions) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 4 {
		return sszutils.ErrUnexpectedEOF
	}
	// Field #0 'Transactions' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 4 {
		return sszutils.ErrOffset
	}
	{ // Field #0 'Transactions' (dynamic)
		buf := buf[offset0:]
		val1 := t.Transactions
		startOffset := int(0)
		if len(buf) != 0 {
			if len(buf) < 4 {
				return sszutils.ErrUnexpectedEOF
			}
			startOffset = int(binary.LittleEndian.Uint32(buf[0:4]))
		}
		itemCount := startOffset / 4
		if startOffset%4 != 0 || len(buf) < startOffset {
			return sszutils.ErrUnexpectedEOF
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for i := range itemCount {
			var endOffset int
			if i < itemCount-1 {
				endOffset = int(binary.LittleEndian.Uint32(buf[(i+1)*4 : (i+2)*4]))
			} else {
				endOffset = len(buf)
			}
			if endOffset < startOffset || endOffset > len(buf) {
				return sszutils.ErrOffset
			}
			buf := buf[startOffset:endOffset]
			startOffset = endOffset
			val2 := val1[i]
			val2 = sszutils.ExpandSlice(val2, len(buf))
			copy(val2[:], buf)
			val1[i] = val2
		}
		t.Transactions = val1
	}
	return nil
}

func (t *ExecutionPayloadTransactions) SizeSSZ() (size int) {
	if t == nil {
		t = new(ExecutionPayloadTransactions)
	}
	// Field #0 'Transactions' offset (4 bytes)
	size += 4
	{ // Dynamic field #0 'Transactions'
		t := t.Transactions
		vlen := len(t)
		size += vlen * 4 // Offsets
		for i1 := range vlen {
			size += len(t[i1])
		}
	}
	return size
}

func (t *ExecutionPayloadTransactions) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
func (t *ExecutionPayloadTransactions) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(ExecutionPayloadTransactions)
	}
	idx := hh.Index()
	{ // Field #0 'Transactions'
		t := t.Transactions
		vlen := uint64(len(t))
		if vlen > 1048576 {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := range int(vlen) {
			vlen := uint64(len(t[i]))
			if vlen > 1073741824 {
				return sszutils.ErrListTooBig
			}
			idx := hh.Index()
			hh.AppendBytes32(t[i][:])
			hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(1073741824, vlen, 1))
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(1048576, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}

