// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 24d923cca94c40bdd13cf5a6c99d162f7c0fcdf9f3541d566cbde00333091808
// Version: v1.2.1 (https://github.com/pk910/dynamic-ssz)
package electra

import (
	"encoding/binary"

	"github.com/attestantio/go-eth2-client/spec/electra"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *WithdrawalRequests) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *WithdrawalRequests) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(WithdrawalRequests)
	}
	dstlen := len(dst)
	// Offset #0 'WithdrawalRequests'
	offset0 := len(dst)
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #0 'WithdrawalRequests'
		binary.LittleEndian.PutUint32(dst[offset0:], uint32(len(dst)-dstlen))
		t := t.WithdrawalRequests
		vlen := len(t)
		if vlen > 16 {
			return nil, sszutils.ErrListTooBig
		}
		for i := range vlen {
			t := t[i]
			if t == nil {
				t = new(electra.WithdrawalRequest)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, err
			}
		}
	}
	return dst, nil
}

func (t *WithdrawalRequests) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 4 {
		return sszutils.ErrUnexpectedEOF
	}
	// Field #0 'WithdrawalRequests' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 4 {
		return sszutils.ErrOffset
	}
	{ // Field #0 'WithdrawalRequests' (dynamic)
		buf := buf[offset0:]
		val1 := t.WithdrawalRequests
		itemCount := len(buf) / 76
		if len(buf)%76 != 0 {
			return sszutils.ErrUnexpectedEOF
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for i := range itemCount {
			if val1[i] == nil {
				val1[i] = new(electra.WithdrawalRequest)
			}
			buf := buf[76*i : 76*(i+1)]
			if err = val1[i].UnmarshalSSZ(buf); err != nil {
				return err
			}
		}
		t.WithdrawalRequests = val1
	}
	return nil
}

func (t *WithdrawalRequests) SizeSSZ() (size int) {
	if t == nil {
		t = new(WithdrawalRequests)
	}
	// Field #0 'WithdrawalRequests' offset (4 bytes)
	size += 4
	{ // Dynamic field #0 'WithdrawalRequests'
		size += len(t.WithdrawalRequests) * 76
	}
	return size
}

func (t *WithdrawalRequests) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
func (t *WithdrawalRequests) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(WithdrawalRequests)
	}
	idx := hh.Index()
	{ // Field #0 'WithdrawalRequests'
		t := t.WithdrawalRequests
		vlen := uint64(len(t))
		if vlen > 16 {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := range int(vlen) {
			t := t[i]
			if t == nil {
				t = new(electra.WithdrawalRequest)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return err
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(16, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}

