// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 8022004ed753dd134bd1bb39d7ffc5df3ec33ae054ee6e6152ae210d341d746a
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package all

import (
	"encoding/binary"

	"github.com/ethpandaops/go-eth2-client/spec/electra"
	"github.com/ethpandaops/go-eth2-client/spec/phase0"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *AggregateAndProof) MarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) ([]byte, error) {
	switch view.(type) {
	case *phase0.AggregateAndProof:
		return t.marshalSSZView_AggregateAndProof
	case *electra.AggregateAndProof:
		return t.marshalSSZView_AggregateAndProof_0
	}
	return nil
}
func (t *AggregateAndProof) marshalSSZView_AggregateAndProof(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(AggregateAndProof)
	}
	dstlen := len(dst)
	{ // Static Field #0 'AggregatorIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.AggregatorIndex))
	}
	// Offset Field #1 'Aggregate'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #2 'SelectionProof'
		dst = append(dst, t.SelectionProof[:96]...)
	}
	{ // Dynamic Field #1 'Aggregate'
		binary.LittleEndian.PutUint32(dst[dstlen+8:], uint32(len(dst)-dstlen))
		t := t.Aggregate
		if t == nil {
			t = new(Attestation)
		}
		if viewFn := t.MarshalSSZDynView((*phase0.Attestation)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *AggregateAndProof) marshalSSZView_AggregateAndProof_0(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(AggregateAndProof)
	}
	dstlen := len(dst)
	{ // Static Field #0 'AggregatorIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.AggregatorIndex))
	}
	// Offset Field #1 'Aggregate'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #2 'SelectionProof'
		dst = append(dst, t.SelectionProof[:96]...)
	}
	{ // Dynamic Field #1 'Aggregate'
		binary.LittleEndian.PutUint32(dst[dstlen+8:], uint32(len(dst)-dstlen))
		t := t.Aggregate
		if t == nil {
			t = new(Attestation)
		}
		if viewFn := t.MarshalSSZDynView((*electra.Attestation)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *AggregateAndProof) UnmarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) error {
	switch view.(type) {
	case *phase0.AggregateAndProof:
		return t.unmarshalSSZView_AggregateAndProof
	case *electra.AggregateAndProof:
		return t.unmarshalSSZView_AggregateAndProof_0
	}
	return nil
}
func (t *AggregateAndProof) unmarshalSSZView_AggregateAndProof(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 108 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 108)
	}
	{ // Field #0 'AggregatorIndex' (static)
		buf := buf[0:8]
		t.AggregatorIndex = phase0.ValidatorIndex(binary.LittleEndian.Uint64(buf))
	}
	// Field #1 'Aggregate' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[8:12]))
	if offset1 != 108 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset1, 108), "Aggregate:o")
	}
	{ // Field #2 'SelectionProof' (static)
		buf := buf[12:108]
		copy(t.SelectionProof[:], buf)
	}
	{ // Field #1 'Aggregate' (dynamic)
		buf := buf[offset1:]
		if t.Aggregate == nil {
			t.Aggregate = new(Attestation)
		}
		if viewFn := t.Aggregate.UnmarshalSSZDynView((*phase0.Attestation)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *AggregateAndProof) unmarshalSSZView_AggregateAndProof_0(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 108 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 108)
	}
	{ // Field #0 'AggregatorIndex' (static)
		buf := buf[0:8]
		t.AggregatorIndex = phase0.ValidatorIndex(binary.LittleEndian.Uint64(buf))
	}
	// Field #1 'Aggregate' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[8:12]))
	if offset1 != 108 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset1, 108), "Aggregate:o")
	}
	{ // Field #2 'SelectionProof' (static)
		buf := buf[12:108]
		copy(t.SelectionProof[:], buf)
	}
	{ // Field #1 'Aggregate' (dynamic)
		buf := buf[offset1:]
		if t.Aggregate == nil {
			t.Aggregate = new(Attestation)
		}
		if viewFn := t.Aggregate.UnmarshalSSZDynView((*electra.Attestation)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *AggregateAndProof) SizeSSZDynView(view any) func(ds sszutils.DynamicSpecs) int {
	switch view.(type) {
	case *phase0.AggregateAndProof:
		return t.sizeSSZView_AggregateAndProof
	case *electra.AggregateAndProof:
		return t.sizeSSZView_AggregateAndProof_0
	}
	return nil
}
func (t *AggregateAndProof) sizeSSZView_AggregateAndProof(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(AggregateAndProof)
	}
	// Field #0 'AggregatorIndex' static (8 bytes)
	// Field #1 'Aggregate' offset (4 bytes)
	// Field #2 'SelectionProof' static (96 bytes)
	size += 108
	{ // Dynamic field #1 'Aggregate'
		if viewFn := t.Aggregate.SizeSSZDynView((*phase0.Attestation)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *AggregateAndProof) sizeSSZView_AggregateAndProof_0(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(AggregateAndProof)
	}
	// Field #0 'AggregatorIndex' static (8 bytes)
	// Field #1 'Aggregate' offset (4 bytes)
	// Field #2 'SelectionProof' static (96 bytes)
	size += 108
	{ // Dynamic field #1 'Aggregate'
		if viewFn := t.Aggregate.SizeSSZDynView((*electra.Attestation)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *AggregateAndProof) HashTreeRootWithDynView(view any) func(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	switch view.(type) {
	case *phase0.AggregateAndProof:
		return t.hashTreeRootView_AggregateAndProof
	case *electra.AggregateAndProof:
		return t.hashTreeRootView_AggregateAndProof_0
	}
	return nil
}
func (t *AggregateAndProof) hashTreeRootView_AggregateAndProof(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(AggregateAndProof)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'AggregatorIndex'
		hh.PutUint64(uint64(t.AggregatorIndex))
	}
	{ // Field #1 'Aggregate'
		t := t.Aggregate
		if t == nil {
			t = new(Attestation)
		}
		if viewFn := t.HashTreeRootWithDynView((*phase0.Attestation)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #2 'SelectionProof'
		hh.PutBytes(t.SelectionProof[:96])
	}
	hh.Merkleize(idx)
	return nil
}

func (t *AggregateAndProof) hashTreeRootView_AggregateAndProof_0(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(AggregateAndProof)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'AggregatorIndex'
		hh.PutUint64(uint64(t.AggregatorIndex))
	}
	{ // Field #1 'Aggregate'
		t := t.Aggregate
		if t == nil {
			t = new(Attestation)
		}
		if viewFn := t.HashTreeRootWithDynView((*electra.Attestation)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #2 'SelectionProof'
		hh.PutBytes(t.SelectionProof[:96])
	}
	hh.Merkleize(idx)
	return nil
}
