// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 5c381d8290e8e25d1341358ffd3f391b1a1de062f551f8cccf224ea51100d6c9
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package all

import (
	"encoding/binary"
	"math/bits"

	"github.com/ethpandaops/go-eth2-client/spec/electra"
	"github.com/ethpandaops/go-eth2-client/spec/phase0"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *Attestation) MarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) ([]byte, error) {
	switch view.(type) {
	case *phase0.Attestation:
		return t.marshalSSZView_Attestation
	case *electra.Attestation:
		return t.marshalSSZView_Attestation_0
	}
	return nil
}
func (t *Attestation) marshalSSZView_Attestation(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_VALIDATORS_PER_COMMITTEE", 2048)
	if err != nil {
		return dst, err
	}
	if t == nil {
		t = new(Attestation)
	}
	dstlen := len(dst)
	// Offset Field #0 'AggregationBits'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'Data'
		t := t.Data
		if t == nil {
			t = new(phase0.AttestationData)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "Data")
		}
	}
	{ // Static Field #2 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	{ // Dynamic Field #0 'AggregationBits'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.AggregationBits
		vlen := len(t)
		bval := []byte(t[:])
		if vlen == 0 {
			bval = []byte{0x01}
		} else if bval[vlen-1] == 0x00 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrBitlistNotTerminatedFn(), "AggregationBits")
		}
		if vlen > 0 {
			bitCount := 8*(vlen-1) + bits.Len8(bval[vlen-1]) - 1
			if bitCount > int(expr0) {
				return nil, sszutils.ErrorWithPath(sszutils.ErrBitlistLengthFn(bitCount, int(expr0)), "AggregationBits")
			}
		}
		dst = append(dst, bval...)
	}
	return dst, nil
}

func (t *Attestation) marshalSSZView_Attestation_0(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_COMMITTEES_PER_SLOT/8", 8)
	if err != nil {
		return dst, err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_VALIDATORS_PER_COMMITTEE*MAX_COMMITTEES_PER_SLOT", 131072)
	if err != nil {
		return dst, err
	}
	if t == nil {
		t = new(Attestation)
	}
	dstlen := len(dst)
	// Offset Field #0 'AggregationBits'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'Data'
		t := t.Data
		if t == nil {
			t = new(phase0.AttestationData)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "Data")
		}
	}
	{ // Static Field #2 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	{ // Static Field #3 'CommitteeBits'
		vlen := len(t.CommitteeBits)
		if vlen > int(expr0) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, int(expr0)), "CommitteeBits")
		}
		dst = append(dst, t.CommitteeBits[:vlen]...)
		if vlen < int(expr0) {
			dst = sszutils.AppendZeroPadding(dst, (int(expr0)-vlen)*1)
		}
	}
	{ // Dynamic Field #0 'AggregationBits'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.AggregationBits
		vlen := len(t)
		bval := []byte(t[:])
		if vlen == 0 {
			bval = []byte{0x01}
		} else if bval[vlen-1] == 0x00 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrBitlistNotTerminatedFn(), "AggregationBits")
		}
		if vlen > 0 {
			bitCount := 8*(vlen-1) + bits.Len8(bval[vlen-1]) - 1
			if bitCount > int(expr1) {
				return nil, sszutils.ErrorWithPath(sszutils.ErrBitlistLengthFn(bitCount, int(expr1)), "AggregationBits")
			}
		}
		dst = append(dst, bval...)
	}
	return dst, nil
}

func (t *Attestation) UnmarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) error {
	switch view.(type) {
	case *phase0.Attestation:
		return t.unmarshalSSZView_Attestation
	case *electra.Attestation:
		return t.unmarshalSSZView_Attestation_0
	}
	return nil
}
func (t *Attestation) unmarshalSSZView_Attestation(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_VALIDATORS_PER_COMMITTEE", 2048)
	if err != nil {
		return err
	}
	buflen := len(buf)
	if buflen < 228 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 228)
	}
	// Field #0 'AggregationBits' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 228 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 228), "AggregationBits:o")
	}
	{ // Field #1 'Data' (static)
		buf := buf[4:132]
		if t.Data == nil {
			t.Data = new(phase0.AttestationData)
		}
		if err = t.Data.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "Data")
		}
	}
	{ // Field #2 'Signature' (static)
		buf := buf[132:228]
		copy(t.Signature[:], buf)
	}
	{ // Field #0 'AggregationBits' (dynamic)
		buf := buf[offset0:]
		val1 := t.AggregationBits
		blen := len(buf)
		if blen == 0 || buf[blen-1] == 0x00 {
			return sszutils.ErrorWithPath(sszutils.ErrBitlistNotTerminatedFn(), "AggregationBits")
		}
		bitCount := 8*(blen-1) + int(bits.Len8(buf[blen-1])) - 1
		if bitCount > int(expr0) {
			return sszutils.ErrorWithPath(sszutils.ErrBitlistLengthFn(bitCount, int(expr0)), "AggregationBits")
		}
		val1 = sszutils.ExpandSlice(val1, blen)
		copy(val1[:], buf)
		t.AggregationBits = val1
	}
	return nil
}

func (t *Attestation) unmarshalSSZView_Attestation_0(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_COMMITTEES_PER_SLOT/8", 8)
	if err != nil {
		return err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_VALIDATORS_PER_COMMITTEE*MAX_COMMITTEES_PER_SLOT", 131072)
	if err != nil {
		return err
	}
	size1 := 1 * int(expr0)
	exproffset := 0
	totalSize := size1+228
	buflen := len(buf)
	if buflen < totalSize {
		return sszutils.ErrFixedFieldsEOFFn(buflen, totalSize)
	}
	// Field #0 'AggregationBits' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != totalSize {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, totalSize), "AggregationBits:o")
	}
	{ // Field #1 'Data' (static)
		buf := buf[4:132]
		if t.Data == nil {
			t.Data = new(phase0.AttestationData)
		}
		if err = t.Data.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "Data")
		}
	}
	{ // Field #2 'Signature' (static)
		buf := buf[132:228]
		copy(t.Signature[:], buf)
	}
	{ // Field #3 'CommitteeBits' (static)
		buf := buf[228 : size1+228]
		exproffset += int(size1)
		t.CommitteeBits = sszutils.ExpandSlice(t.CommitteeBits, int(expr0))
		copy(t.CommitteeBits[:], buf)
	}
	{ // Field #0 'AggregationBits' (dynamic)
		buf := buf[offset0:]
		val1 := t.AggregationBits
		blen := len(buf)
		if blen == 0 || buf[blen-1] == 0x00 {
			return sszutils.ErrorWithPath(sszutils.ErrBitlistNotTerminatedFn(), "AggregationBits")
		}
		bitCount := 8*(blen-1) + int(bits.Len8(buf[blen-1])) - 1
		if bitCount > int(expr1) {
			return sszutils.ErrorWithPath(sszutils.ErrBitlistLengthFn(bitCount, int(expr1)), "AggregationBits")
		}
		val1 = sszutils.ExpandSlice(val1, blen)
		copy(val1[:], buf)
		t.AggregationBits = val1
	}
	return nil
}

func (t *Attestation) SizeSSZDynView(view any) func(ds sszutils.DynamicSpecs) int {
	switch view.(type) {
	case *phase0.Attestation:
		return t.sizeSSZView_Attestation
	case *electra.Attestation:
		return t.sizeSSZView_Attestation_0
	}
	return nil
}
func (t *Attestation) sizeSSZView_Attestation(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(Attestation)
	}
	// Field #0 'AggregationBits' offset (4 bytes)
	// Field #1 'Data' static (128 bytes)
	// Field #2 'Signature' static (96 bytes)
	size += 228
	{ // Dynamic field #0 'AggregationBits'
		if len(t.AggregationBits) == 0 {
			size += 1
		} else {
			size += len(t.AggregationBits)
		}
	}
	return size
}

func (t *Attestation) sizeSSZView_Attestation_0(ds sszutils.DynamicSpecs) (size int) {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_COMMITTEES_PER_SLOT/8", 8)
	if err != nil {
		return 0
	}
	if t == nil {
		t = new(Attestation)
	}
	// Field #0 'AggregationBits' offset (4 bytes)
	// Field #1 'Data' static (128 bytes)
	// Field #2 'Signature' static (96 bytes)
	size += 228
	{ // Field #3 'CommitteeBits'
		size += int(expr0)
	}
	{ // Dynamic field #0 'AggregationBits'
		if len(t.AggregationBits) == 0 {
			size += 1
		} else {
			size += len(t.AggregationBits)
		}
	}
	return size
}

func (t *Attestation) HashTreeRootWithDynView(view any) func(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	switch view.(type) {
	case *phase0.Attestation:
		return t.hashTreeRootView_Attestation
	case *electra.Attestation:
		return t.hashTreeRootView_Attestation_0
	}
	return nil
}
func (t *Attestation) hashTreeRootView_Attestation(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_VALIDATORS_PER_COMMITTEE", 2048)
	if err != nil {
		return err
	}
	if t == nil {
		t = new(Attestation)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'AggregationBits'
		t := t.AggregationBits
		idx := hh.StartTree(sszutils.TreeTypeNone)
		bitlist, size := hasher.ParseBitlistWithHasher(hh, t[:])
		if size > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrBitlistLengthFn(size, expr0), "AggregationBits")
		}
		hh.AppendBytes32(bitlist)
		hh.MerkleizeWithMixin(idx, size, (expr0+255)/256)
	}
	{ // Field #1 'Data'
		t := t.Data
		if t == nil {
			t = new(phase0.AttestationData)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "Data")
		}
	}
	{ // Field #2 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}

func (t *Attestation) hashTreeRootView_Attestation_0(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_VALIDATORS_PER_COMMITTEE*MAX_COMMITTEES_PER_SLOT", 131072)
	if err != nil {
		return err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_COMMITTEES_PER_SLOT/8", 8)
	if err != nil {
		return err
	}
	if t == nil {
		t = new(Attestation)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'AggregationBits'
		t := t.AggregationBits
		idx := hh.StartTree(sszutils.TreeTypeNone)
		bitlist, size := hasher.ParseBitlistWithHasher(hh, t[:])
		if size > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrBitlistLengthFn(size, expr0), "AggregationBits")
		}
		hh.AppendBytes32(bitlist)
		hh.MerkleizeWithMixin(idx, size, (expr0+255)/256)
	}
	{ // Field #1 'Data'
		t := t.Data
		if t == nil {
			t = new(phase0.AttestationData)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "Data")
		}
	}
	{ // Field #2 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	{ // Field #3 'CommitteeBits'
		vlen := len(t.CommitteeBits)
		if vlen > int(expr1) {
			return sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, int(expr1)), "CommitteeBits")
		}
		val := t.CommitteeBits[:]
		if vlen < int(expr1) {
			val = sszutils.AppendZeroPadding(val, (int(expr1)-vlen)*1)
		}
		hh.PutBytes(val[:int(expr1)])
	}
	hh.Merkleize(idx)
	return nil
}
