// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: ccc8da02983f6aeafd7ec1b4efdf9c138c97e8686085cd8f93935c9d8b0b4c1e
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package all

import (
	"encoding/binary"

	"github.com/ethpandaops/go-eth2-client/spec/altair"
	"github.com/ethpandaops/go-eth2-client/spec/bellatrix"
	"github.com/ethpandaops/go-eth2-client/spec/capella"
	"github.com/ethpandaops/go-eth2-client/spec/deneb"
	"github.com/ethpandaops/go-eth2-client/spec/electra"
	"github.com/ethpandaops/go-eth2-client/spec/gloas"
	"github.com/ethpandaops/go-eth2-client/spec/heze"
	"github.com/ethpandaops/go-eth2-client/spec/phase0"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *BeaconBlock) MarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) ([]byte, error) {
	switch view.(type) {
	case *phase0.BeaconBlock:
		return t.marshalSSZView_BeaconBlock
	case *altair.BeaconBlock:
		return t.marshalSSZView_BeaconBlock_0
	case *bellatrix.BeaconBlock:
		return t.marshalSSZView_BeaconBlock_1
	case *capella.BeaconBlock:
		return t.marshalSSZView_BeaconBlock_2
	case *deneb.BeaconBlock:
		return t.marshalSSZView_BeaconBlock_3
	case *electra.BeaconBlock:
		return t.marshalSSZView_BeaconBlock_4
	case *gloas.BeaconBlock:
		return t.marshalSSZView_BeaconBlock_5
	case *heze.BeaconBlock:
		return t.marshalSSZView_BeaconBlock_6
	}
	return nil
}
func (t *BeaconBlock) marshalSSZView_BeaconBlock(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(BeaconBlock)
	}
	dstlen := len(dst)
	{ // Static Field #0 'Slot'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.Slot))
	}
	{ // Static Field #1 'ProposerIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.ProposerIndex))
	}
	{ // Static Field #2 'ParentRoot'
		dst = append(dst, t.ParentRoot[:32]...)
	}
	{ // Static Field #3 'StateRoot'
		dst = append(dst, t.StateRoot[:32]...)
	}
	// Offset Field #4 'Body'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #4 'Body'
		binary.LittleEndian.PutUint32(dst[dstlen+80:], uint32(len(dst)-dstlen))
		t := t.Body
		if t == nil {
			t = new(BeaconBlockBody)
		}
		if viewFn := t.MarshalSSZDynView((*phase0.BeaconBlockBody)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *BeaconBlock) marshalSSZView_BeaconBlock_0(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(BeaconBlock)
	}
	dstlen := len(dst)
	{ // Static Field #0 'Slot'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.Slot))
	}
	{ // Static Field #1 'ProposerIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.ProposerIndex))
	}
	{ // Static Field #2 'ParentRoot'
		dst = append(dst, t.ParentRoot[:32]...)
	}
	{ // Static Field #3 'StateRoot'
		dst = append(dst, t.StateRoot[:32]...)
	}
	// Offset Field #4 'Body'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #4 'Body'
		binary.LittleEndian.PutUint32(dst[dstlen+80:], uint32(len(dst)-dstlen))
		t := t.Body
		if t == nil {
			t = new(BeaconBlockBody)
		}
		if viewFn := t.MarshalSSZDynView((*altair.BeaconBlockBody)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *BeaconBlock) marshalSSZView_BeaconBlock_1(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(BeaconBlock)
	}
	dstlen := len(dst)
	{ // Static Field #0 'Slot'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.Slot))
	}
	{ // Static Field #1 'ProposerIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.ProposerIndex))
	}
	{ // Static Field #2 'ParentRoot'
		dst = append(dst, t.ParentRoot[:32]...)
	}
	{ // Static Field #3 'StateRoot'
		dst = append(dst, t.StateRoot[:32]...)
	}
	// Offset Field #4 'Body'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #4 'Body'
		binary.LittleEndian.PutUint32(dst[dstlen+80:], uint32(len(dst)-dstlen))
		t := t.Body
		if t == nil {
			t = new(BeaconBlockBody)
		}
		if viewFn := t.MarshalSSZDynView((*bellatrix.BeaconBlockBody)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *BeaconBlock) marshalSSZView_BeaconBlock_2(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(BeaconBlock)
	}
	dstlen := len(dst)
	{ // Static Field #0 'Slot'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.Slot))
	}
	{ // Static Field #1 'ProposerIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.ProposerIndex))
	}
	{ // Static Field #2 'ParentRoot'
		dst = append(dst, t.ParentRoot[:32]...)
	}
	{ // Static Field #3 'StateRoot'
		dst = append(dst, t.StateRoot[:32]...)
	}
	// Offset Field #4 'Body'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #4 'Body'
		binary.LittleEndian.PutUint32(dst[dstlen+80:], uint32(len(dst)-dstlen))
		t := t.Body
		if t == nil {
			t = new(BeaconBlockBody)
		}
		if viewFn := t.MarshalSSZDynView((*capella.BeaconBlockBody)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *BeaconBlock) marshalSSZView_BeaconBlock_3(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(BeaconBlock)
	}
	dstlen := len(dst)
	{ // Static Field #0 'Slot'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.Slot))
	}
	{ // Static Field #1 'ProposerIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.ProposerIndex))
	}
	{ // Static Field #2 'ParentRoot'
		dst = append(dst, t.ParentRoot[:32]...)
	}
	{ // Static Field #3 'StateRoot'
		dst = append(dst, t.StateRoot[:32]...)
	}
	// Offset Field #4 'Body'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #4 'Body'
		binary.LittleEndian.PutUint32(dst[dstlen+80:], uint32(len(dst)-dstlen))
		t := t.Body
		if t == nil {
			t = new(BeaconBlockBody)
		}
		if viewFn := t.MarshalSSZDynView((*deneb.BeaconBlockBody)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *BeaconBlock) marshalSSZView_BeaconBlock_4(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(BeaconBlock)
	}
	dstlen := len(dst)
	{ // Static Field #0 'Slot'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.Slot))
	}
	{ // Static Field #1 'ProposerIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.ProposerIndex))
	}
	{ // Static Field #2 'ParentRoot'
		dst = append(dst, t.ParentRoot[:32]...)
	}
	{ // Static Field #3 'StateRoot'
		dst = append(dst, t.StateRoot[:32]...)
	}
	// Offset Field #4 'Body'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #4 'Body'
		binary.LittleEndian.PutUint32(dst[dstlen+80:], uint32(len(dst)-dstlen))
		t := t.Body
		if t == nil {
			t = new(BeaconBlockBody)
		}
		if viewFn := t.MarshalSSZDynView((*electra.BeaconBlockBody)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *BeaconBlock) marshalSSZView_BeaconBlock_5(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(BeaconBlock)
	}
	dstlen := len(dst)
	{ // Static Field #0 'Slot'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.Slot))
	}
	{ // Static Field #1 'ProposerIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.ProposerIndex))
	}
	{ // Static Field #2 'ParentRoot'
		dst = append(dst, t.ParentRoot[:32]...)
	}
	{ // Static Field #3 'StateRoot'
		dst = append(dst, t.StateRoot[:32]...)
	}
	// Offset Field #4 'Body'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #4 'Body'
		binary.LittleEndian.PutUint32(dst[dstlen+80:], uint32(len(dst)-dstlen))
		t := t.Body
		if t == nil {
			t = new(BeaconBlockBody)
		}
		if viewFn := t.MarshalSSZDynView((*gloas.BeaconBlockBody)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *BeaconBlock) marshalSSZView_BeaconBlock_6(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(BeaconBlock)
	}
	dstlen := len(dst)
	{ // Static Field #0 'Slot'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.Slot))
	}
	{ // Static Field #1 'ProposerIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.ProposerIndex))
	}
	{ // Static Field #2 'ParentRoot'
		dst = append(dst, t.ParentRoot[:32]...)
	}
	{ // Static Field #3 'StateRoot'
		dst = append(dst, t.StateRoot[:32]...)
	}
	// Offset Field #4 'Body'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #4 'Body'
		binary.LittleEndian.PutUint32(dst[dstlen+80:], uint32(len(dst)-dstlen))
		t := t.Body
		if t == nil {
			t = new(BeaconBlockBody)
		}
		if viewFn := t.MarshalSSZDynView((*heze.BeaconBlockBody)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *BeaconBlock) UnmarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) error {
	switch view.(type) {
	case *phase0.BeaconBlock:
		return t.unmarshalSSZView_BeaconBlock
	case *altair.BeaconBlock:
		return t.unmarshalSSZView_BeaconBlock_0
	case *bellatrix.BeaconBlock:
		return t.unmarshalSSZView_BeaconBlock_1
	case *capella.BeaconBlock:
		return t.unmarshalSSZView_BeaconBlock_2
	case *deneb.BeaconBlock:
		return t.unmarshalSSZView_BeaconBlock_3
	case *electra.BeaconBlock:
		return t.unmarshalSSZView_BeaconBlock_4
	case *gloas.BeaconBlock:
		return t.unmarshalSSZView_BeaconBlock_5
	case *heze.BeaconBlock:
		return t.unmarshalSSZView_BeaconBlock_6
	}
	return nil
}
func (t *BeaconBlock) unmarshalSSZView_BeaconBlock(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 84 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 84)
	}
	{ // Field #0 'Slot' (static)
		buf := buf[0:8]
		t.Slot = phase0.Slot(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #1 'ProposerIndex' (static)
		buf := buf[8:16]
		t.ProposerIndex = phase0.ValidatorIndex(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #2 'ParentRoot' (static)
		buf := buf[16:48]
		copy(t.ParentRoot[:], buf)
	}
	{ // Field #3 'StateRoot' (static)
		buf := buf[48:80]
		copy(t.StateRoot[:], buf)
	}
	// Field #4 'Body' (offset)
	offset4 := int(binary.LittleEndian.Uint32(buf[80:84]))
	if offset4 != 84 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset4, 84), "Body:o")
	}
	{ // Field #4 'Body' (dynamic)
		buf := buf[offset4:]
		if t.Body == nil {
			t.Body = new(BeaconBlockBody)
		}
		if viewFn := t.Body.UnmarshalSSZDynView((*phase0.BeaconBlockBody)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *BeaconBlock) unmarshalSSZView_BeaconBlock_0(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 84 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 84)
	}
	{ // Field #0 'Slot' (static)
		buf := buf[0:8]
		t.Slot = phase0.Slot(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #1 'ProposerIndex' (static)
		buf := buf[8:16]
		t.ProposerIndex = phase0.ValidatorIndex(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #2 'ParentRoot' (static)
		buf := buf[16:48]
		copy(t.ParentRoot[:], buf)
	}
	{ // Field #3 'StateRoot' (static)
		buf := buf[48:80]
		copy(t.StateRoot[:], buf)
	}
	// Field #4 'Body' (offset)
	offset4 := int(binary.LittleEndian.Uint32(buf[80:84]))
	if offset4 != 84 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset4, 84), "Body:o")
	}
	{ // Field #4 'Body' (dynamic)
		buf := buf[offset4:]
		if t.Body == nil {
			t.Body = new(BeaconBlockBody)
		}
		if viewFn := t.Body.UnmarshalSSZDynView((*altair.BeaconBlockBody)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *BeaconBlock) unmarshalSSZView_BeaconBlock_1(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 84 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 84)
	}
	{ // Field #0 'Slot' (static)
		buf := buf[0:8]
		t.Slot = phase0.Slot(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #1 'ProposerIndex' (static)
		buf := buf[8:16]
		t.ProposerIndex = phase0.ValidatorIndex(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #2 'ParentRoot' (static)
		buf := buf[16:48]
		copy(t.ParentRoot[:], buf)
	}
	{ // Field #3 'StateRoot' (static)
		buf := buf[48:80]
		copy(t.StateRoot[:], buf)
	}
	// Field #4 'Body' (offset)
	offset4 := int(binary.LittleEndian.Uint32(buf[80:84]))
	if offset4 != 84 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset4, 84), "Body:o")
	}
	{ // Field #4 'Body' (dynamic)
		buf := buf[offset4:]
		if t.Body == nil {
			t.Body = new(BeaconBlockBody)
		}
		if viewFn := t.Body.UnmarshalSSZDynView((*bellatrix.BeaconBlockBody)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *BeaconBlock) unmarshalSSZView_BeaconBlock_2(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 84 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 84)
	}
	{ // Field #0 'Slot' (static)
		buf := buf[0:8]
		t.Slot = phase0.Slot(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #1 'ProposerIndex' (static)
		buf := buf[8:16]
		t.ProposerIndex = phase0.ValidatorIndex(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #2 'ParentRoot' (static)
		buf := buf[16:48]
		copy(t.ParentRoot[:], buf)
	}
	{ // Field #3 'StateRoot' (static)
		buf := buf[48:80]
		copy(t.StateRoot[:], buf)
	}
	// Field #4 'Body' (offset)
	offset4 := int(binary.LittleEndian.Uint32(buf[80:84]))
	if offset4 != 84 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset4, 84), "Body:o")
	}
	{ // Field #4 'Body' (dynamic)
		buf := buf[offset4:]
		if t.Body == nil {
			t.Body = new(BeaconBlockBody)
		}
		if viewFn := t.Body.UnmarshalSSZDynView((*capella.BeaconBlockBody)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *BeaconBlock) unmarshalSSZView_BeaconBlock_3(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 84 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 84)
	}
	{ // Field #0 'Slot' (static)
		buf := buf[0:8]
		t.Slot = phase0.Slot(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #1 'ProposerIndex' (static)
		buf := buf[8:16]
		t.ProposerIndex = phase0.ValidatorIndex(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #2 'ParentRoot' (static)
		buf := buf[16:48]
		copy(t.ParentRoot[:], buf)
	}
	{ // Field #3 'StateRoot' (static)
		buf := buf[48:80]
		copy(t.StateRoot[:], buf)
	}
	// Field #4 'Body' (offset)
	offset4 := int(binary.LittleEndian.Uint32(buf[80:84]))
	if offset4 != 84 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset4, 84), "Body:o")
	}
	{ // Field #4 'Body' (dynamic)
		buf := buf[offset4:]
		if t.Body == nil {
			t.Body = new(BeaconBlockBody)
		}
		if viewFn := t.Body.UnmarshalSSZDynView((*deneb.BeaconBlockBody)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *BeaconBlock) unmarshalSSZView_BeaconBlock_4(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 84 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 84)
	}
	{ // Field #0 'Slot' (static)
		buf := buf[0:8]
		t.Slot = phase0.Slot(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #1 'ProposerIndex' (static)
		buf := buf[8:16]
		t.ProposerIndex = phase0.ValidatorIndex(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #2 'ParentRoot' (static)
		buf := buf[16:48]
		copy(t.ParentRoot[:], buf)
	}
	{ // Field #3 'StateRoot' (static)
		buf := buf[48:80]
		copy(t.StateRoot[:], buf)
	}
	// Field #4 'Body' (offset)
	offset4 := int(binary.LittleEndian.Uint32(buf[80:84]))
	if offset4 != 84 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset4, 84), "Body:o")
	}
	{ // Field #4 'Body' (dynamic)
		buf := buf[offset4:]
		if t.Body == nil {
			t.Body = new(BeaconBlockBody)
		}
		if viewFn := t.Body.UnmarshalSSZDynView((*electra.BeaconBlockBody)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *BeaconBlock) unmarshalSSZView_BeaconBlock_5(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 84 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 84)
	}
	{ // Field #0 'Slot' (static)
		buf := buf[0:8]
		t.Slot = phase0.Slot(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #1 'ProposerIndex' (static)
		buf := buf[8:16]
		t.ProposerIndex = phase0.ValidatorIndex(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #2 'ParentRoot' (static)
		buf := buf[16:48]
		copy(t.ParentRoot[:], buf)
	}
	{ // Field #3 'StateRoot' (static)
		buf := buf[48:80]
		copy(t.StateRoot[:], buf)
	}
	// Field #4 'Body' (offset)
	offset4 := int(binary.LittleEndian.Uint32(buf[80:84]))
	if offset4 != 84 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset4, 84), "Body:o")
	}
	{ // Field #4 'Body' (dynamic)
		buf := buf[offset4:]
		if t.Body == nil {
			t.Body = new(BeaconBlockBody)
		}
		if viewFn := t.Body.UnmarshalSSZDynView((*gloas.BeaconBlockBody)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *BeaconBlock) unmarshalSSZView_BeaconBlock_6(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 84 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 84)
	}
	{ // Field #0 'Slot' (static)
		buf := buf[0:8]
		t.Slot = phase0.Slot(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #1 'ProposerIndex' (static)
		buf := buf[8:16]
		t.ProposerIndex = phase0.ValidatorIndex(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #2 'ParentRoot' (static)
		buf := buf[16:48]
		copy(t.ParentRoot[:], buf)
	}
	{ // Field #3 'StateRoot' (static)
		buf := buf[48:80]
		copy(t.StateRoot[:], buf)
	}
	// Field #4 'Body' (offset)
	offset4 := int(binary.LittleEndian.Uint32(buf[80:84]))
	if offset4 != 84 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset4, 84), "Body:o")
	}
	{ // Field #4 'Body' (dynamic)
		buf := buf[offset4:]
		if t.Body == nil {
			t.Body = new(BeaconBlockBody)
		}
		if viewFn := t.Body.UnmarshalSSZDynView((*heze.BeaconBlockBody)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *BeaconBlock) SizeSSZDynView(view any) func(ds sszutils.DynamicSpecs) int {
	switch view.(type) {
	case *phase0.BeaconBlock:
		return t.sizeSSZView_BeaconBlock
	case *altair.BeaconBlock:
		return t.sizeSSZView_BeaconBlock_0
	case *bellatrix.BeaconBlock:
		return t.sizeSSZView_BeaconBlock_1
	case *capella.BeaconBlock:
		return t.sizeSSZView_BeaconBlock_2
	case *deneb.BeaconBlock:
		return t.sizeSSZView_BeaconBlock_3
	case *electra.BeaconBlock:
		return t.sizeSSZView_BeaconBlock_4
	case *gloas.BeaconBlock:
		return t.sizeSSZView_BeaconBlock_5
	case *heze.BeaconBlock:
		return t.sizeSSZView_BeaconBlock_6
	}
	return nil
}
func (t *BeaconBlock) sizeSSZView_BeaconBlock(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(BeaconBlock)
	}
	// Field #0 'Slot' static (8 bytes)
	// Field #1 'ProposerIndex' static (8 bytes)
	// Field #2 'ParentRoot' static (32 bytes)
	// Field #3 'StateRoot' static (32 bytes)
	// Field #4 'Body' offset (4 bytes)
	size += 84
	{ // Dynamic field #4 'Body'
		if viewFn := t.Body.SizeSSZDynView((*phase0.BeaconBlockBody)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *BeaconBlock) sizeSSZView_BeaconBlock_0(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(BeaconBlock)
	}
	// Field #0 'Slot' static (8 bytes)
	// Field #1 'ProposerIndex' static (8 bytes)
	// Field #2 'ParentRoot' static (32 bytes)
	// Field #3 'StateRoot' static (32 bytes)
	// Field #4 'Body' offset (4 bytes)
	size += 84
	{ // Dynamic field #4 'Body'
		if viewFn := t.Body.SizeSSZDynView((*altair.BeaconBlockBody)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *BeaconBlock) sizeSSZView_BeaconBlock_1(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(BeaconBlock)
	}
	// Field #0 'Slot' static (8 bytes)
	// Field #1 'ProposerIndex' static (8 bytes)
	// Field #2 'ParentRoot' static (32 bytes)
	// Field #3 'StateRoot' static (32 bytes)
	// Field #4 'Body' offset (4 bytes)
	size += 84
	{ // Dynamic field #4 'Body'
		if viewFn := t.Body.SizeSSZDynView((*bellatrix.BeaconBlockBody)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *BeaconBlock) sizeSSZView_BeaconBlock_2(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(BeaconBlock)
	}
	// Field #0 'Slot' static (8 bytes)
	// Field #1 'ProposerIndex' static (8 bytes)
	// Field #2 'ParentRoot' static (32 bytes)
	// Field #3 'StateRoot' static (32 bytes)
	// Field #4 'Body' offset (4 bytes)
	size += 84
	{ // Dynamic field #4 'Body'
		if viewFn := t.Body.SizeSSZDynView((*capella.BeaconBlockBody)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *BeaconBlock) sizeSSZView_BeaconBlock_3(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(BeaconBlock)
	}
	// Field #0 'Slot' static (8 bytes)
	// Field #1 'ProposerIndex' static (8 bytes)
	// Field #2 'ParentRoot' static (32 bytes)
	// Field #3 'StateRoot' static (32 bytes)
	// Field #4 'Body' offset (4 bytes)
	size += 84
	{ // Dynamic field #4 'Body'
		if viewFn := t.Body.SizeSSZDynView((*deneb.BeaconBlockBody)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *BeaconBlock) sizeSSZView_BeaconBlock_4(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(BeaconBlock)
	}
	// Field #0 'Slot' static (8 bytes)
	// Field #1 'ProposerIndex' static (8 bytes)
	// Field #2 'ParentRoot' static (32 bytes)
	// Field #3 'StateRoot' static (32 bytes)
	// Field #4 'Body' offset (4 bytes)
	size += 84
	{ // Dynamic field #4 'Body'
		if viewFn := t.Body.SizeSSZDynView((*electra.BeaconBlockBody)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *BeaconBlock) sizeSSZView_BeaconBlock_5(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(BeaconBlock)
	}
	// Field #0 'Slot' static (8 bytes)
	// Field #1 'ProposerIndex' static (8 bytes)
	// Field #2 'ParentRoot' static (32 bytes)
	// Field #3 'StateRoot' static (32 bytes)
	// Field #4 'Body' offset (4 bytes)
	size += 84
	{ // Dynamic field #4 'Body'
		if viewFn := t.Body.SizeSSZDynView((*gloas.BeaconBlockBody)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *BeaconBlock) sizeSSZView_BeaconBlock_6(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(BeaconBlock)
	}
	// Field #0 'Slot' static (8 bytes)
	// Field #1 'ProposerIndex' static (8 bytes)
	// Field #2 'ParentRoot' static (32 bytes)
	// Field #3 'StateRoot' static (32 bytes)
	// Field #4 'Body' offset (4 bytes)
	size += 84
	{ // Dynamic field #4 'Body'
		if viewFn := t.Body.SizeSSZDynView((*heze.BeaconBlockBody)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *BeaconBlock) HashTreeRootWithDynView(view any) func(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	switch view.(type) {
	case *phase0.BeaconBlock:
		return t.hashTreeRootView_BeaconBlock
	case *altair.BeaconBlock:
		return t.hashTreeRootView_BeaconBlock_0
	case *bellatrix.BeaconBlock:
		return t.hashTreeRootView_BeaconBlock_1
	case *capella.BeaconBlock:
		return t.hashTreeRootView_BeaconBlock_2
	case *deneb.BeaconBlock:
		return t.hashTreeRootView_BeaconBlock_3
	case *electra.BeaconBlock:
		return t.hashTreeRootView_BeaconBlock_4
	case *gloas.BeaconBlock:
		return t.hashTreeRootView_BeaconBlock_5
	case *heze.BeaconBlock:
		return t.hashTreeRootView_BeaconBlock_6
	}
	return nil
}
func (t *BeaconBlock) hashTreeRootView_BeaconBlock(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BeaconBlock)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Slot'
		hh.PutUint64(uint64(t.Slot))
	}
	{ // Field #1 'ProposerIndex'
		hh.PutUint64(uint64(t.ProposerIndex))
	}
	{ // Field #2 'ParentRoot'
		hh.PutBytes(t.ParentRoot[:32])
	}
	{ // Field #3 'StateRoot'
		hh.PutBytes(t.StateRoot[:32])
	}
	{ // Field #4 'Body'
		t := t.Body
		if t == nil {
			t = new(BeaconBlockBody)
		}
		if viewFn := t.HashTreeRootWithDynView((*phase0.BeaconBlockBody)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	hh.Merkleize(idx)
	return nil
}

func (t *BeaconBlock) hashTreeRootView_BeaconBlock_0(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BeaconBlock)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Slot'
		hh.PutUint64(uint64(t.Slot))
	}
	{ // Field #1 'ProposerIndex'
		hh.PutUint64(uint64(t.ProposerIndex))
	}
	{ // Field #2 'ParentRoot'
		hh.PutBytes(t.ParentRoot[:32])
	}
	{ // Field #3 'StateRoot'
		hh.PutBytes(t.StateRoot[:32])
	}
	{ // Field #4 'Body'
		t := t.Body
		if t == nil {
			t = new(BeaconBlockBody)
		}
		if viewFn := t.HashTreeRootWithDynView((*altair.BeaconBlockBody)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	hh.Merkleize(idx)
	return nil
}

func (t *BeaconBlock) hashTreeRootView_BeaconBlock_1(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BeaconBlock)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Slot'
		hh.PutUint64(uint64(t.Slot))
	}
	{ // Field #1 'ProposerIndex'
		hh.PutUint64(uint64(t.ProposerIndex))
	}
	{ // Field #2 'ParentRoot'
		hh.PutBytes(t.ParentRoot[:32])
	}
	{ // Field #3 'StateRoot'
		hh.PutBytes(t.StateRoot[:32])
	}
	{ // Field #4 'Body'
		t := t.Body
		if t == nil {
			t = new(BeaconBlockBody)
		}
		if viewFn := t.HashTreeRootWithDynView((*bellatrix.BeaconBlockBody)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	hh.Merkleize(idx)
	return nil
}

func (t *BeaconBlock) hashTreeRootView_BeaconBlock_2(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BeaconBlock)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Slot'
		hh.PutUint64(uint64(t.Slot))
	}
	{ // Field #1 'ProposerIndex'
		hh.PutUint64(uint64(t.ProposerIndex))
	}
	{ // Field #2 'ParentRoot'
		hh.PutBytes(t.ParentRoot[:32])
	}
	{ // Field #3 'StateRoot'
		hh.PutBytes(t.StateRoot[:32])
	}
	{ // Field #4 'Body'
		t := t.Body
		if t == nil {
			t = new(BeaconBlockBody)
		}
		if viewFn := t.HashTreeRootWithDynView((*capella.BeaconBlockBody)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	hh.Merkleize(idx)
	return nil
}

func (t *BeaconBlock) hashTreeRootView_BeaconBlock_3(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BeaconBlock)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Slot'
		hh.PutUint64(uint64(t.Slot))
	}
	{ // Field #1 'ProposerIndex'
		hh.PutUint64(uint64(t.ProposerIndex))
	}
	{ // Field #2 'ParentRoot'
		hh.PutBytes(t.ParentRoot[:32])
	}
	{ // Field #3 'StateRoot'
		hh.PutBytes(t.StateRoot[:32])
	}
	{ // Field #4 'Body'
		t := t.Body
		if t == nil {
			t = new(BeaconBlockBody)
		}
		if viewFn := t.HashTreeRootWithDynView((*deneb.BeaconBlockBody)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	hh.Merkleize(idx)
	return nil
}

func (t *BeaconBlock) hashTreeRootView_BeaconBlock_4(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BeaconBlock)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Slot'
		hh.PutUint64(uint64(t.Slot))
	}
	{ // Field #1 'ProposerIndex'
		hh.PutUint64(uint64(t.ProposerIndex))
	}
	{ // Field #2 'ParentRoot'
		hh.PutBytes(t.ParentRoot[:32])
	}
	{ // Field #3 'StateRoot'
		hh.PutBytes(t.StateRoot[:32])
	}
	{ // Field #4 'Body'
		t := t.Body
		if t == nil {
			t = new(BeaconBlockBody)
		}
		if viewFn := t.HashTreeRootWithDynView((*electra.BeaconBlockBody)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	hh.Merkleize(idx)
	return nil
}

func (t *BeaconBlock) hashTreeRootView_BeaconBlock_5(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BeaconBlock)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Slot'
		hh.PutUint64(uint64(t.Slot))
	}
	{ // Field #1 'ProposerIndex'
		hh.PutUint64(uint64(t.ProposerIndex))
	}
	{ // Field #2 'ParentRoot'
		hh.PutBytes(t.ParentRoot[:32])
	}
	{ // Field #3 'StateRoot'
		hh.PutBytes(t.StateRoot[:32])
	}
	{ // Field #4 'Body'
		t := t.Body
		if t == nil {
			t = new(BeaconBlockBody)
		}
		if viewFn := t.HashTreeRootWithDynView((*gloas.BeaconBlockBody)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	hh.Merkleize(idx)
	return nil
}

func (t *BeaconBlock) hashTreeRootView_BeaconBlock_6(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BeaconBlock)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Slot'
		hh.PutUint64(uint64(t.Slot))
	}
	{ // Field #1 'ProposerIndex'
		hh.PutUint64(uint64(t.ProposerIndex))
	}
	{ // Field #2 'ParentRoot'
		hh.PutBytes(t.ParentRoot[:32])
	}
	{ // Field #3 'StateRoot'
		hh.PutBytes(t.StateRoot[:32])
	}
	{ // Field #4 'Body'
		t := t.Body
		if t == nil {
			t = new(BeaconBlockBody)
		}
		if viewFn := t.HashTreeRootWithDynView((*heze.BeaconBlockBody)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	hh.Merkleize(idx)
	return nil
}
