// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 3b6a989fdee77c93cb25dec43c38e8a304c4732d9032a86c45b14c11f306f2a8
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package all

import (
	"encoding/binary"

	"github.com/ethpandaops/go-eth2-client/spec/bellatrix"
	"github.com/ethpandaops/go-eth2-client/spec/capella"
	"github.com/ethpandaops/go-eth2-client/spec/deneb"
	"github.com/ethpandaops/go-eth2-client/spec/gloas"
	"github.com/holiman/uint256"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *ExecutionPayload) MarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) ([]byte, error) {
	switch view.(type) {
	case *bellatrix.ExecutionPayload:
		return t.marshalSSZView_ExecutionPayload
	case *capella.ExecutionPayload:
		return t.marshalSSZView_ExecutionPayload_0
	case *deneb.ExecutionPayload:
		return t.marshalSSZView_ExecutionPayload_1
	case *gloas.ExecutionPayload:
		return t.marshalSSZView_ExecutionPayload_2
	}
	return nil
}
func (t *ExecutionPayload) marshalSSZView_ExecutionPayload(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_EXTRA_DATA_BYTES", 32)
	if err != nil {
		return dst, err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_TRANSACTIONS_PER_PAYLOAD", 1048576)
	if err != nil {
		return dst, err
	}
	expr2, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BYTES_PER_TRANSACTION", 1073741824)
	if err != nil {
		return dst, err
	}
	if t == nil {
		t = new(ExecutionPayload)
	}
	dstlen := len(dst)
	{ // Static Field #0 'ParentHash'
		dst = append(dst, t.ParentHash[:32]...)
	}
	{ // Static Field #1 'FeeRecipient'
		dst = append(dst, t.FeeRecipient[:20]...)
	}
	{ // Static Field #2 'StateRoot'
		dst = append(dst, t.StateRoot[:32]...)
	}
	{ // Static Field #3 'ReceiptsRoot'
		dst = append(dst, t.ReceiptsRoot[:32]...)
	}
	{ // Static Field #4 'LogsBloom'
		dst = append(dst, t.LogsBloom[:256]...)
	}
	{ // Static Field #5 'PrevRandao'
		dst = append(dst, t.PrevRandao[:32]...)
	}
	{ // Static Field #6 'BlockNumber'
		dst = binary.LittleEndian.AppendUint64(dst, t.BlockNumber)
	}
	{ // Static Field #7 'GasLimit'
		dst = binary.LittleEndian.AppendUint64(dst, t.GasLimit)
	}
	{ // Static Field #8 'GasUsed'
		dst = binary.LittleEndian.AppendUint64(dst, t.GasUsed)
	}
	{ // Static Field #9 'Timestamp'
		dst = binary.LittleEndian.AppendUint64(dst, t.Timestamp)
	}
	// Offset Field #10 'ExtraData'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #11 'BaseFeePerGasLE'
		dst = append(dst, t.BaseFeePerGasLE[:32]...)
	}
	{ // Static Field #12 'BlockHash'
		dst = append(dst, t.BlockHash[:32]...)
	}
	// Offset Field #13 'Transactions'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #10 'ExtraData'
		binary.LittleEndian.PutUint32(dst[dstlen+436:], uint32(len(dst)-dstlen))
		vlen := len(t.ExtraData)
		if vlen > int(expr0) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr0)), "ExtraData")
		}
		dst = append(dst, t.ExtraData[:]...)
	}
	{ // Dynamic Field #13 'Transactions'
		binary.LittleEndian.PutUint32(dst[dstlen+504:], uint32(len(dst)-dstlen))
		t := t.Transactions
		vlen := len(t)
		if vlen > int(expr1) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr1)), "Transactions")
		}
		dstlen := len(dst)
		dst = sszutils.AppendZeroPadding(dst, vlen*4)
		for idx1 := range vlen {
			binary.LittleEndian.PutUint32(dst[dstlen+(idx1*4):], uint32(len(dst)-dstlen))
			vlen := len(t[idx1])
			if vlen > int(expr2) {
				return nil, sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(vlen, int(expr2)), "Transactions[%d]", idx1)
			}
			dst = append(dst, t[idx1][:]...)
		}
	}
	return dst, nil
}

func (t *ExecutionPayload) marshalSSZView_ExecutionPayload_0(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_EXTRA_DATA_BYTES", 32)
	if err != nil {
		return dst, err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_TRANSACTIONS_PER_PAYLOAD", 1048576)
	if err != nil {
		return dst, err
	}
	expr2, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BYTES_PER_TRANSACTION", 1073741824)
	if err != nil {
		return dst, err
	}
	expr3, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_WITHDRAWALS_PER_PAYLOAD", 16)
	if err != nil {
		return dst, err
	}
	if t == nil {
		t = new(ExecutionPayload)
	}
	dstlen := len(dst)
	{ // Static Field #0 'ParentHash'
		dst = append(dst, t.ParentHash[:32]...)
	}
	{ // Static Field #1 'FeeRecipient'
		dst = append(dst, t.FeeRecipient[:20]...)
	}
	{ // Static Field #2 'StateRoot'
		dst = append(dst, t.StateRoot[:32]...)
	}
	{ // Static Field #3 'ReceiptsRoot'
		dst = append(dst, t.ReceiptsRoot[:32]...)
	}
	{ // Static Field #4 'LogsBloom'
		dst = append(dst, t.LogsBloom[:256]...)
	}
	{ // Static Field #5 'PrevRandao'
		dst = append(dst, t.PrevRandao[:32]...)
	}
	{ // Static Field #6 'BlockNumber'
		dst = binary.LittleEndian.AppendUint64(dst, t.BlockNumber)
	}
	{ // Static Field #7 'GasLimit'
		dst = binary.LittleEndian.AppendUint64(dst, t.GasLimit)
	}
	{ // Static Field #8 'GasUsed'
		dst = binary.LittleEndian.AppendUint64(dst, t.GasUsed)
	}
	{ // Static Field #9 'Timestamp'
		dst = binary.LittleEndian.AppendUint64(dst, t.Timestamp)
	}
	// Offset Field #10 'ExtraData'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #11 'BaseFeePerGasLE'
		dst = append(dst, t.BaseFeePerGasLE[:32]...)
	}
	{ // Static Field #12 'BlockHash'
		dst = append(dst, t.BlockHash[:32]...)
	}
	// Offset Field #13 'Transactions'
	// Offset Field #14 'Withdrawals'
	dst = append(dst, 0, 0, 0, 0, 0, 0, 0, 0)
	{ // Dynamic Field #10 'ExtraData'
		binary.LittleEndian.PutUint32(dst[dstlen+436:], uint32(len(dst)-dstlen))
		vlen := len(t.ExtraData)
		if vlen > int(expr0) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr0)), "ExtraData")
		}
		dst = append(dst, t.ExtraData[:]...)
	}
	{ // Dynamic Field #13 'Transactions'
		binary.LittleEndian.PutUint32(dst[dstlen+504:], uint32(len(dst)-dstlen))
		t := t.Transactions
		vlen := len(t)
		if vlen > int(expr1) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr1)), "Transactions")
		}
		dstlen := len(dst)
		dst = sszutils.AppendZeroPadding(dst, vlen*4)
		for idx1 := range vlen {
			binary.LittleEndian.PutUint32(dst[dstlen+(idx1*4):], uint32(len(dst)-dstlen))
			vlen := len(t[idx1])
			if vlen > int(expr2) {
				return nil, sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(vlen, int(expr2)), "Transactions[%d]", idx1)
			}
			dst = append(dst, t[idx1][:]...)
		}
	}
	{ // Dynamic Field #14 'Withdrawals'
		binary.LittleEndian.PutUint32(dst[dstlen+508:], uint32(len(dst)-dstlen))
		t := t.Withdrawals
		vlen := len(t)
		if vlen > int(expr3) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr3)), "Withdrawals")
		}
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(capella.Withdrawal)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
		}
	}
	return dst, nil
}

func (t *ExecutionPayload) marshalSSZView_ExecutionPayload_1(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_EXTRA_DATA_BYTES", 32)
	if err != nil {
		return dst, err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_TRANSACTIONS_PER_PAYLOAD", 1048576)
	if err != nil {
		return dst, err
	}
	expr2, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BYTES_PER_TRANSACTION", 1073741824)
	if err != nil {
		return dst, err
	}
	expr3, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_WITHDRAWALS_PER_PAYLOAD", 16)
	if err != nil {
		return dst, err
	}
	if t == nil {
		t = new(ExecutionPayload)
	}
	dstlen := len(dst)
	{ // Static Field #0 'ParentHash'
		dst = append(dst, t.ParentHash[:32]...)
	}
	{ // Static Field #1 'FeeRecipient'
		dst = append(dst, t.FeeRecipient[:20]...)
	}
	{ // Static Field #2 'StateRoot'
		dst = append(dst, t.StateRoot[:32]...)
	}
	{ // Static Field #3 'ReceiptsRoot'
		dst = append(dst, t.ReceiptsRoot[:32]...)
	}
	{ // Static Field #4 'LogsBloom'
		dst = append(dst, t.LogsBloom[:256]...)
	}
	{ // Static Field #5 'PrevRandao'
		dst = append(dst, t.PrevRandao[:32]...)
	}
	{ // Static Field #6 'BlockNumber'
		dst = binary.LittleEndian.AppendUint64(dst, t.BlockNumber)
	}
	{ // Static Field #7 'GasLimit'
		dst = binary.LittleEndian.AppendUint64(dst, t.GasLimit)
	}
	{ // Static Field #8 'GasUsed'
		dst = binary.LittleEndian.AppendUint64(dst, t.GasUsed)
	}
	{ // Static Field #9 'Timestamp'
		dst = binary.LittleEndian.AppendUint64(dst, t.Timestamp)
	}
	// Offset Field #10 'ExtraData'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #11 'BaseFeePerGas'
		t := t.BaseFeePerGas
		if t == nil {
			t = new(uint256.Int)
		}
		dst = sszutils.MarshalUint64Slice(dst, (*t)[:4])
	}
	{ // Static Field #12 'BlockHash'
		dst = append(dst, t.BlockHash[:32]...)
	}
	// Offset Field #13 'Transactions'
	// Offset Field #14 'Withdrawals'
	dst = append(dst, 0, 0, 0, 0, 0, 0, 0, 0)
	{ // Static Field #15 'BlobGasUsed'
		dst = binary.LittleEndian.AppendUint64(dst, t.BlobGasUsed)
	}
	{ // Static Field #16 'ExcessBlobGas'
		dst = binary.LittleEndian.AppendUint64(dst, t.ExcessBlobGas)
	}
	{ // Dynamic Field #10 'ExtraData'
		binary.LittleEndian.PutUint32(dst[dstlen+436:], uint32(len(dst)-dstlen))
		vlen := len(t.ExtraData)
		if vlen > int(expr0) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr0)), "ExtraData")
		}
		dst = append(dst, t.ExtraData[:]...)
	}
	{ // Dynamic Field #13 'Transactions'
		binary.LittleEndian.PutUint32(dst[dstlen+504:], uint32(len(dst)-dstlen))
		t := t.Transactions
		vlen := len(t)
		if vlen > int(expr1) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr1)), "Transactions")
		}
		dstlen := len(dst)
		dst = sszutils.AppendZeroPadding(dst, vlen*4)
		for idx1 := range vlen {
			binary.LittleEndian.PutUint32(dst[dstlen+(idx1*4):], uint32(len(dst)-dstlen))
			vlen := len(t[idx1])
			if vlen > int(expr2) {
				return nil, sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(vlen, int(expr2)), "Transactions[%d]", idx1)
			}
			dst = append(dst, t[idx1][:]...)
		}
	}
	{ // Dynamic Field #14 'Withdrawals'
		binary.LittleEndian.PutUint32(dst[dstlen+508:], uint32(len(dst)-dstlen))
		t := t.Withdrawals
		vlen := len(t)
		if vlen > int(expr3) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr3)), "Withdrawals")
		}
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(capella.Withdrawal)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
		}
	}
	return dst, nil
}

func (t *ExecutionPayload) marshalSSZView_ExecutionPayload_2(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_EXTRA_DATA_BYTES", 32)
	if err != nil {
		return dst, err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_TRANSACTIONS_PER_PAYLOAD", 1048576)
	if err != nil {
		return dst, err
	}
	expr2, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BYTES_PER_TRANSACTION", 1073741824)
	if err != nil {
		return dst, err
	}
	expr3, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_WITHDRAWALS_PER_PAYLOAD", 16)
	if err != nil {
		return dst, err
	}
	if t == nil {
		t = new(ExecutionPayload)
	}
	dstlen := len(dst)
	{ // Static Field #0 'ParentHash'
		dst = append(dst, t.ParentHash[:32]...)
	}
	{ // Static Field #1 'FeeRecipient'
		dst = append(dst, t.FeeRecipient[:20]...)
	}
	{ // Static Field #2 'StateRoot'
		dst = append(dst, t.StateRoot[:32]...)
	}
	{ // Static Field #3 'ReceiptsRoot'
		dst = append(dst, t.ReceiptsRoot[:32]...)
	}
	{ // Static Field #4 'LogsBloom'
		dst = append(dst, t.LogsBloom[:256]...)
	}
	{ // Static Field #5 'PrevRandao'
		dst = append(dst, t.PrevRandao[:32]...)
	}
	{ // Static Field #6 'BlockNumber'
		dst = binary.LittleEndian.AppendUint64(dst, t.BlockNumber)
	}
	{ // Static Field #7 'GasLimit'
		dst = binary.LittleEndian.AppendUint64(dst, t.GasLimit)
	}
	{ // Static Field #8 'GasUsed'
		dst = binary.LittleEndian.AppendUint64(dst, t.GasUsed)
	}
	{ // Static Field #9 'Timestamp'
		dst = binary.LittleEndian.AppendUint64(dst, t.Timestamp)
	}
	// Offset Field #10 'ExtraData'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #11 'BaseFeePerGas'
		t := t.BaseFeePerGas
		if t == nil {
			t = new(uint256.Int)
		}
		dst = sszutils.MarshalUint64Slice(dst, (*t)[:4])
	}
	{ // Static Field #12 'BlockHash'
		dst = append(dst, t.BlockHash[:32]...)
	}
	// Offset Field #13 'Transactions'
	// Offset Field #14 'Withdrawals'
	dst = append(dst, 0, 0, 0, 0, 0, 0, 0, 0)
	{ // Static Field #15 'BlobGasUsed'
		dst = binary.LittleEndian.AppendUint64(dst, t.BlobGasUsed)
	}
	{ // Static Field #16 'ExcessBlobGas'
		dst = binary.LittleEndian.AppendUint64(dst, t.ExcessBlobGas)
	}
	// Offset Field #17 'BlockAccessList'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #18 'SlotNumber'
		dst = binary.LittleEndian.AppendUint64(dst, t.SlotNumber)
	}
	{ // Dynamic Field #10 'ExtraData'
		binary.LittleEndian.PutUint32(dst[dstlen+436:], uint32(len(dst)-dstlen))
		vlen := len(t.ExtraData)
		if vlen > int(expr0) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr0)), "ExtraData")
		}
		dst = append(dst, t.ExtraData[:]...)
	}
	{ // Dynamic Field #13 'Transactions'
		binary.LittleEndian.PutUint32(dst[dstlen+504:], uint32(len(dst)-dstlen))
		t := t.Transactions
		vlen := len(t)
		if vlen > int(expr1) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr1)), "Transactions")
		}
		dstlen := len(dst)
		dst = sszutils.AppendZeroPadding(dst, vlen*4)
		for idx1 := range vlen {
			binary.LittleEndian.PutUint32(dst[dstlen+(idx1*4):], uint32(len(dst)-dstlen))
			vlen := len(t[idx1])
			if vlen > int(expr2) {
				return nil, sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(vlen, int(expr2)), "Transactions[%d]", idx1)
			}
			dst = append(dst, t[idx1][:]...)
		}
	}
	{ // Dynamic Field #14 'Withdrawals'
		binary.LittleEndian.PutUint32(dst[dstlen+508:], uint32(len(dst)-dstlen))
		t := t.Withdrawals
		vlen := len(t)
		if vlen > int(expr3) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr3)), "Withdrawals")
		}
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(capella.Withdrawal)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
		}
	}
	{ // Dynamic Field #17 'BlockAccessList'
		binary.LittleEndian.PutUint32(dst[dstlen+528:], uint32(len(dst)-dstlen))
		vlen := len(t.BlockAccessList)
		if vlen > int(expr2) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr2)), "BlockAccessList")
		}
		dst = append(dst, t.BlockAccessList[:]...)
	}
	return dst, nil
}

func (t *ExecutionPayload) UnmarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) error {
	switch view.(type) {
	case *bellatrix.ExecutionPayload:
		return t.unmarshalSSZView_ExecutionPayload
	case *capella.ExecutionPayload:
		return t.unmarshalSSZView_ExecutionPayload_0
	case *deneb.ExecutionPayload:
		return t.unmarshalSSZView_ExecutionPayload_1
	case *gloas.ExecutionPayload:
		return t.unmarshalSSZView_ExecutionPayload_2
	}
	return nil
}
func (t *ExecutionPayload) unmarshalSSZView_ExecutionPayload(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_EXTRA_DATA_BYTES", 32)
	if err != nil {
		return err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_TRANSACTIONS_PER_PAYLOAD", 1048576)
	if err != nil {
		return err
	}
	expr2, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BYTES_PER_TRANSACTION", 1073741824)
	if err != nil {
		return err
	}
	buflen := len(buf)
	if buflen < 508 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 508)
	}
	{ // Field #0 'ParentHash' (static)
		buf := buf[0:32]
		copy(t.ParentHash[:], buf)
	}
	{ // Field #1 'FeeRecipient' (static)
		buf := buf[32:52]
		copy(t.FeeRecipient[:], buf)
	}
	{ // Field #2 'StateRoot' (static)
		buf := buf[52:84]
		copy(t.StateRoot[:], buf)
	}
	{ // Field #3 'ReceiptsRoot' (static)
		buf := buf[84:116]
		copy(t.ReceiptsRoot[:], buf)
	}
	{ // Field #4 'LogsBloom' (static)
		buf := buf[116:372]
		copy(t.LogsBloom[:], buf)
	}
	{ // Field #5 'PrevRandao' (static)
		buf := buf[372:404]
		copy(t.PrevRandao[:], buf)
	}
	{ // Field #6 'BlockNumber' (static)
		buf := buf[404:412]
		t.BlockNumber = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #7 'GasLimit' (static)
		buf := buf[412:420]
		t.GasLimit = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #8 'GasUsed' (static)
		buf := buf[420:428]
		t.GasUsed = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #9 'Timestamp' (static)
		buf := buf[428:436]
		t.Timestamp = binary.LittleEndian.Uint64(buf)
	}
	// Field #10 'ExtraData' (offset)
	offset10 := int(binary.LittleEndian.Uint32(buf[436:440]))
	if offset10 != 508 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset10, 508), "ExtraData:o")
	}
	{ // Field #11 'BaseFeePerGasLE' (static)
		buf := buf[440:472]
		copy(t.BaseFeePerGasLE[:], buf)
	}
	{ // Field #12 'BlockHash' (static)
		buf := buf[472:504]
		copy(t.BlockHash[:], buf)
	}
	// Field #13 'Transactions' (offset)
	offset13 := int(binary.LittleEndian.Uint32(buf[504:508]))
	if offset13 < offset10 || offset13 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset13, offset10, buflen), "Transactions:o")
	}
	{ // Field #10 'ExtraData' (dynamic)
		buf := buf[offset10:offset13]
		if len(buf) > int(expr0) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(len(buf), int(expr0)), "ExtraData")
		}
		t.ExtraData = sszutils.ExpandSlice(t.ExtraData, len(buf))
		copy(t.ExtraData[:], buf)
	}
	{ // Field #13 'Transactions' (dynamic)
		buf := buf[offset13:]
		val1 := t.Transactions
		startOffset := int(0)
		if len(buf) != 0 {
			if len(buf) < 4 {
				return sszutils.ErrorWithPath(sszutils.ErrListOffsetsEOFFn(len(buf), 4), "Transactions")
			}
			startOffset = int(binary.LittleEndian.Uint32(buf[0:4]))
		}
		itemCount := startOffset / 4
		if startOffset%4 != 0 || len(buf) < startOffset {
			return sszutils.ErrorWithPath(sszutils.ErrInvalidListStartOffsetFn(startOffset, len(buf)), "Transactions")
		}
		if itemCount > int(expr1) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr1)), "Transactions")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for idx1 := range itemCount {
			var endOffset int
			if idx1 < itemCount-1 {
				endOffset = int(binary.LittleEndian.Uint32(buf[(idx1+1)*4 : (idx1+2)*4]))
			} else {
				endOffset = len(buf)
			}
			if endOffset < startOffset || endOffset > len(buf) {
				return sszutils.ErrorWithPathf(sszutils.ErrElementOffsetOutOfRangeFn(endOffset, startOffset, len(buf)), "Transactions[%d]", idx1)
			}
			buf := buf[startOffset:endOffset]
			startOffset = endOffset
			val2 := val1[idx1]
			if len(buf) > int(expr2) {
				return sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(len(buf), int(expr2)), "Transactions[%d]", idx1)
			}
			val2 = sszutils.ExpandSlice(val2, len(buf))
			copy(val2[:], buf)
			val1[idx1] = val2
		}
		t.Transactions = val1
	}
	return nil
}

func (t *ExecutionPayload) unmarshalSSZView_ExecutionPayload_0(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_EXTRA_DATA_BYTES", 32)
	if err != nil {
		return err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_TRANSACTIONS_PER_PAYLOAD", 1048576)
	if err != nil {
		return err
	}
	expr2, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BYTES_PER_TRANSACTION", 1073741824)
	if err != nil {
		return err
	}
	expr3, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_WITHDRAWALS_PER_PAYLOAD", 16)
	if err != nil {
		return err
	}
	buflen := len(buf)
	if buflen < 512 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 512)
	}
	{ // Field #0 'ParentHash' (static)
		buf := buf[0:32]
		copy(t.ParentHash[:], buf)
	}
	{ // Field #1 'FeeRecipient' (static)
		buf := buf[32:52]
		copy(t.FeeRecipient[:], buf)
	}
	{ // Field #2 'StateRoot' (static)
		buf := buf[52:84]
		copy(t.StateRoot[:], buf)
	}
	{ // Field #3 'ReceiptsRoot' (static)
		buf := buf[84:116]
		copy(t.ReceiptsRoot[:], buf)
	}
	{ // Field #4 'LogsBloom' (static)
		buf := buf[116:372]
		copy(t.LogsBloom[:], buf)
	}
	{ // Field #5 'PrevRandao' (static)
		buf := buf[372:404]
		copy(t.PrevRandao[:], buf)
	}
	{ // Field #6 'BlockNumber' (static)
		buf := buf[404:412]
		t.BlockNumber = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #7 'GasLimit' (static)
		buf := buf[412:420]
		t.GasLimit = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #8 'GasUsed' (static)
		buf := buf[420:428]
		t.GasUsed = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #9 'Timestamp' (static)
		buf := buf[428:436]
		t.Timestamp = binary.LittleEndian.Uint64(buf)
	}
	// Field #10 'ExtraData' (offset)
	offset10 := int(binary.LittleEndian.Uint32(buf[436:440]))
	if offset10 != 512 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset10, 512), "ExtraData:o")
	}
	{ // Field #11 'BaseFeePerGasLE' (static)
		buf := buf[440:472]
		copy(t.BaseFeePerGasLE[:], buf)
	}
	{ // Field #12 'BlockHash' (static)
		buf := buf[472:504]
		copy(t.BlockHash[:], buf)
	}
	// Field #13 'Transactions' (offset)
	offset13 := int(binary.LittleEndian.Uint32(buf[504:508]))
	if offset13 < offset10 || offset13 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset13, offset10, buflen), "Transactions:o")
	}
	// Field #14 'Withdrawals' (offset)
	offset14 := int(binary.LittleEndian.Uint32(buf[508:512]))
	if offset14 < offset13 || offset14 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset14, offset13, buflen), "Withdrawals:o")
	}
	{ // Field #10 'ExtraData' (dynamic)
		buf := buf[offset10:offset13]
		if len(buf) > int(expr0) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(len(buf), int(expr0)), "ExtraData")
		}
		t.ExtraData = sszutils.ExpandSlice(t.ExtraData, len(buf))
		copy(t.ExtraData[:], buf)
	}
	{ // Field #13 'Transactions' (dynamic)
		buf := buf[offset13:offset14]
		val1 := t.Transactions
		startOffset := int(0)
		if len(buf) != 0 {
			if len(buf) < 4 {
				return sszutils.ErrorWithPath(sszutils.ErrListOffsetsEOFFn(len(buf), 4), "Transactions")
			}
			startOffset = int(binary.LittleEndian.Uint32(buf[0:4]))
		}
		itemCount := startOffset / 4
		if startOffset%4 != 0 || len(buf) < startOffset {
			return sszutils.ErrorWithPath(sszutils.ErrInvalidListStartOffsetFn(startOffset, len(buf)), "Transactions")
		}
		if itemCount > int(expr1) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr1)), "Transactions")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for idx1 := range itemCount {
			var endOffset int
			if idx1 < itemCount-1 {
				endOffset = int(binary.LittleEndian.Uint32(buf[(idx1+1)*4 : (idx1+2)*4]))
			} else {
				endOffset = len(buf)
			}
			if endOffset < startOffset || endOffset > len(buf) {
				return sszutils.ErrorWithPathf(sszutils.ErrElementOffsetOutOfRangeFn(endOffset, startOffset, len(buf)), "Transactions[%d]", idx1)
			}
			buf := buf[startOffset:endOffset]
			startOffset = endOffset
			val2 := val1[idx1]
			if len(buf) > int(expr2) {
				return sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(len(buf), int(expr2)), "Transactions[%d]", idx1)
			}
			val2 = sszutils.ExpandSlice(val2, len(buf))
			copy(val2[:], buf)
			val1[idx1] = val2
		}
		t.Transactions = val1
	}
	{ // Field #14 'Withdrawals' (dynamic)
		buf := buf[offset14:]
		val3 := t.Withdrawals
		itemCount := len(buf) / 44
		if len(buf)%44 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 44), "Withdrawals")
		}
		if itemCount > int(expr3) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr3)), "Withdrawals")
		}
		val3 = sszutils.ExpandSlice(val3, itemCount)
		for idx1 := range itemCount {
			if val3[idx1] == nil {
				val3[idx1] = new(capella.Withdrawal)
			}
			buf := buf[44*idx1 : 44*(idx1+1)]
			if err = val3[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
		}
		t.Withdrawals = val3
	}
	return nil
}

func (t *ExecutionPayload) unmarshalSSZView_ExecutionPayload_1(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_EXTRA_DATA_BYTES", 32)
	if err != nil {
		return err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_TRANSACTIONS_PER_PAYLOAD", 1048576)
	if err != nil {
		return err
	}
	expr2, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BYTES_PER_TRANSACTION", 1073741824)
	if err != nil {
		return err
	}
	expr3, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_WITHDRAWALS_PER_PAYLOAD", 16)
	if err != nil {
		return err
	}
	buflen := len(buf)
	if buflen < 528 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 528)
	}
	{ // Field #0 'ParentHash' (static)
		buf := buf[0:32]
		copy(t.ParentHash[:], buf)
	}
	{ // Field #1 'FeeRecipient' (static)
		buf := buf[32:52]
		copy(t.FeeRecipient[:], buf)
	}
	{ // Field #2 'StateRoot' (static)
		buf := buf[52:84]
		copy(t.StateRoot[:], buf)
	}
	{ // Field #3 'ReceiptsRoot' (static)
		buf := buf[84:116]
		copy(t.ReceiptsRoot[:], buf)
	}
	{ // Field #4 'LogsBloom' (static)
		buf := buf[116:372]
		copy(t.LogsBloom[:], buf)
	}
	{ // Field #5 'PrevRandao' (static)
		buf := buf[372:404]
		copy(t.PrevRandao[:], buf)
	}
	{ // Field #6 'BlockNumber' (static)
		buf := buf[404:412]
		t.BlockNumber = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #7 'GasLimit' (static)
		buf := buf[412:420]
		t.GasLimit = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #8 'GasUsed' (static)
		buf := buf[420:428]
		t.GasUsed = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #9 'Timestamp' (static)
		buf := buf[428:436]
		t.Timestamp = binary.LittleEndian.Uint64(buf)
	}
	// Field #10 'ExtraData' (offset)
	offset10 := int(binary.LittleEndian.Uint32(buf[436:440]))
	if offset10 != 528 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset10, 528), "ExtraData:o")
	}
	{ // Field #11 'BaseFeePerGas' (static)
		buf := buf[440:472]
		val1 := t.BaseFeePerGas
		if val1 == nil {
			val1 = new(uint256.Int)
		}
		sszutils.UnmarshalUint64Slice((*val1)[:4], buf)
		t.BaseFeePerGas = val1
	}
	{ // Field #12 'BlockHash' (static)
		buf := buf[472:504]
		copy(t.BlockHash[:], buf)
	}
	// Field #13 'Transactions' (offset)
	offset13 := int(binary.LittleEndian.Uint32(buf[504:508]))
	if offset13 < offset10 || offset13 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset13, offset10, buflen), "Transactions:o")
	}
	// Field #14 'Withdrawals' (offset)
	offset14 := int(binary.LittleEndian.Uint32(buf[508:512]))
	if offset14 < offset13 || offset14 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset14, offset13, buflen), "Withdrawals:o")
	}
	{ // Field #15 'BlobGasUsed' (static)
		buf := buf[512:520]
		t.BlobGasUsed = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #16 'ExcessBlobGas' (static)
		buf := buf[520:528]
		t.ExcessBlobGas = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #10 'ExtraData' (dynamic)
		buf := buf[offset10:offset13]
		if len(buf) > int(expr0) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(len(buf), int(expr0)), "ExtraData")
		}
		t.ExtraData = sszutils.ExpandSlice(t.ExtraData, len(buf))
		copy(t.ExtraData[:], buf)
	}
	{ // Field #13 'Transactions' (dynamic)
		buf := buf[offset13:offset14]
		val2 := t.Transactions
		startOffset := int(0)
		if len(buf) != 0 {
			if len(buf) < 4 {
				return sszutils.ErrorWithPath(sszutils.ErrListOffsetsEOFFn(len(buf), 4), "Transactions")
			}
			startOffset = int(binary.LittleEndian.Uint32(buf[0:4]))
		}
		itemCount := startOffset / 4
		if startOffset%4 != 0 || len(buf) < startOffset {
			return sszutils.ErrorWithPath(sszutils.ErrInvalidListStartOffsetFn(startOffset, len(buf)), "Transactions")
		}
		if itemCount > int(expr1) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr1)), "Transactions")
		}
		val2 = sszutils.ExpandSlice(val2, itemCount)
		for idx1 := range itemCount {
			var endOffset int
			if idx1 < itemCount-1 {
				endOffset = int(binary.LittleEndian.Uint32(buf[(idx1+1)*4 : (idx1+2)*4]))
			} else {
				endOffset = len(buf)
			}
			if endOffset < startOffset || endOffset > len(buf) {
				return sszutils.ErrorWithPathf(sszutils.ErrElementOffsetOutOfRangeFn(endOffset, startOffset, len(buf)), "Transactions[%d]", idx1)
			}
			buf := buf[startOffset:endOffset]
			startOffset = endOffset
			val3 := val2[idx1]
			if len(buf) > int(expr2) {
				return sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(len(buf), int(expr2)), "Transactions[%d]", idx1)
			}
			val3 = sszutils.ExpandSlice(val3, len(buf))
			copy(val3[:], buf)
			val2[idx1] = val3
		}
		t.Transactions = val2
	}
	{ // Field #14 'Withdrawals' (dynamic)
		buf := buf[offset14:]
		val4 := t.Withdrawals
		itemCount := len(buf) / 44
		if len(buf)%44 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 44), "Withdrawals")
		}
		if itemCount > int(expr3) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr3)), "Withdrawals")
		}
		val4 = sszutils.ExpandSlice(val4, itemCount)
		for idx1 := range itemCount {
			if val4[idx1] == nil {
				val4[idx1] = new(capella.Withdrawal)
			}
			buf := buf[44*idx1 : 44*(idx1+1)]
			if err = val4[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
		}
		t.Withdrawals = val4
	}
	return nil
}

func (t *ExecutionPayload) unmarshalSSZView_ExecutionPayload_2(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_EXTRA_DATA_BYTES", 32)
	if err != nil {
		return err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_TRANSACTIONS_PER_PAYLOAD", 1048576)
	if err != nil {
		return err
	}
	expr2, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BYTES_PER_TRANSACTION", 1073741824)
	if err != nil {
		return err
	}
	expr3, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_WITHDRAWALS_PER_PAYLOAD", 16)
	if err != nil {
		return err
	}
	buflen := len(buf)
	if buflen < 540 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 540)
	}
	{ // Field #0 'ParentHash' (static)
		buf := buf[0:32]
		copy(t.ParentHash[:], buf)
	}
	{ // Field #1 'FeeRecipient' (static)
		buf := buf[32:52]
		copy(t.FeeRecipient[:], buf)
	}
	{ // Field #2 'StateRoot' (static)
		buf := buf[52:84]
		copy(t.StateRoot[:], buf)
	}
	{ // Field #3 'ReceiptsRoot' (static)
		buf := buf[84:116]
		copy(t.ReceiptsRoot[:], buf)
	}
	{ // Field #4 'LogsBloom' (static)
		buf := buf[116:372]
		copy(t.LogsBloom[:], buf)
	}
	{ // Field #5 'PrevRandao' (static)
		buf := buf[372:404]
		copy(t.PrevRandao[:], buf)
	}
	{ // Field #6 'BlockNumber' (static)
		buf := buf[404:412]
		t.BlockNumber = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #7 'GasLimit' (static)
		buf := buf[412:420]
		t.GasLimit = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #8 'GasUsed' (static)
		buf := buf[420:428]
		t.GasUsed = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #9 'Timestamp' (static)
		buf := buf[428:436]
		t.Timestamp = binary.LittleEndian.Uint64(buf)
	}
	// Field #10 'ExtraData' (offset)
	offset10 := int(binary.LittleEndian.Uint32(buf[436:440]))
	if offset10 != 540 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset10, 540), "ExtraData:o")
	}
	{ // Field #11 'BaseFeePerGas' (static)
		buf := buf[440:472]
		val1 := t.BaseFeePerGas
		if val1 == nil {
			val1 = new(uint256.Int)
		}
		sszutils.UnmarshalUint64Slice((*val1)[:4], buf)
		t.BaseFeePerGas = val1
	}
	{ // Field #12 'BlockHash' (static)
		buf := buf[472:504]
		copy(t.BlockHash[:], buf)
	}
	// Field #13 'Transactions' (offset)
	offset13 := int(binary.LittleEndian.Uint32(buf[504:508]))
	if offset13 < offset10 || offset13 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset13, offset10, buflen), "Transactions:o")
	}
	// Field #14 'Withdrawals' (offset)
	offset14 := int(binary.LittleEndian.Uint32(buf[508:512]))
	if offset14 < offset13 || offset14 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset14, offset13, buflen), "Withdrawals:o")
	}
	{ // Field #15 'BlobGasUsed' (static)
		buf := buf[512:520]
		t.BlobGasUsed = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #16 'ExcessBlobGas' (static)
		buf := buf[520:528]
		t.ExcessBlobGas = binary.LittleEndian.Uint64(buf)
	}
	// Field #17 'BlockAccessList' (offset)
	offset17 := int(binary.LittleEndian.Uint32(buf[528:532]))
	if offset17 < offset14 || offset17 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset17, offset14, buflen), "BlockAccessList:o")
	}
	{ // Field #18 'SlotNumber' (static)
		buf := buf[532:540]
		t.SlotNumber = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #10 'ExtraData' (dynamic)
		buf := buf[offset10:offset13]
		if len(buf) > int(expr0) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(len(buf), int(expr0)), "ExtraData")
		}
		t.ExtraData = sszutils.ExpandSlice(t.ExtraData, len(buf))
		copy(t.ExtraData[:], buf)
	}
	{ // Field #13 'Transactions' (dynamic)
		buf := buf[offset13:offset14]
		val2 := t.Transactions
		startOffset := int(0)
		if len(buf) != 0 {
			if len(buf) < 4 {
				return sszutils.ErrorWithPath(sszutils.ErrListOffsetsEOFFn(len(buf), 4), "Transactions")
			}
			startOffset = int(binary.LittleEndian.Uint32(buf[0:4]))
		}
		itemCount := startOffset / 4
		if startOffset%4 != 0 || len(buf) < startOffset {
			return sszutils.ErrorWithPath(sszutils.ErrInvalidListStartOffsetFn(startOffset, len(buf)), "Transactions")
		}
		if itemCount > int(expr1) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr1)), "Transactions")
		}
		val2 = sszutils.ExpandSlice(val2, itemCount)
		for idx1 := range itemCount {
			var endOffset int
			if idx1 < itemCount-1 {
				endOffset = int(binary.LittleEndian.Uint32(buf[(idx1+1)*4 : (idx1+2)*4]))
			} else {
				endOffset = len(buf)
			}
			if endOffset < startOffset || endOffset > len(buf) {
				return sszutils.ErrorWithPathf(sszutils.ErrElementOffsetOutOfRangeFn(endOffset, startOffset, len(buf)), "Transactions[%d]", idx1)
			}
			buf := buf[startOffset:endOffset]
			startOffset = endOffset
			val3 := val2[idx1]
			if len(buf) > int(expr2) {
				return sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(len(buf), int(expr2)), "Transactions[%d]", idx1)
			}
			val3 = sszutils.ExpandSlice(val3, len(buf))
			copy(val3[:], buf)
			val2[idx1] = val3
		}
		t.Transactions = val2
	}
	{ // Field #14 'Withdrawals' (dynamic)
		buf := buf[offset14:offset17]
		val4 := t.Withdrawals
		itemCount := len(buf) / 44
		if len(buf)%44 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 44), "Withdrawals")
		}
		if itemCount > int(expr3) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr3)), "Withdrawals")
		}
		val4 = sszutils.ExpandSlice(val4, itemCount)
		for idx1 := range itemCount {
			if val4[idx1] == nil {
				val4[idx1] = new(capella.Withdrawal)
			}
			buf := buf[44*idx1 : 44*(idx1+1)]
			if err = val4[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
		}
		t.Withdrawals = val4
	}
	{ // Field #17 'BlockAccessList' (dynamic)
		buf := buf[offset17:]
		if len(buf) > int(expr2) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(len(buf), int(expr2)), "BlockAccessList")
		}
		t.BlockAccessList = sszutils.ExpandSlice(t.BlockAccessList, len(buf))
		copy(t.BlockAccessList[:], buf)
	}
	return nil
}

func (t *ExecutionPayload) SizeSSZDynView(view any) func(ds sszutils.DynamicSpecs) int {
	switch view.(type) {
	case *bellatrix.ExecutionPayload:
		return t.sizeSSZView_ExecutionPayload
	case *capella.ExecutionPayload:
		return t.sizeSSZView_ExecutionPayload_0
	case *deneb.ExecutionPayload:
		return t.sizeSSZView_ExecutionPayload_1
	case *gloas.ExecutionPayload:
		return t.sizeSSZView_ExecutionPayload_2
	}
	return nil
}
func (t *ExecutionPayload) sizeSSZView_ExecutionPayload(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(ExecutionPayload)
	}
	// Field #0 'ParentHash' static (32 bytes)
	// Field #1 'FeeRecipient' static (20 bytes)
	// Field #2 'StateRoot' static (32 bytes)
	// Field #3 'ReceiptsRoot' static (32 bytes)
	// Field #4 'LogsBloom' static (256 bytes)
	// Field #5 'PrevRandao' static (32 bytes)
	// Field #6 'BlockNumber' static (8 bytes)
	// Field #7 'GasLimit' static (8 bytes)
	// Field #8 'GasUsed' static (8 bytes)
	// Field #9 'Timestamp' static (8 bytes)
	// Field #10 'ExtraData' offset (4 bytes)
	// Field #11 'BaseFeePerGasLE' static (32 bytes)
	// Field #12 'BlockHash' static (32 bytes)
	// Field #13 'Transactions' offset (4 bytes)
	size += 508
	{ // Dynamic field #10 'ExtraData'
		size += len(t.ExtraData)
	}
	{ // Dynamic field #13 'Transactions'
		t := t.Transactions
		vlen := len(t)
		size += vlen * 4 // Offsets
		for i1 := range vlen {
			size += len(t[i1])
		}
	}
	return size
}

func (t *ExecutionPayload) sizeSSZView_ExecutionPayload_0(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(ExecutionPayload)
	}
	// Field #0 'ParentHash' static (32 bytes)
	// Field #1 'FeeRecipient' static (20 bytes)
	// Field #2 'StateRoot' static (32 bytes)
	// Field #3 'ReceiptsRoot' static (32 bytes)
	// Field #4 'LogsBloom' static (256 bytes)
	// Field #5 'PrevRandao' static (32 bytes)
	// Field #6 'BlockNumber' static (8 bytes)
	// Field #7 'GasLimit' static (8 bytes)
	// Field #8 'GasUsed' static (8 bytes)
	// Field #9 'Timestamp' static (8 bytes)
	// Field #10 'ExtraData' offset (4 bytes)
	// Field #11 'BaseFeePerGasLE' static (32 bytes)
	// Field #12 'BlockHash' static (32 bytes)
	// Field #13 'Transactions' offset (4 bytes)
	// Field #14 'Withdrawals' offset (4 bytes)
	size += 512
	{ // Dynamic field #10 'ExtraData'
		size += len(t.ExtraData)
	}
	{ // Dynamic field #13 'Transactions'
		t := t.Transactions
		vlen := len(t)
		size += vlen * 4 // Offsets
		for i1 := range vlen {
			size += len(t[i1])
		}
	}
	{ // Dynamic field #14 'Withdrawals'
		size += len(t.Withdrawals) * 44
	}
	return size
}

func (t *ExecutionPayload) sizeSSZView_ExecutionPayload_1(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(ExecutionPayload)
	}
	// Field #0 'ParentHash' static (32 bytes)
	// Field #1 'FeeRecipient' static (20 bytes)
	// Field #2 'StateRoot' static (32 bytes)
	// Field #3 'ReceiptsRoot' static (32 bytes)
	// Field #4 'LogsBloom' static (256 bytes)
	// Field #5 'PrevRandao' static (32 bytes)
	// Field #6 'BlockNumber' static (8 bytes)
	// Field #7 'GasLimit' static (8 bytes)
	// Field #8 'GasUsed' static (8 bytes)
	// Field #9 'Timestamp' static (8 bytes)
	// Field #10 'ExtraData' offset (4 bytes)
	// Field #11 'BaseFeePerGas' static (32 bytes)
	// Field #12 'BlockHash' static (32 bytes)
	// Field #13 'Transactions' offset (4 bytes)
	// Field #14 'Withdrawals' offset (4 bytes)
	// Field #15 'BlobGasUsed' static (8 bytes)
	// Field #16 'ExcessBlobGas' static (8 bytes)
	size += 528
	{ // Dynamic field #10 'ExtraData'
		size += len(t.ExtraData)
	}
	{ // Dynamic field #13 'Transactions'
		t := t.Transactions
		vlen := len(t)
		size += vlen * 4 // Offsets
		for i1 := range vlen {
			size += len(t[i1])
		}
	}
	{ // Dynamic field #14 'Withdrawals'
		size += len(t.Withdrawals) * 44
	}
	return size
}

func (t *ExecutionPayload) sizeSSZView_ExecutionPayload_2(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(ExecutionPayload)
	}
	// Field #0 'ParentHash' static (32 bytes)
	// Field #1 'FeeRecipient' static (20 bytes)
	// Field #2 'StateRoot' static (32 bytes)
	// Field #3 'ReceiptsRoot' static (32 bytes)
	// Field #4 'LogsBloom' static (256 bytes)
	// Field #5 'PrevRandao' static (32 bytes)
	// Field #6 'BlockNumber' static (8 bytes)
	// Field #7 'GasLimit' static (8 bytes)
	// Field #8 'GasUsed' static (8 bytes)
	// Field #9 'Timestamp' static (8 bytes)
	// Field #10 'ExtraData' offset (4 bytes)
	// Field #11 'BaseFeePerGas' static (32 bytes)
	// Field #12 'BlockHash' static (32 bytes)
	// Field #13 'Transactions' offset (4 bytes)
	// Field #14 'Withdrawals' offset (4 bytes)
	// Field #15 'BlobGasUsed' static (8 bytes)
	// Field #16 'ExcessBlobGas' static (8 bytes)
	// Field #17 'BlockAccessList' offset (4 bytes)
	// Field #18 'SlotNumber' static (8 bytes)
	size += 540
	{ // Dynamic field #10 'ExtraData'
		size += len(t.ExtraData)
	}
	{ // Dynamic field #13 'Transactions'
		t := t.Transactions
		vlen := len(t)
		size += vlen * 4 // Offsets
		for i1 := range vlen {
			size += len(t[i1])
		}
	}
	{ // Dynamic field #14 'Withdrawals'
		size += len(t.Withdrawals) * 44
	}
	{ // Dynamic field #17 'BlockAccessList'
		size += len(t.BlockAccessList)
	}
	return size
}

func (t *ExecutionPayload) HashTreeRootWithDynView(view any) func(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	switch view.(type) {
	case *bellatrix.ExecutionPayload:
		return t.hashTreeRootView_ExecutionPayload
	case *capella.ExecutionPayload:
		return t.hashTreeRootView_ExecutionPayload_0
	case *deneb.ExecutionPayload:
		return t.hashTreeRootView_ExecutionPayload_1
	case *gloas.ExecutionPayload:
		return t.hashTreeRootView_ExecutionPayload_2
	}
	return nil
}
func (t *ExecutionPayload) hashTreeRootView_ExecutionPayload(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_EXTRA_DATA_BYTES", 32)
	if err != nil {
		return err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_TRANSACTIONS_PER_PAYLOAD", 1048576)
	if err != nil {
		return err
	}
	expr2, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BYTES_PER_TRANSACTION", 1073741824)
	if err != nil {
		return err
	}
	if t == nil {
		t = new(ExecutionPayload)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'ParentHash'
		hh.PutBytes(t.ParentHash[:32])
	}
	{ // Field #1 'FeeRecipient'
		hh.PutBytes(t.FeeRecipient[:20])
	}
	{ // Field #2 'StateRoot'
		hh.PutBytes(t.StateRoot[:32])
	}
	{ // Field #3 'ReceiptsRoot'
		hh.PutBytes(t.ReceiptsRoot[:32])
	}
	{ // Field #4 'LogsBloom'
		hh.PutBytes(t.LogsBloom[:256])
	}
	{ // Field #5 'PrevRandao'
		hh.PutBytes(t.PrevRandao[:32])
	}
	{ // Field #6 'BlockNumber'
		hh.PutUint64(t.BlockNumber)
	}
	{ // Field #7 'GasLimit'
		hh.PutUint64(t.GasLimit)
	}
	{ // Field #8 'GasUsed'
		hh.PutUint64(t.GasUsed)
	}
	{ // Field #9 'Timestamp'
		hh.PutUint64(t.Timestamp)
	}
	{ // Field #10 'ExtraData'
		vlen := uint64(len(t.ExtraData))
		if vlen > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "ExtraData")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		hh.AppendBytes32(t.ExtraData[:])
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr0, vlen, 1))
	}
	{ // Field #11 'BaseFeePerGasLE'
		hh.PutBytes(t.BaseFeePerGasLE[:32])
	}
	{ // Field #12 'BlockHash'
		hh.PutBytes(t.BlockHash[:32])
	}
	{ // Field #13 'Transactions'
		t := t.Transactions
		vlen := uint64(len(t))
		if vlen > expr1 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr1), "Transactions")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			vlen := uint64(len(t[idx1]))
			if vlen > expr2 {
				return sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(vlen, expr2), "Transactions[%d]", idx1)
			}
			idx := hh.StartTree(sszutils.TreeTypeBinary)
			hh.AppendBytes32(t[idx1][:])
			hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr2, vlen, 1))
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr1, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}

func (t *ExecutionPayload) hashTreeRootView_ExecutionPayload_0(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_EXTRA_DATA_BYTES", 32)
	if err != nil {
		return err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_TRANSACTIONS_PER_PAYLOAD", 1048576)
	if err != nil {
		return err
	}
	expr2, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BYTES_PER_TRANSACTION", 1073741824)
	if err != nil {
		return err
	}
	expr3, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_WITHDRAWALS_PER_PAYLOAD", 16)
	if err != nil {
		return err
	}
	if t == nil {
		t = new(ExecutionPayload)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'ParentHash'
		hh.PutBytes(t.ParentHash[:32])
	}
	{ // Field #1 'FeeRecipient'
		hh.PutBytes(t.FeeRecipient[:20])
	}
	{ // Field #2 'StateRoot'
		hh.PutBytes(t.StateRoot[:32])
	}
	{ // Field #3 'ReceiptsRoot'
		hh.PutBytes(t.ReceiptsRoot[:32])
	}
	{ // Field #4 'LogsBloom'
		hh.PutBytes(t.LogsBloom[:256])
	}
	{ // Field #5 'PrevRandao'
		hh.PutBytes(t.PrevRandao[:32])
	}
	{ // Field #6 'BlockNumber'
		hh.PutUint64(t.BlockNumber)
	}
	{ // Field #7 'GasLimit'
		hh.PutUint64(t.GasLimit)
	}
	{ // Field #8 'GasUsed'
		hh.PutUint64(t.GasUsed)
	}
	{ // Field #9 'Timestamp'
		hh.PutUint64(t.Timestamp)
	}
	{ // Field #10 'ExtraData'
		vlen := uint64(len(t.ExtraData))
		if vlen > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "ExtraData")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		hh.AppendBytes32(t.ExtraData[:])
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr0, vlen, 1))
	}
	{ // Field #11 'BaseFeePerGasLE'
		hh.PutBytes(t.BaseFeePerGasLE[:32])
	}
	{ // Field #12 'BlockHash'
		hh.PutBytes(t.BlockHash[:32])
	}
	{ // Field #13 'Transactions'
		t := t.Transactions
		vlen := uint64(len(t))
		if vlen > expr1 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr1), "Transactions")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			vlen := uint64(len(t[idx1]))
			if vlen > expr2 {
				return sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(vlen, expr2), "Transactions[%d]", idx1)
			}
			idx := hh.StartTree(sszutils.TreeTypeBinary)
			hh.AppendBytes32(t[idx1][:])
			hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr2, vlen, 1))
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr1, vlen, 32))
	}
	{ // Field #14 'Withdrawals'
		t := t.Withdrawals
		vlen := uint64(len(t))
		if vlen > expr3 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr3), "Withdrawals")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			t := t[idx1]
			if t == nil {
				t = new(capella.Withdrawal)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr3, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}

func (t *ExecutionPayload) hashTreeRootView_ExecutionPayload_1(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_EXTRA_DATA_BYTES", 32)
	if err != nil {
		return err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_TRANSACTIONS_PER_PAYLOAD", 1048576)
	if err != nil {
		return err
	}
	expr2, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BYTES_PER_TRANSACTION", 1073741824)
	if err != nil {
		return err
	}
	expr3, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_WITHDRAWALS_PER_PAYLOAD", 16)
	if err != nil {
		return err
	}
	if t == nil {
		t = new(ExecutionPayload)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'ParentHash'
		hh.PutBytes(t.ParentHash[:32])
	}
	{ // Field #1 'FeeRecipient'
		hh.PutBytes(t.FeeRecipient[:20])
	}
	{ // Field #2 'StateRoot'
		hh.PutBytes(t.StateRoot[:32])
	}
	{ // Field #3 'ReceiptsRoot'
		hh.PutBytes(t.ReceiptsRoot[:32])
	}
	{ // Field #4 'LogsBloom'
		hh.PutBytes(t.LogsBloom[:256])
	}
	{ // Field #5 'PrevRandao'
		hh.PutBytes(t.PrevRandao[:32])
	}
	{ // Field #6 'BlockNumber'
		hh.PutUint64(t.BlockNumber)
	}
	{ // Field #7 'GasLimit'
		hh.PutUint64(t.GasLimit)
	}
	{ // Field #8 'GasUsed'
		hh.PutUint64(t.GasUsed)
	}
	{ // Field #9 'Timestamp'
		hh.PutUint64(t.Timestamp)
	}
	{ // Field #10 'ExtraData'
		vlen := uint64(len(t.ExtraData))
		if vlen > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "ExtraData")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		hh.AppendBytes32(t.ExtraData[:])
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr0, vlen, 1))
	}
	{ // Field #11 'BaseFeePerGas'
		t := t.BaseFeePerGas
		if t == nil {
			t = new(uint256.Int)
		}
		if root, err := t.HashTreeRoot(); err != nil {
			return sszutils.ErrorWithPath(err, "BaseFeePerGas")
		} else {
			hh.AppendBytes32(root[:])
		}
	}
	{ // Field #12 'BlockHash'
		hh.PutBytes(t.BlockHash[:32])
	}
	{ // Field #13 'Transactions'
		t := t.Transactions
		vlen := uint64(len(t))
		if vlen > expr1 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr1), "Transactions")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			vlen := uint64(len(t[idx1]))
			if vlen > expr2 {
				return sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(vlen, expr2), "Transactions[%d]", idx1)
			}
			idx := hh.StartTree(sszutils.TreeTypeBinary)
			hh.AppendBytes32(t[idx1][:])
			hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr2, vlen, 1))
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr1, vlen, 32))
	}
	{ // Field #14 'Withdrawals'
		t := t.Withdrawals
		vlen := uint64(len(t))
		if vlen > expr3 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr3), "Withdrawals")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			t := t[idx1]
			if t == nil {
				t = new(capella.Withdrawal)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr3, vlen, 32))
	}
	{ // Field #15 'BlobGasUsed'
		hh.PutUint64(t.BlobGasUsed)
	}
	{ // Field #16 'ExcessBlobGas'
		hh.PutUint64(t.ExcessBlobGas)
	}
	hh.Merkleize(idx)
	return nil
}

func (t *ExecutionPayload) hashTreeRootView_ExecutionPayload_2(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_EXTRA_DATA_BYTES", 32)
	if err != nil {
		return err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_TRANSACTIONS_PER_PAYLOAD", 1048576)
	if err != nil {
		return err
	}
	expr2, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BYTES_PER_TRANSACTION", 1073741824)
	if err != nil {
		return err
	}
	expr3, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_WITHDRAWALS_PER_PAYLOAD", 16)
	if err != nil {
		return err
	}
	if t == nil {
		t = new(ExecutionPayload)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'ParentHash'
		hh.PutBytes(t.ParentHash[:32])
	}
	{ // Field #1 'FeeRecipient'
		hh.PutBytes(t.FeeRecipient[:20])
	}
	{ // Field #2 'StateRoot'
		hh.PutBytes(t.StateRoot[:32])
	}
	{ // Field #3 'ReceiptsRoot'
		hh.PutBytes(t.ReceiptsRoot[:32])
	}
	{ // Field #4 'LogsBloom'
		hh.PutBytes(t.LogsBloom[:256])
	}
	{ // Field #5 'PrevRandao'
		hh.PutBytes(t.PrevRandao[:32])
	}
	{ // Field #6 'BlockNumber'
		hh.PutUint64(t.BlockNumber)
	}
	{ // Field #7 'GasLimit'
		hh.PutUint64(t.GasLimit)
	}
	{ // Field #8 'GasUsed'
		hh.PutUint64(t.GasUsed)
	}
	{ // Field #9 'Timestamp'
		hh.PutUint64(t.Timestamp)
	}
	{ // Field #10 'ExtraData'
		vlen := uint64(len(t.ExtraData))
		if vlen > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "ExtraData")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		hh.AppendBytes32(t.ExtraData[:])
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr0, vlen, 1))
	}
	{ // Field #11 'BaseFeePerGas'
		t := t.BaseFeePerGas
		if t == nil {
			t = new(uint256.Int)
		}
		if root, err := t.HashTreeRoot(); err != nil {
			return sszutils.ErrorWithPath(err, "BaseFeePerGas")
		} else {
			hh.AppendBytes32(root[:])
		}
	}
	{ // Field #12 'BlockHash'
		hh.PutBytes(t.BlockHash[:32])
	}
	{ // Field #13 'Transactions'
		t := t.Transactions
		vlen := uint64(len(t))
		if vlen > expr1 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr1), "Transactions")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			vlen := uint64(len(t[idx1]))
			if vlen > expr2 {
				return sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(vlen, expr2), "Transactions[%d]", idx1)
			}
			idx := hh.StartTree(sszutils.TreeTypeBinary)
			hh.AppendBytes32(t[idx1][:])
			hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr2, vlen, 1))
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr1, vlen, 32))
	}
	{ // Field #14 'Withdrawals'
		t := t.Withdrawals
		vlen := uint64(len(t))
		if vlen > expr3 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr3), "Withdrawals")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			t := t[idx1]
			if t == nil {
				t = new(capella.Withdrawal)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr3, vlen, 32))
	}
	{ // Field #15 'BlobGasUsed'
		hh.PutUint64(t.BlobGasUsed)
	}
	{ // Field #16 'ExcessBlobGas'
		hh.PutUint64(t.ExcessBlobGas)
	}
	{ // Field #17 'BlockAccessList'
		vlen := uint64(len(t.BlockAccessList))
		if vlen > expr2 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr2), "BlockAccessList")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		hh.AppendBytes32(t.BlockAccessList[:])
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr2, vlen, 1))
	}
	{ // Field #18 'SlotNumber'
		hh.PutUint64(t.SlotNumber)
	}
	hh.Merkleize(idx)
	return nil
}
