// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 6ed1e6ca07b13dfd3c565bf44b7100426a447967f4ccc4c3a41ccce9aa9291ce
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package all

import (
	"encoding/binary"

	"github.com/ethpandaops/go-eth2-client/spec/gloas"
	"github.com/ethpandaops/go-eth2-client/spec/heze"
	"github.com/ethpandaops/go-eth2-client/spec/phase0"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *ExecutionPayloadBid) MarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) ([]byte, error) {
	switch view.(type) {
	case *gloas.ExecutionPayloadBid:
		return t.marshalSSZView_ExecutionPayloadBid
	case *heze.ExecutionPayloadBid:
		return t.marshalSSZView_ExecutionPayloadBid_0
	}
	return nil
}
func (t *ExecutionPayloadBid) marshalSSZView_ExecutionPayloadBid(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK", 4096)
	if err != nil {
		return dst, err
	}
	if t == nil {
		t = new(ExecutionPayloadBid)
	}
	dstlen := len(dst)
	{ // Static Field #0 'ParentBlockHash'
		dst = append(dst, t.ParentBlockHash[:32]...)
	}
	{ // Static Field #1 'ParentBlockRoot'
		dst = append(dst, t.ParentBlockRoot[:32]...)
	}
	{ // Static Field #2 'BlockHash'
		dst = append(dst, t.BlockHash[:32]...)
	}
	{ // Static Field #3 'PrevRandao'
		dst = append(dst, t.PrevRandao[:32]...)
	}
	{ // Static Field #4 'FeeRecipient'
		dst = append(dst, t.FeeRecipient[:20]...)
	}
	{ // Static Field #5 'GasLimit'
		dst = binary.LittleEndian.AppendUint64(dst, t.GasLimit)
	}
	{ // Static Field #6 'BuilderIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.BuilderIndex))
	}
	{ // Static Field #7 'Slot'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.Slot))
	}
	{ // Static Field #8 'Value'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.Value))
	}
	{ // Static Field #9 'ExecutionPayment'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.ExecutionPayment))
	}
	// Offset Field #10 'BlobKZGCommitments'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #11 'ExecutionRequestsRoot'
		dst = append(dst, t.ExecutionRequestsRoot[:32]...)
	}
	{ // Dynamic Field #10 'BlobKZGCommitments'
		binary.LittleEndian.PutUint32(dst[dstlen+188:], uint32(len(dst)-dstlen))
		t := t.BlobKZGCommitments
		vlen := len(t)
		if vlen > int(expr0) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr0)), "BlobKZGCommitments")
		}
		for idx1 := range vlen {
			dst = append(dst, t[idx1][:48]...)
		}
	}
	return dst, nil
}

func (t *ExecutionPayloadBid) marshalSSZView_ExecutionPayloadBid_0(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "INCLUSION_LIST_COMMITTEE_SIZE/8", 2)
	if err != nil {
		return dst, err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK", 4096)
	if err != nil {
		return dst, err
	}
	if t == nil {
		t = new(ExecutionPayloadBid)
	}
	dstlen := len(dst)
	{ // Static Field #0 'ParentBlockHash'
		dst = append(dst, t.ParentBlockHash[:32]...)
	}
	{ // Static Field #1 'ParentBlockRoot'
		dst = append(dst, t.ParentBlockRoot[:32]...)
	}
	{ // Static Field #2 'BlockHash'
		dst = append(dst, t.BlockHash[:32]...)
	}
	{ // Static Field #3 'PrevRandao'
		dst = append(dst, t.PrevRandao[:32]...)
	}
	{ // Static Field #4 'FeeRecipient'
		dst = append(dst, t.FeeRecipient[:20]...)
	}
	{ // Static Field #5 'GasLimit'
		dst = binary.LittleEndian.AppendUint64(dst, t.GasLimit)
	}
	{ // Static Field #6 'BuilderIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.BuilderIndex))
	}
	{ // Static Field #7 'Slot'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.Slot))
	}
	{ // Static Field #8 'Value'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.Value))
	}
	{ // Static Field #9 'ExecutionPayment'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.ExecutionPayment))
	}
	// Offset Field #10 'BlobKZGCommitments'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #11 'ExecutionRequestsRoot'
		dst = append(dst, t.ExecutionRequestsRoot[:32]...)
	}
	{ // Static Field #12 'InclusionListBits'
		vlen := len(t.InclusionListBits)
		if vlen > int(expr0) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, int(expr0)), "InclusionListBits")
		}
		dst = append(dst, t.InclusionListBits[:vlen]...)
		if vlen < int(expr0) {
			dst = sszutils.AppendZeroPadding(dst, (int(expr0)-vlen)*1)
		}
	}
	{ // Dynamic Field #10 'BlobKZGCommitments'
		binary.LittleEndian.PutUint32(dst[dstlen+188:], uint32(len(dst)-dstlen))
		t := t.BlobKZGCommitments
		vlen := len(t)
		if vlen > int(expr1) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr1)), "BlobKZGCommitments")
		}
		for idx1 := range vlen {
			dst = append(dst, t[idx1][:48]...)
		}
	}
	return dst, nil
}

func (t *ExecutionPayloadBid) UnmarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) error {
	switch view.(type) {
	case *gloas.ExecutionPayloadBid:
		return t.unmarshalSSZView_ExecutionPayloadBid
	case *heze.ExecutionPayloadBid:
		return t.unmarshalSSZView_ExecutionPayloadBid_0
	}
	return nil
}
func (t *ExecutionPayloadBid) unmarshalSSZView_ExecutionPayloadBid(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK", 4096)
	if err != nil {
		return err
	}
	buflen := len(buf)
	if buflen < 224 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 224)
	}
	{ // Field #0 'ParentBlockHash' (static)
		buf := buf[0:32]
		copy(t.ParentBlockHash[:], buf)
	}
	{ // Field #1 'ParentBlockRoot' (static)
		buf := buf[32:64]
		copy(t.ParentBlockRoot[:], buf)
	}
	{ // Field #2 'BlockHash' (static)
		buf := buf[64:96]
		copy(t.BlockHash[:], buf)
	}
	{ // Field #3 'PrevRandao' (static)
		buf := buf[96:128]
		copy(t.PrevRandao[:], buf)
	}
	{ // Field #4 'FeeRecipient' (static)
		buf := buf[128:148]
		copy(t.FeeRecipient[:], buf)
	}
	{ // Field #5 'GasLimit' (static)
		buf := buf[148:156]
		t.GasLimit = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #6 'BuilderIndex' (static)
		buf := buf[156:164]
		t.BuilderIndex = gloas.BuilderIndex(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #7 'Slot' (static)
		buf := buf[164:172]
		t.Slot = phase0.Slot(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #8 'Value' (static)
		buf := buf[172:180]
		t.Value = phase0.Gwei(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #9 'ExecutionPayment' (static)
		buf := buf[180:188]
		t.ExecutionPayment = phase0.Gwei(binary.LittleEndian.Uint64(buf))
	}
	// Field #10 'BlobKZGCommitments' (offset)
	offset10 := int(binary.LittleEndian.Uint32(buf[188:192]))
	if offset10 != 224 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset10, 224), "BlobKZGCommitments:o")
	}
	{ // Field #11 'ExecutionRequestsRoot' (static)
		buf := buf[192:224]
		copy(t.ExecutionRequestsRoot[:], buf)
	}
	{ // Field #10 'BlobKZGCommitments' (dynamic)
		buf := buf[offset10:]
		val1 := t.BlobKZGCommitments
		itemCount := len(buf) / 48
		if len(buf)%48 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 48), "BlobKZGCommitments")
		}
		if itemCount > int(expr0) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr0)), "BlobKZGCommitments")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for idx1 := range itemCount {
			buf := buf[48*idx1 : 48*(idx1+1)]
			copy(val1[idx1][:], buf)
		}
		t.BlobKZGCommitments = val1
	}
	return nil
}

func (t *ExecutionPayloadBid) unmarshalSSZView_ExecutionPayloadBid_0(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "INCLUSION_LIST_COMMITTEE_SIZE/8", 2)
	if err != nil {
		return err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK", 4096)
	if err != nil {
		return err
	}
	size1 := 1 * int(expr0)
	exproffset := 0
	totalSize := size1+224
	buflen := len(buf)
	if buflen < totalSize {
		return sszutils.ErrFixedFieldsEOFFn(buflen, totalSize)
	}
	{ // Field #0 'ParentBlockHash' (static)
		buf := buf[0:32]
		copy(t.ParentBlockHash[:], buf)
	}
	{ // Field #1 'ParentBlockRoot' (static)
		buf := buf[32:64]
		copy(t.ParentBlockRoot[:], buf)
	}
	{ // Field #2 'BlockHash' (static)
		buf := buf[64:96]
		copy(t.BlockHash[:], buf)
	}
	{ // Field #3 'PrevRandao' (static)
		buf := buf[96:128]
		copy(t.PrevRandao[:], buf)
	}
	{ // Field #4 'FeeRecipient' (static)
		buf := buf[128:148]
		copy(t.FeeRecipient[:], buf)
	}
	{ // Field #5 'GasLimit' (static)
		buf := buf[148:156]
		t.GasLimit = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #6 'BuilderIndex' (static)
		buf := buf[156:164]
		t.BuilderIndex = gloas.BuilderIndex(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #7 'Slot' (static)
		buf := buf[164:172]
		t.Slot = phase0.Slot(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #8 'Value' (static)
		buf := buf[172:180]
		t.Value = phase0.Gwei(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #9 'ExecutionPayment' (static)
		buf := buf[180:188]
		t.ExecutionPayment = phase0.Gwei(binary.LittleEndian.Uint64(buf))
	}
	// Field #10 'BlobKZGCommitments' (offset)
	offset10 := int(binary.LittleEndian.Uint32(buf[188:192]))
	if offset10 != totalSize {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset10, totalSize), "BlobKZGCommitments:o")
	}
	{ // Field #11 'ExecutionRequestsRoot' (static)
		buf := buf[192:224]
		copy(t.ExecutionRequestsRoot[:], buf)
	}
	{ // Field #12 'InclusionListBits' (static)
		buf := buf[224 : size1+224]
		exproffset += int(size1)
		t.InclusionListBits = sszutils.ExpandSlice(t.InclusionListBits, int(expr0))
		copy(t.InclusionListBits[:], buf)
	}
	{ // Field #10 'BlobKZGCommitments' (dynamic)
		buf := buf[offset10:]
		val1 := t.BlobKZGCommitments
		itemCount := len(buf) / 48
		if len(buf)%48 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 48), "BlobKZGCommitments")
		}
		if itemCount > int(expr1) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr1)), "BlobKZGCommitments")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for idx1 := range itemCount {
			buf := buf[48*idx1 : 48*(idx1+1)]
			copy(val1[idx1][:], buf)
		}
		t.BlobKZGCommitments = val1
	}
	return nil
}

func (t *ExecutionPayloadBid) SizeSSZDynView(view any) func(ds sszutils.DynamicSpecs) int {
	switch view.(type) {
	case *gloas.ExecutionPayloadBid:
		return t.sizeSSZView_ExecutionPayloadBid
	case *heze.ExecutionPayloadBid:
		return t.sizeSSZView_ExecutionPayloadBid_0
	}
	return nil
}
func (t *ExecutionPayloadBid) sizeSSZView_ExecutionPayloadBid(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(ExecutionPayloadBid)
	}
	// Field #0 'ParentBlockHash' static (32 bytes)
	// Field #1 'ParentBlockRoot' static (32 bytes)
	// Field #2 'BlockHash' static (32 bytes)
	// Field #3 'PrevRandao' static (32 bytes)
	// Field #4 'FeeRecipient' static (20 bytes)
	// Field #5 'GasLimit' static (8 bytes)
	// Field #6 'BuilderIndex' static (8 bytes)
	// Field #7 'Slot' static (8 bytes)
	// Field #8 'Value' static (8 bytes)
	// Field #9 'ExecutionPayment' static (8 bytes)
	// Field #10 'BlobKZGCommitments' offset (4 bytes)
	// Field #11 'ExecutionRequestsRoot' static (32 bytes)
	size += 224
	{ // Dynamic field #10 'BlobKZGCommitments'
		size += len(t.BlobKZGCommitments) * 48
	}
	return size
}

func (t *ExecutionPayloadBid) sizeSSZView_ExecutionPayloadBid_0(ds sszutils.DynamicSpecs) (size int) {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "INCLUSION_LIST_COMMITTEE_SIZE/8", 2)
	if err != nil {
		return 0
	}
	if t == nil {
		t = new(ExecutionPayloadBid)
	}
	// Field #0 'ParentBlockHash' static (32 bytes)
	// Field #1 'ParentBlockRoot' static (32 bytes)
	// Field #2 'BlockHash' static (32 bytes)
	// Field #3 'PrevRandao' static (32 bytes)
	// Field #4 'FeeRecipient' static (20 bytes)
	// Field #5 'GasLimit' static (8 bytes)
	// Field #6 'BuilderIndex' static (8 bytes)
	// Field #7 'Slot' static (8 bytes)
	// Field #8 'Value' static (8 bytes)
	// Field #9 'ExecutionPayment' static (8 bytes)
	// Field #10 'BlobKZGCommitments' offset (4 bytes)
	// Field #11 'ExecutionRequestsRoot' static (32 bytes)
	size += 224
	{ // Field #12 'InclusionListBits'
		size += int(expr0)
	}
	{ // Dynamic field #10 'BlobKZGCommitments'
		size += len(t.BlobKZGCommitments) * 48
	}
	return size
}

func (t *ExecutionPayloadBid) HashTreeRootWithDynView(view any) func(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	switch view.(type) {
	case *gloas.ExecutionPayloadBid:
		return t.hashTreeRootView_ExecutionPayloadBid
	case *heze.ExecutionPayloadBid:
		return t.hashTreeRootView_ExecutionPayloadBid_0
	}
	return nil
}
func (t *ExecutionPayloadBid) hashTreeRootView_ExecutionPayloadBid(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK", 4096)
	if err != nil {
		return err
	}
	if t == nil {
		t = new(ExecutionPayloadBid)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'ParentBlockHash'
		hh.PutBytes(t.ParentBlockHash[:32])
	}
	{ // Field #1 'ParentBlockRoot'
		hh.PutBytes(t.ParentBlockRoot[:32])
	}
	{ // Field #2 'BlockHash'
		hh.PutBytes(t.BlockHash[:32])
	}
	{ // Field #3 'PrevRandao'
		hh.PutBytes(t.PrevRandao[:32])
	}
	{ // Field #4 'FeeRecipient'
		hh.PutBytes(t.FeeRecipient[:20])
	}
	{ // Field #5 'GasLimit'
		hh.PutUint64(t.GasLimit)
	}
	{ // Field #6 'BuilderIndex'
		hh.PutUint64(uint64(t.BuilderIndex))
	}
	{ // Field #7 'Slot'
		hh.PutUint64(uint64(t.Slot))
	}
	{ // Field #8 'Value'
		hh.PutUint64(uint64(t.Value))
	}
	{ // Field #9 'ExecutionPayment'
		hh.PutUint64(uint64(t.ExecutionPayment))
	}
	{ // Field #10 'BlobKZGCommitments'
		t := t.BlobKZGCommitments
		vlen := uint64(len(t))
		if vlen > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "BlobKZGCommitments")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			hh.PutBytes(t[idx1][:48])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr0, vlen, 32))
	}
	{ // Field #11 'ExecutionRequestsRoot'
		hh.PutBytes(t.ExecutionRequestsRoot[:32])
	}
	hh.Merkleize(idx)
	return nil
}

func (t *ExecutionPayloadBid) hashTreeRootView_ExecutionPayloadBid_0(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK", 4096)
	if err != nil {
		return err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "INCLUSION_LIST_COMMITTEE_SIZE/8", 2)
	if err != nil {
		return err
	}
	if t == nil {
		t = new(ExecutionPayloadBid)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'ParentBlockHash'
		hh.PutBytes(t.ParentBlockHash[:32])
	}
	{ // Field #1 'ParentBlockRoot'
		hh.PutBytes(t.ParentBlockRoot[:32])
	}
	{ // Field #2 'BlockHash'
		hh.PutBytes(t.BlockHash[:32])
	}
	{ // Field #3 'PrevRandao'
		hh.PutBytes(t.PrevRandao[:32])
	}
	{ // Field #4 'FeeRecipient'
		hh.PutBytes(t.FeeRecipient[:20])
	}
	{ // Field #5 'GasLimit'
		hh.PutUint64(t.GasLimit)
	}
	{ // Field #6 'BuilderIndex'
		hh.PutUint64(uint64(t.BuilderIndex))
	}
	{ // Field #7 'Slot'
		hh.PutUint64(uint64(t.Slot))
	}
	{ // Field #8 'Value'
		hh.PutUint64(uint64(t.Value))
	}
	{ // Field #9 'ExecutionPayment'
		hh.PutUint64(uint64(t.ExecutionPayment))
	}
	{ // Field #10 'BlobKZGCommitments'
		t := t.BlobKZGCommitments
		vlen := uint64(len(t))
		if vlen > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "BlobKZGCommitments")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			hh.PutBytes(t[idx1][:48])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr0, vlen, 32))
	}
	{ // Field #11 'ExecutionRequestsRoot'
		hh.PutBytes(t.ExecutionRequestsRoot[:32])
	}
	{ // Field #12 'InclusionListBits'
		vlen := len(t.InclusionListBits)
		if vlen > int(expr1) {
			return sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, int(expr1)), "InclusionListBits")
		}
		val := t.InclusionListBits[:]
		if vlen < int(expr1) {
			val = sszutils.AppendZeroPadding(val, (int(expr1)-vlen)*1)
		}
		hh.PutBytes(val[:int(expr1)])
	}
	hh.Merkleize(idx)
	return nil
}
