// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 602ad6409f86969f69cd3c7c6c1c228f3c437741fd43a6628522fe3bfd10a452
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package all

import (
	"encoding/binary"

	"github.com/ethpandaops/go-eth2-client/spec/electra"
	"github.com/ethpandaops/go-eth2-client/spec/gloas"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *ExecutionPayloadEnvelope) MarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) ([]byte, error) {
	switch view.(type) {
	case *gloas.ExecutionPayloadEnvelope:
		return t.marshalSSZView_ExecutionPayloadEnvelope
	}
	return nil
}
func (t *ExecutionPayloadEnvelope) marshalSSZView_ExecutionPayloadEnvelope(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(ExecutionPayloadEnvelope)
	}
	dstlen := len(dst)
	// Offset Field #0 'Payload'
	// Offset Field #1 'ExecutionRequests'
	dst = append(dst, 0, 0, 0, 0, 0, 0, 0, 0)
	{ // Static Field #2 'BuilderIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.BuilderIndex))
	}
	{ // Static Field #3 'BeaconBlockRoot'
		dst = append(dst, t.BeaconBlockRoot[:32]...)
	}
	{ // Static Field #4 'ParentBeaconBlockRoot'
		dst = append(dst, t.ParentBeaconBlockRoot[:32]...)
	}
	{ // Dynamic Field #0 'Payload'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.Payload
		if t == nil {
			t = new(ExecutionPayload)
		}
		if viewFn := t.MarshalSSZDynView((*gloas.ExecutionPayload)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	{ // Dynamic Field #1 'ExecutionRequests'
		binary.LittleEndian.PutUint32(dst[dstlen+4:], uint32(len(dst)-dstlen))
		t := t.ExecutionRequests
		if t == nil {
			t = new(electra.ExecutionRequests)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "ExecutionRequests")
		}
	}
	return dst, nil
}

func (t *ExecutionPayloadEnvelope) UnmarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) error {
	switch view.(type) {
	case *gloas.ExecutionPayloadEnvelope:
		return t.unmarshalSSZView_ExecutionPayloadEnvelope
	}
	return nil
}
func (t *ExecutionPayloadEnvelope) unmarshalSSZView_ExecutionPayloadEnvelope(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 80 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 80)
	}
	// Field #0 'Payload' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 80 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 80), "Payload:o")
	}
	// Field #1 'ExecutionRequests' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[4:8]))
	if offset1 < offset0 || offset1 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset1, offset0, buflen), "ExecutionRequests:o")
	}
	{ // Field #2 'BuilderIndex' (static)
		buf := buf[8:16]
		t.BuilderIndex = gloas.BuilderIndex(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #3 'BeaconBlockRoot' (static)
		buf := buf[16:48]
		copy(t.BeaconBlockRoot[:], buf)
	}
	{ // Field #4 'ParentBeaconBlockRoot' (static)
		buf := buf[48:80]
		copy(t.ParentBeaconBlockRoot[:], buf)
	}
	{ // Field #0 'Payload' (dynamic)
		buf := buf[offset0:offset1]
		if t.Payload == nil {
			t.Payload = new(ExecutionPayload)
		}
		if viewFn := t.Payload.UnmarshalSSZDynView((*gloas.ExecutionPayload)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'ExecutionRequests' (dynamic)
		buf := buf[offset1:]
		if t.ExecutionRequests == nil {
			t.ExecutionRequests = new(electra.ExecutionRequests)
		}
		if err = t.ExecutionRequests.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "ExecutionRequests")
		}
	}
	return nil
}

func (t *ExecutionPayloadEnvelope) SizeSSZDynView(view any) func(ds sszutils.DynamicSpecs) int {
	switch view.(type) {
	case *gloas.ExecutionPayloadEnvelope:
		return t.sizeSSZView_ExecutionPayloadEnvelope
	}
	return nil
}
func (t *ExecutionPayloadEnvelope) sizeSSZView_ExecutionPayloadEnvelope(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(ExecutionPayloadEnvelope)
	}
	// Field #0 'Payload' offset (4 bytes)
	// Field #1 'ExecutionRequests' offset (4 bytes)
	// Field #2 'BuilderIndex' static (8 bytes)
	// Field #3 'BeaconBlockRoot' static (32 bytes)
	// Field #4 'ParentBeaconBlockRoot' static (32 bytes)
	size += 80
	{ // Dynamic field #0 'Payload'
		if viewFn := t.Payload.SizeSSZDynView((*gloas.ExecutionPayload)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	{ // Dynamic field #1 'ExecutionRequests'
		size += t.ExecutionRequests.SizeSSZ()
	}
	return size
}

func (t *ExecutionPayloadEnvelope) HashTreeRootWithDynView(view any) func(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	switch view.(type) {
	case *gloas.ExecutionPayloadEnvelope:
		return t.hashTreeRootView_ExecutionPayloadEnvelope
	}
	return nil
}
func (t *ExecutionPayloadEnvelope) hashTreeRootView_ExecutionPayloadEnvelope(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_DEPOSIT_REQUESTS_PER_PAYLOAD", 8192)
	if err != nil {
		return err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_WITHDRAWAL_REQUESTS_PER_PAYLOAD", 16)
	if err != nil {
		return err
	}
	expr2, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_CONSOLIDATION_REQUESTS_PER_PAYLOAD", 2)
	if err != nil {
		return err
	}
	if t == nil {
		t = new(ExecutionPayloadEnvelope)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Payload'
		t := t.Payload
		if t == nil {
			t = new(ExecutionPayload)
		}
		if viewFn := t.HashTreeRootWithDynView((*gloas.ExecutionPayload)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'ExecutionRequests'
		t := t.ExecutionRequests
		if t == nil {
			t = new(electra.ExecutionRequests)
		}
		idx := hh.StartTree(sszutils.TreeTypeNone)
		{ // Field #0 'Deposits'
			t := t.Deposits
			vlen := uint64(len(t))
			if vlen > expr0 {
				return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "ExecutionRequests.Deposits")
			}
			idx := hh.StartTree(sszutils.TreeTypeBinary)
			for idx1 := range int(vlen) {
				t := t[idx1]
				if t == nil {
					t = new(electra.DepositRequest)
				}
				if err := t.HashTreeRootWith(hh); err != nil {
					return sszutils.ErrorWithPathf(err, "ExecutionRequests.Deposits[%d]", idx1)
				}
				if (idx1+1)%256 == 0 {
					hh.Collapse()
				}
			}
			hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr0, vlen, 32))
		}
		{ // Field #1 'Withdrawals'
			t := t.Withdrawals
			vlen := uint64(len(t))
			if vlen > expr1 {
				return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr1), "ExecutionRequests.Withdrawals")
			}
			idx := hh.StartTree(sszutils.TreeTypeBinary)
			for idx1 := range int(vlen) {
				t := t[idx1]
				if t == nil {
					t = new(electra.WithdrawalRequest)
				}
				if err := t.HashTreeRootWith(hh); err != nil {
					return sszutils.ErrorWithPathf(err, "ExecutionRequests.Withdrawals[%d]", idx1)
				}
				if (idx1+1)%256 == 0 {
					hh.Collapse()
				}
			}
			hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr1, vlen, 32))
		}
		{ // Field #2 'Consolidations'
			t := t.Consolidations
			vlen := uint64(len(t))
			if vlen > expr2 {
				return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr2), "ExecutionRequests.Consolidations")
			}
			idx := hh.StartTree(sszutils.TreeTypeBinary)
			for idx1 := range int(vlen) {
				t := t[idx1]
				if t == nil {
					t = new(electra.ConsolidationRequest)
				}
				if err := t.HashTreeRootWith(hh); err != nil {
					return sszutils.ErrorWithPathf(err, "ExecutionRequests.Consolidations[%d]", idx1)
				}
				if (idx1+1)%256 == 0 {
					hh.Collapse()
				}
			}
			hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr2, vlen, 32))
		}
		hh.Merkleize(idx)
	}
	{ // Field #2 'BuilderIndex'
		hh.PutUint64(uint64(t.BuilderIndex))
	}
	{ // Field #3 'BeaconBlockRoot'
		hh.PutBytes(t.BeaconBlockRoot[:32])
	}
	{ // Field #4 'ParentBeaconBlockRoot'
		hh.PutBytes(t.ParentBeaconBlockRoot[:32])
	}
	hh.Merkleize(idx)
	return nil
}
