// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: bfc0c0a7c9f28f74439b61f958914fd917a763d68461c5128d6f9a66ae2d5f57
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package all

import (
	"encoding/binary"

	"github.com/ethpandaops/go-eth2-client/spec/bellatrix"
	"github.com/ethpandaops/go-eth2-client/spec/capella"
	"github.com/ethpandaops/go-eth2-client/spec/deneb"
	"github.com/holiman/uint256"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *ExecutionPayloadHeader) MarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) ([]byte, error) {
	switch view.(type) {
	case *bellatrix.ExecutionPayloadHeader:
		return t.marshalSSZView_ExecutionPayloadHeader
	case *capella.ExecutionPayloadHeader:
		return t.marshalSSZView_ExecutionPayloadHeader_0
	case *deneb.ExecutionPayloadHeader:
		return t.marshalSSZView_ExecutionPayloadHeader_1
	}
	return nil
}
func (t *ExecutionPayloadHeader) marshalSSZView_ExecutionPayloadHeader(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(ExecutionPayloadHeader)
	}
	dstlen := len(dst)
	{ // Static Field #0 'ParentHash'
		dst = append(dst, t.ParentHash[:32]...)
	}
	{ // Static Field #1 'FeeRecipient'
		dst = append(dst, t.FeeRecipient[:20]...)
	}
	{ // Static Field #2 'StateRoot'
		dst = append(dst, t.StateRoot[:32]...)
	}
	{ // Static Field #3 'ReceiptsRoot'
		dst = append(dst, t.ReceiptsRoot[:32]...)
	}
	{ // Static Field #4 'LogsBloom'
		dst = append(dst, t.LogsBloom[:256]...)
	}
	{ // Static Field #5 'PrevRandao'
		dst = append(dst, t.PrevRandao[:32]...)
	}
	{ // Static Field #6 'BlockNumber'
		dst = binary.LittleEndian.AppendUint64(dst, t.BlockNumber)
	}
	{ // Static Field #7 'GasLimit'
		dst = binary.LittleEndian.AppendUint64(dst, t.GasLimit)
	}
	{ // Static Field #8 'GasUsed'
		dst = binary.LittleEndian.AppendUint64(dst, t.GasUsed)
	}
	{ // Static Field #9 'Timestamp'
		dst = binary.LittleEndian.AppendUint64(dst, t.Timestamp)
	}
	// Offset Field #10 'ExtraData'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #11 'BaseFeePerGasLE'
		dst = append(dst, t.BaseFeePerGasLE[:32]...)
	}
	{ // Static Field #12 'BlockHash'
		dst = append(dst, t.BlockHash[:32]...)
	}
	{ // Static Field #13 'TransactionsRoot'
		dst = append(dst, t.TransactionsRoot[:32]...)
	}
	{ // Dynamic Field #10 'ExtraData'
		binary.LittleEndian.PutUint32(dst[dstlen+436:], uint32(len(dst)-dstlen))
		vlen := len(t.ExtraData)
		if vlen > 32 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 32), "ExtraData")
		}
		dst = append(dst, t.ExtraData[:]...)
	}
	return dst, nil
}

func (t *ExecutionPayloadHeader) marshalSSZView_ExecutionPayloadHeader_0(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(ExecutionPayloadHeader)
	}
	dstlen := len(dst)
	{ // Static Field #0 'ParentHash'
		dst = append(dst, t.ParentHash[:32]...)
	}
	{ // Static Field #1 'FeeRecipient'
		dst = append(dst, t.FeeRecipient[:20]...)
	}
	{ // Static Field #2 'StateRoot'
		dst = append(dst, t.StateRoot[:32]...)
	}
	{ // Static Field #3 'ReceiptsRoot'
		dst = append(dst, t.ReceiptsRoot[:32]...)
	}
	{ // Static Field #4 'LogsBloom'
		dst = append(dst, t.LogsBloom[:256]...)
	}
	{ // Static Field #5 'PrevRandao'
		dst = append(dst, t.PrevRandao[:32]...)
	}
	{ // Static Field #6 'BlockNumber'
		dst = binary.LittleEndian.AppendUint64(dst, t.BlockNumber)
	}
	{ // Static Field #7 'GasLimit'
		dst = binary.LittleEndian.AppendUint64(dst, t.GasLimit)
	}
	{ // Static Field #8 'GasUsed'
		dst = binary.LittleEndian.AppendUint64(dst, t.GasUsed)
	}
	{ // Static Field #9 'Timestamp'
		dst = binary.LittleEndian.AppendUint64(dst, t.Timestamp)
	}
	// Offset Field #10 'ExtraData'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #11 'BaseFeePerGasLE'
		dst = append(dst, t.BaseFeePerGasLE[:32]...)
	}
	{ // Static Field #12 'BlockHash'
		dst = append(dst, t.BlockHash[:32]...)
	}
	{ // Static Field #13 'TransactionsRoot'
		dst = append(dst, t.TransactionsRoot[:32]...)
	}
	{ // Static Field #14 'WithdrawalsRoot'
		dst = append(dst, t.WithdrawalsRoot[:32]...)
	}
	{ // Dynamic Field #10 'ExtraData'
		binary.LittleEndian.PutUint32(dst[dstlen+436:], uint32(len(dst)-dstlen))
		vlen := len(t.ExtraData)
		if vlen > 32 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 32), "ExtraData")
		}
		dst = append(dst, t.ExtraData[:]...)
	}
	return dst, nil
}

func (t *ExecutionPayloadHeader) marshalSSZView_ExecutionPayloadHeader_1(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(ExecutionPayloadHeader)
	}
	dstlen := len(dst)
	{ // Static Field #0 'ParentHash'
		dst = append(dst, t.ParentHash[:32]...)
	}
	{ // Static Field #1 'FeeRecipient'
		dst = append(dst, t.FeeRecipient[:20]...)
	}
	{ // Static Field #2 'StateRoot'
		dst = append(dst, t.StateRoot[:32]...)
	}
	{ // Static Field #3 'ReceiptsRoot'
		dst = append(dst, t.ReceiptsRoot[:32]...)
	}
	{ // Static Field #4 'LogsBloom'
		dst = append(dst, t.LogsBloom[:256]...)
	}
	{ // Static Field #5 'PrevRandao'
		dst = append(dst, t.PrevRandao[:32]...)
	}
	{ // Static Field #6 'BlockNumber'
		dst = binary.LittleEndian.AppendUint64(dst, t.BlockNumber)
	}
	{ // Static Field #7 'GasLimit'
		dst = binary.LittleEndian.AppendUint64(dst, t.GasLimit)
	}
	{ // Static Field #8 'GasUsed'
		dst = binary.LittleEndian.AppendUint64(dst, t.GasUsed)
	}
	{ // Static Field #9 'Timestamp'
		dst = binary.LittleEndian.AppendUint64(dst, t.Timestamp)
	}
	// Offset Field #10 'ExtraData'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #11 'BaseFeePerGas'
		t := t.BaseFeePerGas
		if t == nil {
			t = new(uint256.Int)
		}
		dst = sszutils.MarshalUint64Slice(dst, (*t)[:4])
	}
	{ // Static Field #12 'BlockHash'
		dst = append(dst, t.BlockHash[:32]...)
	}
	{ // Static Field #13 'TransactionsRoot'
		dst = append(dst, t.TransactionsRoot[:32]...)
	}
	{ // Static Field #14 'WithdrawalsRoot'
		dst = append(dst, t.WithdrawalsRoot[:32]...)
	}
	{ // Static Field #15 'BlobGasUsed'
		dst = binary.LittleEndian.AppendUint64(dst, t.BlobGasUsed)
	}
	{ // Static Field #16 'ExcessBlobGas'
		dst = binary.LittleEndian.AppendUint64(dst, t.ExcessBlobGas)
	}
	{ // Dynamic Field #10 'ExtraData'
		binary.LittleEndian.PutUint32(dst[dstlen+436:], uint32(len(dst)-dstlen))
		vlen := len(t.ExtraData)
		if vlen > 32 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 32), "ExtraData")
		}
		dst = append(dst, t.ExtraData[:]...)
	}
	return dst, nil
}

func (t *ExecutionPayloadHeader) UnmarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) error {
	switch view.(type) {
	case *bellatrix.ExecutionPayloadHeader:
		return t.unmarshalSSZView_ExecutionPayloadHeader
	case *capella.ExecutionPayloadHeader:
		return t.unmarshalSSZView_ExecutionPayloadHeader_0
	case *deneb.ExecutionPayloadHeader:
		return t.unmarshalSSZView_ExecutionPayloadHeader_1
	}
	return nil
}
func (t *ExecutionPayloadHeader) unmarshalSSZView_ExecutionPayloadHeader(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 536 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 536)
	}
	{ // Field #0 'ParentHash' (static)
		buf := buf[0:32]
		copy(t.ParentHash[:], buf)
	}
	{ // Field #1 'FeeRecipient' (static)
		buf := buf[32:52]
		copy(t.FeeRecipient[:], buf)
	}
	{ // Field #2 'StateRoot' (static)
		buf := buf[52:84]
		copy(t.StateRoot[:], buf)
	}
	{ // Field #3 'ReceiptsRoot' (static)
		buf := buf[84:116]
		copy(t.ReceiptsRoot[:], buf)
	}
	{ // Field #4 'LogsBloom' (static)
		buf := buf[116:372]
		copy(t.LogsBloom[:], buf)
	}
	{ // Field #5 'PrevRandao' (static)
		buf := buf[372:404]
		copy(t.PrevRandao[:], buf)
	}
	{ // Field #6 'BlockNumber' (static)
		buf := buf[404:412]
		t.BlockNumber = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #7 'GasLimit' (static)
		buf := buf[412:420]
		t.GasLimit = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #8 'GasUsed' (static)
		buf := buf[420:428]
		t.GasUsed = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #9 'Timestamp' (static)
		buf := buf[428:436]
		t.Timestamp = binary.LittleEndian.Uint64(buf)
	}
	// Field #10 'ExtraData' (offset)
	offset10 := int(binary.LittleEndian.Uint32(buf[436:440]))
	if offset10 != 536 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset10, 536), "ExtraData:o")
	}
	{ // Field #11 'BaseFeePerGasLE' (static)
		buf := buf[440:472]
		copy(t.BaseFeePerGasLE[:], buf)
	}
	{ // Field #12 'BlockHash' (static)
		buf := buf[472:504]
		copy(t.BlockHash[:], buf)
	}
	{ // Field #13 'TransactionsRoot' (static)
		buf := buf[504:536]
		copy(t.TransactionsRoot[:], buf)
	}
	{ // Field #10 'ExtraData' (dynamic)
		buf := buf[offset10:]
		if len(buf) > 32 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(len(buf), 32), "ExtraData")
		}
		t.ExtraData = sszutils.ExpandSlice(t.ExtraData, len(buf))
		copy(t.ExtraData[:], buf)
	}
	return nil
}

func (t *ExecutionPayloadHeader) unmarshalSSZView_ExecutionPayloadHeader_0(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 568 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 568)
	}
	{ // Field #0 'ParentHash' (static)
		buf := buf[0:32]
		copy(t.ParentHash[:], buf)
	}
	{ // Field #1 'FeeRecipient' (static)
		buf := buf[32:52]
		copy(t.FeeRecipient[:], buf)
	}
	{ // Field #2 'StateRoot' (static)
		buf := buf[52:84]
		copy(t.StateRoot[:], buf)
	}
	{ // Field #3 'ReceiptsRoot' (static)
		buf := buf[84:116]
		copy(t.ReceiptsRoot[:], buf)
	}
	{ // Field #4 'LogsBloom' (static)
		buf := buf[116:372]
		copy(t.LogsBloom[:], buf)
	}
	{ // Field #5 'PrevRandao' (static)
		buf := buf[372:404]
		copy(t.PrevRandao[:], buf)
	}
	{ // Field #6 'BlockNumber' (static)
		buf := buf[404:412]
		t.BlockNumber = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #7 'GasLimit' (static)
		buf := buf[412:420]
		t.GasLimit = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #8 'GasUsed' (static)
		buf := buf[420:428]
		t.GasUsed = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #9 'Timestamp' (static)
		buf := buf[428:436]
		t.Timestamp = binary.LittleEndian.Uint64(buf)
	}
	// Field #10 'ExtraData' (offset)
	offset10 := int(binary.LittleEndian.Uint32(buf[436:440]))
	if offset10 != 568 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset10, 568), "ExtraData:o")
	}
	{ // Field #11 'BaseFeePerGasLE' (static)
		buf := buf[440:472]
		copy(t.BaseFeePerGasLE[:], buf)
	}
	{ // Field #12 'BlockHash' (static)
		buf := buf[472:504]
		copy(t.BlockHash[:], buf)
	}
	{ // Field #13 'TransactionsRoot' (static)
		buf := buf[504:536]
		copy(t.TransactionsRoot[:], buf)
	}
	{ // Field #14 'WithdrawalsRoot' (static)
		buf := buf[536:568]
		copy(t.WithdrawalsRoot[:], buf)
	}
	{ // Field #10 'ExtraData' (dynamic)
		buf := buf[offset10:]
		if len(buf) > 32 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(len(buf), 32), "ExtraData")
		}
		t.ExtraData = sszutils.ExpandSlice(t.ExtraData, len(buf))
		copy(t.ExtraData[:], buf)
	}
	return nil
}

func (t *ExecutionPayloadHeader) unmarshalSSZView_ExecutionPayloadHeader_1(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 584 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 584)
	}
	{ // Field #0 'ParentHash' (static)
		buf := buf[0:32]
		copy(t.ParentHash[:], buf)
	}
	{ // Field #1 'FeeRecipient' (static)
		buf := buf[32:52]
		copy(t.FeeRecipient[:], buf)
	}
	{ // Field #2 'StateRoot' (static)
		buf := buf[52:84]
		copy(t.StateRoot[:], buf)
	}
	{ // Field #3 'ReceiptsRoot' (static)
		buf := buf[84:116]
		copy(t.ReceiptsRoot[:], buf)
	}
	{ // Field #4 'LogsBloom' (static)
		buf := buf[116:372]
		copy(t.LogsBloom[:], buf)
	}
	{ // Field #5 'PrevRandao' (static)
		buf := buf[372:404]
		copy(t.PrevRandao[:], buf)
	}
	{ // Field #6 'BlockNumber' (static)
		buf := buf[404:412]
		t.BlockNumber = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #7 'GasLimit' (static)
		buf := buf[412:420]
		t.GasLimit = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #8 'GasUsed' (static)
		buf := buf[420:428]
		t.GasUsed = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #9 'Timestamp' (static)
		buf := buf[428:436]
		t.Timestamp = binary.LittleEndian.Uint64(buf)
	}
	// Field #10 'ExtraData' (offset)
	offset10 := int(binary.LittleEndian.Uint32(buf[436:440]))
	if offset10 != 584 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset10, 584), "ExtraData:o")
	}
	{ // Field #11 'BaseFeePerGas' (static)
		buf := buf[440:472]
		val1 := t.BaseFeePerGas
		if val1 == nil {
			val1 = new(uint256.Int)
		}
		sszutils.UnmarshalUint64Slice((*val1)[:4], buf)
		t.BaseFeePerGas = val1
	}
	{ // Field #12 'BlockHash' (static)
		buf := buf[472:504]
		copy(t.BlockHash[:], buf)
	}
	{ // Field #13 'TransactionsRoot' (static)
		buf := buf[504:536]
		copy(t.TransactionsRoot[:], buf)
	}
	{ // Field #14 'WithdrawalsRoot' (static)
		buf := buf[536:568]
		copy(t.WithdrawalsRoot[:], buf)
	}
	{ // Field #15 'BlobGasUsed' (static)
		buf := buf[568:576]
		t.BlobGasUsed = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #16 'ExcessBlobGas' (static)
		buf := buf[576:584]
		t.ExcessBlobGas = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #10 'ExtraData' (dynamic)
		buf := buf[offset10:]
		if len(buf) > 32 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(len(buf), 32), "ExtraData")
		}
		t.ExtraData = sszutils.ExpandSlice(t.ExtraData, len(buf))
		copy(t.ExtraData[:], buf)
	}
	return nil
}

func (t *ExecutionPayloadHeader) SizeSSZDynView(view any) func(ds sszutils.DynamicSpecs) int {
	switch view.(type) {
	case *bellatrix.ExecutionPayloadHeader:
		return t.sizeSSZView_ExecutionPayloadHeader
	case *capella.ExecutionPayloadHeader:
		return t.sizeSSZView_ExecutionPayloadHeader_0
	case *deneb.ExecutionPayloadHeader:
		return t.sizeSSZView_ExecutionPayloadHeader_1
	}
	return nil
}
func (t *ExecutionPayloadHeader) sizeSSZView_ExecutionPayloadHeader(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(ExecutionPayloadHeader)
	}
	// Field #0 'ParentHash' static (32 bytes)
	// Field #1 'FeeRecipient' static (20 bytes)
	// Field #2 'StateRoot' static (32 bytes)
	// Field #3 'ReceiptsRoot' static (32 bytes)
	// Field #4 'LogsBloom' static (256 bytes)
	// Field #5 'PrevRandao' static (32 bytes)
	// Field #6 'BlockNumber' static (8 bytes)
	// Field #7 'GasLimit' static (8 bytes)
	// Field #8 'GasUsed' static (8 bytes)
	// Field #9 'Timestamp' static (8 bytes)
	// Field #10 'ExtraData' offset (4 bytes)
	// Field #11 'BaseFeePerGasLE' static (32 bytes)
	// Field #12 'BlockHash' static (32 bytes)
	// Field #13 'TransactionsRoot' static (32 bytes)
	size += 536
	{ // Dynamic field #10 'ExtraData'
		size += len(t.ExtraData)
	}
	return size
}

func (t *ExecutionPayloadHeader) sizeSSZView_ExecutionPayloadHeader_0(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(ExecutionPayloadHeader)
	}
	// Field #0 'ParentHash' static (32 bytes)
	// Field #1 'FeeRecipient' static (20 bytes)
	// Field #2 'StateRoot' static (32 bytes)
	// Field #3 'ReceiptsRoot' static (32 bytes)
	// Field #4 'LogsBloom' static (256 bytes)
	// Field #5 'PrevRandao' static (32 bytes)
	// Field #6 'BlockNumber' static (8 bytes)
	// Field #7 'GasLimit' static (8 bytes)
	// Field #8 'GasUsed' static (8 bytes)
	// Field #9 'Timestamp' static (8 bytes)
	// Field #10 'ExtraData' offset (4 bytes)
	// Field #11 'BaseFeePerGasLE' static (32 bytes)
	// Field #12 'BlockHash' static (32 bytes)
	// Field #13 'TransactionsRoot' static (32 bytes)
	// Field #14 'WithdrawalsRoot' static (32 bytes)
	size += 568
	{ // Dynamic field #10 'ExtraData'
		size += len(t.ExtraData)
	}
	return size
}

func (t *ExecutionPayloadHeader) sizeSSZView_ExecutionPayloadHeader_1(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(ExecutionPayloadHeader)
	}
	// Field #0 'ParentHash' static (32 bytes)
	// Field #1 'FeeRecipient' static (20 bytes)
	// Field #2 'StateRoot' static (32 bytes)
	// Field #3 'ReceiptsRoot' static (32 bytes)
	// Field #4 'LogsBloom' static (256 bytes)
	// Field #5 'PrevRandao' static (32 bytes)
	// Field #6 'BlockNumber' static (8 bytes)
	// Field #7 'GasLimit' static (8 bytes)
	// Field #8 'GasUsed' static (8 bytes)
	// Field #9 'Timestamp' static (8 bytes)
	// Field #10 'ExtraData' offset (4 bytes)
	// Field #11 'BaseFeePerGas' static (32 bytes)
	// Field #12 'BlockHash' static (32 bytes)
	// Field #13 'TransactionsRoot' static (32 bytes)
	// Field #14 'WithdrawalsRoot' static (32 bytes)
	// Field #15 'BlobGasUsed' static (8 bytes)
	// Field #16 'ExcessBlobGas' static (8 bytes)
	size += 584
	{ // Dynamic field #10 'ExtraData'
		size += len(t.ExtraData)
	}
	return size
}

func (t *ExecutionPayloadHeader) HashTreeRootWithDynView(view any) func(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	switch view.(type) {
	case *bellatrix.ExecutionPayloadHeader:
		return t.hashTreeRootView_ExecutionPayloadHeader
	case *capella.ExecutionPayloadHeader:
		return t.hashTreeRootView_ExecutionPayloadHeader_0
	case *deneb.ExecutionPayloadHeader:
		return t.hashTreeRootView_ExecutionPayloadHeader_1
	}
	return nil
}
func (t *ExecutionPayloadHeader) hashTreeRootView_ExecutionPayloadHeader(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(ExecutionPayloadHeader)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'ParentHash'
		hh.PutBytes(t.ParentHash[:32])
	}
	{ // Field #1 'FeeRecipient'
		hh.PutBytes(t.FeeRecipient[:20])
	}
	{ // Field #2 'StateRoot'
		hh.PutBytes(t.StateRoot[:32])
	}
	{ // Field #3 'ReceiptsRoot'
		hh.PutBytes(t.ReceiptsRoot[:32])
	}
	{ // Field #4 'LogsBloom'
		hh.PutBytes(t.LogsBloom[:256])
	}
	{ // Field #5 'PrevRandao'
		hh.PutBytes(t.PrevRandao[:32])
	}
	{ // Field #6 'BlockNumber'
		hh.PutUint64(t.BlockNumber)
	}
	{ // Field #7 'GasLimit'
		hh.PutUint64(t.GasLimit)
	}
	{ // Field #8 'GasUsed'
		hh.PutUint64(t.GasUsed)
	}
	{ // Field #9 'Timestamp'
		hh.PutUint64(t.Timestamp)
	}
	{ // Field #10 'ExtraData'
		vlen := uint64(len(t.ExtraData))
		if vlen > 32 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 32), "ExtraData")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		hh.AppendBytes32(t.ExtraData[:])
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(32, vlen, 1))
	}
	{ // Field #11 'BaseFeePerGasLE'
		hh.PutBytes(t.BaseFeePerGasLE[:32])
	}
	{ // Field #12 'BlockHash'
		hh.PutBytes(t.BlockHash[:32])
	}
	{ // Field #13 'TransactionsRoot'
		hh.PutBytes(t.TransactionsRoot[:32])
	}
	hh.Merkleize(idx)
	return nil
}

func (t *ExecutionPayloadHeader) hashTreeRootView_ExecutionPayloadHeader_0(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(ExecutionPayloadHeader)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'ParentHash'
		hh.PutBytes(t.ParentHash[:32])
	}
	{ // Field #1 'FeeRecipient'
		hh.PutBytes(t.FeeRecipient[:20])
	}
	{ // Field #2 'StateRoot'
		hh.PutBytes(t.StateRoot[:32])
	}
	{ // Field #3 'ReceiptsRoot'
		hh.PutBytes(t.ReceiptsRoot[:32])
	}
	{ // Field #4 'LogsBloom'
		hh.PutBytes(t.LogsBloom[:256])
	}
	{ // Field #5 'PrevRandao'
		hh.PutBytes(t.PrevRandao[:32])
	}
	{ // Field #6 'BlockNumber'
		hh.PutUint64(t.BlockNumber)
	}
	{ // Field #7 'GasLimit'
		hh.PutUint64(t.GasLimit)
	}
	{ // Field #8 'GasUsed'
		hh.PutUint64(t.GasUsed)
	}
	{ // Field #9 'Timestamp'
		hh.PutUint64(t.Timestamp)
	}
	{ // Field #10 'ExtraData'
		vlen := uint64(len(t.ExtraData))
		if vlen > 32 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 32), "ExtraData")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		hh.AppendBytes32(t.ExtraData[:])
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(32, vlen, 1))
	}
	{ // Field #11 'BaseFeePerGasLE'
		hh.PutBytes(t.BaseFeePerGasLE[:32])
	}
	{ // Field #12 'BlockHash'
		hh.PutBytes(t.BlockHash[:32])
	}
	{ // Field #13 'TransactionsRoot'
		hh.PutBytes(t.TransactionsRoot[:32])
	}
	{ // Field #14 'WithdrawalsRoot'
		hh.PutBytes(t.WithdrawalsRoot[:32])
	}
	hh.Merkleize(idx)
	return nil
}

func (t *ExecutionPayloadHeader) hashTreeRootView_ExecutionPayloadHeader_1(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(ExecutionPayloadHeader)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'ParentHash'
		hh.PutBytes(t.ParentHash[:32])
	}
	{ // Field #1 'FeeRecipient'
		hh.PutBytes(t.FeeRecipient[:20])
	}
	{ // Field #2 'StateRoot'
		hh.PutBytes(t.StateRoot[:32])
	}
	{ // Field #3 'ReceiptsRoot'
		hh.PutBytes(t.ReceiptsRoot[:32])
	}
	{ // Field #4 'LogsBloom'
		hh.PutBytes(t.LogsBloom[:256])
	}
	{ // Field #5 'PrevRandao'
		hh.PutBytes(t.PrevRandao[:32])
	}
	{ // Field #6 'BlockNumber'
		hh.PutUint64(t.BlockNumber)
	}
	{ // Field #7 'GasLimit'
		hh.PutUint64(t.GasLimit)
	}
	{ // Field #8 'GasUsed'
		hh.PutUint64(t.GasUsed)
	}
	{ // Field #9 'Timestamp'
		hh.PutUint64(t.Timestamp)
	}
	{ // Field #10 'ExtraData'
		vlen := uint64(len(t.ExtraData))
		if vlen > 32 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 32), "ExtraData")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		hh.AppendBytes32(t.ExtraData[:])
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(32, vlen, 1))
	}
	{ // Field #11 'BaseFeePerGas'
		t := t.BaseFeePerGas
		if t == nil {
			t = new(uint256.Int)
		}
		if root, err := t.HashTreeRoot(); err != nil {
			return sszutils.ErrorWithPath(err, "BaseFeePerGas")
		} else {
			hh.AppendBytes32(root[:])
		}
	}
	{ // Field #12 'BlockHash'
		hh.PutBytes(t.BlockHash[:32])
	}
	{ // Field #13 'TransactionsRoot'
		hh.PutBytes(t.TransactionsRoot[:32])
	}
	{ // Field #14 'WithdrawalsRoot'
		hh.PutBytes(t.WithdrawalsRoot[:32])
	}
	{ // Field #15 'BlobGasUsed'
		hh.PutUint64(t.BlobGasUsed)
	}
	{ // Field #16 'ExcessBlobGas'
		hh.PutUint64(t.ExcessBlobGas)
	}
	hh.Merkleize(idx)
	return nil
}
