// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: ee070c6d3d5d1b12f85a0e9e8337145652f6004e22aad755b307d8e518bb7960
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package all

import (
	"encoding/binary"

	"github.com/ethpandaops/go-eth2-client/spec/electra"
	"github.com/ethpandaops/go-eth2-client/spec/phase0"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *IndexedAttestation) MarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) ([]byte, error) {
	switch view.(type) {
	case *phase0.IndexedAttestation:
		return t.marshalSSZView_IndexedAttestation
	case *electra.IndexedAttestation:
		return t.marshalSSZView_IndexedAttestation_0
	}
	return nil
}
func (t *IndexedAttestation) marshalSSZView_IndexedAttestation(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(IndexedAttestation)
	}
	dstlen := len(dst)
	// Offset Field #0 'AttestingIndices'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'Data'
		t := t.Data
		if t == nil {
			t = new(phase0.AttestationData)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "Data")
		}
	}
	{ // Static Field #2 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	{ // Dynamic Field #0 'AttestingIndices'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.AttestingIndices
		vlen := len(t)
		if vlen > 2048 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 2048), "AttestingIndices")
		}
		dst = sszutils.MarshalUint64Slice(dst, t[:vlen])
	}
	return dst, nil
}

func (t *IndexedAttestation) marshalSSZView_IndexedAttestation_0(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_VALIDATORS_PER_COMMITTEE*MAX_COMMITTEES_PER_SLOT", 131072)
	if err != nil {
		return dst, err
	}
	if t == nil {
		t = new(IndexedAttestation)
	}
	dstlen := len(dst)
	// Offset Field #0 'AttestingIndices'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'Data'
		t := t.Data
		if t == nil {
			t = new(phase0.AttestationData)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "Data")
		}
	}
	{ // Static Field #2 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	{ // Dynamic Field #0 'AttestingIndices'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.AttestingIndices
		vlen := len(t)
		if vlen > int(expr0) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr0)), "AttestingIndices")
		}
		dst = sszutils.MarshalUint64Slice(dst, t[:vlen])
	}
	return dst, nil
}

func (t *IndexedAttestation) UnmarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) error {
	switch view.(type) {
	case *phase0.IndexedAttestation:
		return t.unmarshalSSZView_IndexedAttestation
	case *electra.IndexedAttestation:
		return t.unmarshalSSZView_IndexedAttestation_0
	}
	return nil
}
func (t *IndexedAttestation) unmarshalSSZView_IndexedAttestation(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 228 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 228)
	}
	// Field #0 'AttestingIndices' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 228 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 228), "AttestingIndices:o")
	}
	{ // Field #1 'Data' (static)
		buf := buf[4:132]
		if t.Data == nil {
			t.Data = new(phase0.AttestationData)
		}
		if err = t.Data.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "Data")
		}
	}
	{ // Field #2 'Signature' (static)
		buf := buf[132:228]
		copy(t.Signature[:], buf)
	}
	{ // Field #0 'AttestingIndices' (dynamic)
		buf := buf[offset0:]
		val1 := t.AttestingIndices
		itemCount := len(buf) / 8
		if len(buf)%8 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 8), "AttestingIndices")
		}
		if itemCount > 2048 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 2048), "AttestingIndices")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		sszutils.UnmarshalUint64Slice(val1, buf)
		t.AttestingIndices = val1
	}
	return nil
}

func (t *IndexedAttestation) unmarshalSSZView_IndexedAttestation_0(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_VALIDATORS_PER_COMMITTEE*MAX_COMMITTEES_PER_SLOT", 131072)
	if err != nil {
		return err
	}
	buflen := len(buf)
	if buflen < 228 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 228)
	}
	// Field #0 'AttestingIndices' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 228 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 228), "AttestingIndices:o")
	}
	{ // Field #1 'Data' (static)
		buf := buf[4:132]
		if t.Data == nil {
			t.Data = new(phase0.AttestationData)
		}
		if err = t.Data.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "Data")
		}
	}
	{ // Field #2 'Signature' (static)
		buf := buf[132:228]
		copy(t.Signature[:], buf)
	}
	{ // Field #0 'AttestingIndices' (dynamic)
		buf := buf[offset0:]
		val1 := t.AttestingIndices
		itemCount := len(buf) / 8
		if len(buf)%8 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 8), "AttestingIndices")
		}
		if itemCount > int(expr0) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr0)), "AttestingIndices")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		sszutils.UnmarshalUint64Slice(val1, buf)
		t.AttestingIndices = val1
	}
	return nil
}

func (t *IndexedAttestation) SizeSSZDynView(view any) func(ds sszutils.DynamicSpecs) int {
	switch view.(type) {
	case *phase0.IndexedAttestation:
		return t.sizeSSZView_IndexedAttestation
	case *electra.IndexedAttestation:
		return t.sizeSSZView_IndexedAttestation_0
	}
	return nil
}
func (t *IndexedAttestation) sizeSSZView_IndexedAttestation(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(IndexedAttestation)
	}
	// Field #0 'AttestingIndices' offset (4 bytes)
	// Field #1 'Data' static (128 bytes)
	// Field #2 'Signature' static (96 bytes)
	size += 228
	{ // Dynamic field #0 'AttestingIndices'
		size += len(t.AttestingIndices) * 8
	}
	return size
}

func (t *IndexedAttestation) sizeSSZView_IndexedAttestation_0(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(IndexedAttestation)
	}
	// Field #0 'AttestingIndices' offset (4 bytes)
	// Field #1 'Data' static (128 bytes)
	// Field #2 'Signature' static (96 bytes)
	size += 228
	{ // Dynamic field #0 'AttestingIndices'
		size += len(t.AttestingIndices) * 8
	}
	return size
}

func (t *IndexedAttestation) HashTreeRootWithDynView(view any) func(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	switch view.(type) {
	case *phase0.IndexedAttestation:
		return t.hashTreeRootView_IndexedAttestation
	case *electra.IndexedAttestation:
		return t.hashTreeRootView_IndexedAttestation_0
	}
	return nil
}
func (t *IndexedAttestation) hashTreeRootView_IndexedAttestation(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(IndexedAttestation)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'AttestingIndices'
		t := t.AttestingIndices
		vlen := uint64(len(t))
		if vlen > 2048 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 2048), "AttestingIndices")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		sszutils.HashUint64Slice(hh, t)
		hh.FillUpTo32()
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(2048, vlen, 8))
	}
	{ // Field #1 'Data'
		t := t.Data
		if t == nil {
			t = new(phase0.AttestationData)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "Data")
		}
	}
	{ // Field #2 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}

func (t *IndexedAttestation) hashTreeRootView_IndexedAttestation_0(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_VALIDATORS_PER_COMMITTEE*MAX_COMMITTEES_PER_SLOT", 131072)
	if err != nil {
		return err
	}
	if t == nil {
		t = new(IndexedAttestation)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'AttestingIndices'
		t := t.AttestingIndices
		vlen := uint64(len(t))
		if vlen > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "AttestingIndices")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		sszutils.HashUint64Slice(hh, t)
		hh.FillUpTo32()
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr0, vlen, 8))
	}
	{ // Field #1 'Data'
		t := t.Data
		if t == nil {
			t = new(phase0.AttestationData)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "Data")
		}
	}
	{ // Field #2 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}
