// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 65665b6f3d33f6eccd2d859bd7004c2adb4dda723b75131467345e83c01af67c
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package all

import (
	"encoding/binary"

	"github.com/ethpandaops/go-eth2-client/spec/gloas"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *SignedExecutionPayloadEnvelope) MarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) ([]byte, error) {
	switch view.(type) {
	case *gloas.SignedExecutionPayloadEnvelope:
		return t.marshalSSZView_SignedExecutionPayloadEnvelope
	}
	return nil
}
func (t *SignedExecutionPayloadEnvelope) marshalSSZView_SignedExecutionPayloadEnvelope(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(SignedExecutionPayloadEnvelope)
	}
	dstlen := len(dst)
	// Offset Field #0 'Message'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	{ // Dynamic Field #0 'Message'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.Message
		if t == nil {
			t = new(ExecutionPayloadEnvelope)
		}
		if viewFn := t.MarshalSSZDynView((*gloas.ExecutionPayloadEnvelope)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *SignedExecutionPayloadEnvelope) UnmarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) error {
	switch view.(type) {
	case *gloas.SignedExecutionPayloadEnvelope:
		return t.unmarshalSSZView_SignedExecutionPayloadEnvelope
	}
	return nil
}
func (t *SignedExecutionPayloadEnvelope) unmarshalSSZView_SignedExecutionPayloadEnvelope(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 100 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 100)
	}
	// Field #0 'Message' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 100 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 100), "Message:o")
	}
	{ // Field #1 'Signature' (static)
		buf := buf[4:100]
		copy(t.Signature[:], buf)
	}
	{ // Field #0 'Message' (dynamic)
		buf := buf[offset0:]
		if t.Message == nil {
			t.Message = new(ExecutionPayloadEnvelope)
		}
		if viewFn := t.Message.UnmarshalSSZDynView((*gloas.ExecutionPayloadEnvelope)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *SignedExecutionPayloadEnvelope) SizeSSZDynView(view any) func(ds sszutils.DynamicSpecs) int {
	switch view.(type) {
	case *gloas.SignedExecutionPayloadEnvelope:
		return t.sizeSSZView_SignedExecutionPayloadEnvelope
	}
	return nil
}
func (t *SignedExecutionPayloadEnvelope) sizeSSZView_SignedExecutionPayloadEnvelope(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(SignedExecutionPayloadEnvelope)
	}
	// Field #0 'Message' offset (4 bytes)
	// Field #1 'Signature' static (96 bytes)
	size += 100
	{ // Dynamic field #0 'Message'
		if viewFn := t.Message.SizeSSZDynView((*gloas.ExecutionPayloadEnvelope)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *SignedExecutionPayloadEnvelope) HashTreeRootWithDynView(view any) func(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	switch view.(type) {
	case *gloas.SignedExecutionPayloadEnvelope:
		return t.hashTreeRootView_SignedExecutionPayloadEnvelope
	}
	return nil
}
func (t *SignedExecutionPayloadEnvelope) hashTreeRootView_SignedExecutionPayloadEnvelope(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SignedExecutionPayloadEnvelope)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(ExecutionPayloadEnvelope)
		}
		if viewFn := t.HashTreeRootWithDynView((*gloas.ExecutionPayloadEnvelope)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}
