// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 39dbdcab2c3e92e7dd3bbfc7402c12938b3f5994916a081c46626fe978a40b0f
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package all

import (
	"encoding/binary"

	"github.com/ethpandaops/go-eth2-client/spec/altair"
	"github.com/ethpandaops/go-eth2-client/spec/bellatrix"
	"github.com/ethpandaops/go-eth2-client/spec/capella"
	"github.com/ethpandaops/go-eth2-client/spec/deneb"
	"github.com/ethpandaops/go-eth2-client/spec/electra"
	"github.com/ethpandaops/go-eth2-client/spec/gloas"
	"github.com/ethpandaops/go-eth2-client/spec/heze"
	"github.com/ethpandaops/go-eth2-client/spec/phase0"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *SignedBeaconBlock) MarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) ([]byte, error) {
	switch view.(type) {
	case *phase0.SignedBeaconBlock:
		return t.marshalSSZView_SignedBeaconBlock
	case *altair.SignedBeaconBlock:
		return t.marshalSSZView_SignedBeaconBlock_0
	case *bellatrix.SignedBeaconBlock:
		return t.marshalSSZView_SignedBeaconBlock_1
	case *capella.SignedBeaconBlock:
		return t.marshalSSZView_SignedBeaconBlock_2
	case *deneb.SignedBeaconBlock:
		return t.marshalSSZView_SignedBeaconBlock_3
	case *electra.SignedBeaconBlock:
		return t.marshalSSZView_SignedBeaconBlock_4
	case *gloas.SignedBeaconBlock:
		return t.marshalSSZView_SignedBeaconBlock_5
	case *heze.SignedBeaconBlock:
		return t.marshalSSZView_SignedBeaconBlock_6
	}
	return nil
}
func (t *SignedBeaconBlock) marshalSSZView_SignedBeaconBlock(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(SignedBeaconBlock)
	}
	dstlen := len(dst)
	// Offset Field #0 'Message'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	{ // Dynamic Field #0 'Message'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.Message
		if t == nil {
			t = new(BeaconBlock)
		}
		if viewFn := t.MarshalSSZDynView((*phase0.BeaconBlock)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *SignedBeaconBlock) marshalSSZView_SignedBeaconBlock_0(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(SignedBeaconBlock)
	}
	dstlen := len(dst)
	// Offset Field #0 'Message'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	{ // Dynamic Field #0 'Message'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.Message
		if t == nil {
			t = new(BeaconBlock)
		}
		if viewFn := t.MarshalSSZDynView((*altair.BeaconBlock)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *SignedBeaconBlock) marshalSSZView_SignedBeaconBlock_1(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(SignedBeaconBlock)
	}
	dstlen := len(dst)
	// Offset Field #0 'Message'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	{ // Dynamic Field #0 'Message'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.Message
		if t == nil {
			t = new(BeaconBlock)
		}
		if viewFn := t.MarshalSSZDynView((*bellatrix.BeaconBlock)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *SignedBeaconBlock) marshalSSZView_SignedBeaconBlock_2(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(SignedBeaconBlock)
	}
	dstlen := len(dst)
	// Offset Field #0 'Message'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	{ // Dynamic Field #0 'Message'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.Message
		if t == nil {
			t = new(BeaconBlock)
		}
		if viewFn := t.MarshalSSZDynView((*capella.BeaconBlock)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *SignedBeaconBlock) marshalSSZView_SignedBeaconBlock_3(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(SignedBeaconBlock)
	}
	dstlen := len(dst)
	// Offset Field #0 'Message'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	{ // Dynamic Field #0 'Message'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.Message
		if t == nil {
			t = new(BeaconBlock)
		}
		if viewFn := t.MarshalSSZDynView((*deneb.BeaconBlock)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *SignedBeaconBlock) marshalSSZView_SignedBeaconBlock_4(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(SignedBeaconBlock)
	}
	dstlen := len(dst)
	// Offset Field #0 'Message'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	{ // Dynamic Field #0 'Message'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.Message
		if t == nil {
			t = new(BeaconBlock)
		}
		if viewFn := t.MarshalSSZDynView((*electra.BeaconBlock)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *SignedBeaconBlock) marshalSSZView_SignedBeaconBlock_5(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(SignedBeaconBlock)
	}
	dstlen := len(dst)
	// Offset Field #0 'Message'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	{ // Dynamic Field #0 'Message'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.Message
		if t == nil {
			t = new(BeaconBlock)
		}
		if viewFn := t.MarshalSSZDynView((*gloas.BeaconBlock)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *SignedBeaconBlock) marshalSSZView_SignedBeaconBlock_6(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(SignedBeaconBlock)
	}
	dstlen := len(dst)
	// Offset Field #0 'Message'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	{ // Dynamic Field #0 'Message'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.Message
		if t == nil {
			t = new(BeaconBlock)
		}
		if viewFn := t.MarshalSSZDynView((*heze.BeaconBlock)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *SignedBeaconBlock) UnmarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) error {
	switch view.(type) {
	case *phase0.SignedBeaconBlock:
		return t.unmarshalSSZView_SignedBeaconBlock
	case *altair.SignedBeaconBlock:
		return t.unmarshalSSZView_SignedBeaconBlock_0
	case *bellatrix.SignedBeaconBlock:
		return t.unmarshalSSZView_SignedBeaconBlock_1
	case *capella.SignedBeaconBlock:
		return t.unmarshalSSZView_SignedBeaconBlock_2
	case *deneb.SignedBeaconBlock:
		return t.unmarshalSSZView_SignedBeaconBlock_3
	case *electra.SignedBeaconBlock:
		return t.unmarshalSSZView_SignedBeaconBlock_4
	case *gloas.SignedBeaconBlock:
		return t.unmarshalSSZView_SignedBeaconBlock_5
	case *heze.SignedBeaconBlock:
		return t.unmarshalSSZView_SignedBeaconBlock_6
	}
	return nil
}
func (t *SignedBeaconBlock) unmarshalSSZView_SignedBeaconBlock(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 100 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 100)
	}
	// Field #0 'Message' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 100 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 100), "Message:o")
	}
	{ // Field #1 'Signature' (static)
		buf := buf[4:100]
		copy(t.Signature[:], buf)
	}
	{ // Field #0 'Message' (dynamic)
		buf := buf[offset0:]
		if t.Message == nil {
			t.Message = new(BeaconBlock)
		}
		if viewFn := t.Message.UnmarshalSSZDynView((*phase0.BeaconBlock)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *SignedBeaconBlock) unmarshalSSZView_SignedBeaconBlock_0(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 100 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 100)
	}
	// Field #0 'Message' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 100 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 100), "Message:o")
	}
	{ // Field #1 'Signature' (static)
		buf := buf[4:100]
		copy(t.Signature[:], buf)
	}
	{ // Field #0 'Message' (dynamic)
		buf := buf[offset0:]
		if t.Message == nil {
			t.Message = new(BeaconBlock)
		}
		if viewFn := t.Message.UnmarshalSSZDynView((*altair.BeaconBlock)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *SignedBeaconBlock) unmarshalSSZView_SignedBeaconBlock_1(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 100 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 100)
	}
	// Field #0 'Message' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 100 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 100), "Message:o")
	}
	{ // Field #1 'Signature' (static)
		buf := buf[4:100]
		copy(t.Signature[:], buf)
	}
	{ // Field #0 'Message' (dynamic)
		buf := buf[offset0:]
		if t.Message == nil {
			t.Message = new(BeaconBlock)
		}
		if viewFn := t.Message.UnmarshalSSZDynView((*bellatrix.BeaconBlock)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *SignedBeaconBlock) unmarshalSSZView_SignedBeaconBlock_2(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 100 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 100)
	}
	// Field #0 'Message' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 100 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 100), "Message:o")
	}
	{ // Field #1 'Signature' (static)
		buf := buf[4:100]
		copy(t.Signature[:], buf)
	}
	{ // Field #0 'Message' (dynamic)
		buf := buf[offset0:]
		if t.Message == nil {
			t.Message = new(BeaconBlock)
		}
		if viewFn := t.Message.UnmarshalSSZDynView((*capella.BeaconBlock)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *SignedBeaconBlock) unmarshalSSZView_SignedBeaconBlock_3(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 100 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 100)
	}
	// Field #0 'Message' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 100 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 100), "Message:o")
	}
	{ // Field #1 'Signature' (static)
		buf := buf[4:100]
		copy(t.Signature[:], buf)
	}
	{ // Field #0 'Message' (dynamic)
		buf := buf[offset0:]
		if t.Message == nil {
			t.Message = new(BeaconBlock)
		}
		if viewFn := t.Message.UnmarshalSSZDynView((*deneb.BeaconBlock)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *SignedBeaconBlock) unmarshalSSZView_SignedBeaconBlock_4(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 100 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 100)
	}
	// Field #0 'Message' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 100 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 100), "Message:o")
	}
	{ // Field #1 'Signature' (static)
		buf := buf[4:100]
		copy(t.Signature[:], buf)
	}
	{ // Field #0 'Message' (dynamic)
		buf := buf[offset0:]
		if t.Message == nil {
			t.Message = new(BeaconBlock)
		}
		if viewFn := t.Message.UnmarshalSSZDynView((*electra.BeaconBlock)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *SignedBeaconBlock) unmarshalSSZView_SignedBeaconBlock_5(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 100 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 100)
	}
	// Field #0 'Message' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 100 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 100), "Message:o")
	}
	{ // Field #1 'Signature' (static)
		buf := buf[4:100]
		copy(t.Signature[:], buf)
	}
	{ // Field #0 'Message' (dynamic)
		buf := buf[offset0:]
		if t.Message == nil {
			t.Message = new(BeaconBlock)
		}
		if viewFn := t.Message.UnmarshalSSZDynView((*gloas.BeaconBlock)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *SignedBeaconBlock) unmarshalSSZView_SignedBeaconBlock_6(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 100 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 100)
	}
	// Field #0 'Message' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 100 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 100), "Message:o")
	}
	{ // Field #1 'Signature' (static)
		buf := buf[4:100]
		copy(t.Signature[:], buf)
	}
	{ // Field #0 'Message' (dynamic)
		buf := buf[offset0:]
		if t.Message == nil {
			t.Message = new(BeaconBlock)
		}
		if viewFn := t.Message.UnmarshalSSZDynView((*heze.BeaconBlock)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *SignedBeaconBlock) SizeSSZDynView(view any) func(ds sszutils.DynamicSpecs) int {
	switch view.(type) {
	case *phase0.SignedBeaconBlock:
		return t.sizeSSZView_SignedBeaconBlock
	case *altair.SignedBeaconBlock:
		return t.sizeSSZView_SignedBeaconBlock_0
	case *bellatrix.SignedBeaconBlock:
		return t.sizeSSZView_SignedBeaconBlock_1
	case *capella.SignedBeaconBlock:
		return t.sizeSSZView_SignedBeaconBlock_2
	case *deneb.SignedBeaconBlock:
		return t.sizeSSZView_SignedBeaconBlock_3
	case *electra.SignedBeaconBlock:
		return t.sizeSSZView_SignedBeaconBlock_4
	case *gloas.SignedBeaconBlock:
		return t.sizeSSZView_SignedBeaconBlock_5
	case *heze.SignedBeaconBlock:
		return t.sizeSSZView_SignedBeaconBlock_6
	}
	return nil
}
func (t *SignedBeaconBlock) sizeSSZView_SignedBeaconBlock(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(SignedBeaconBlock)
	}
	// Field #0 'Message' offset (4 bytes)
	// Field #1 'Signature' static (96 bytes)
	size += 100
	{ // Dynamic field #0 'Message'
		if viewFn := t.Message.SizeSSZDynView((*phase0.BeaconBlock)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *SignedBeaconBlock) sizeSSZView_SignedBeaconBlock_0(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(SignedBeaconBlock)
	}
	// Field #0 'Message' offset (4 bytes)
	// Field #1 'Signature' static (96 bytes)
	size += 100
	{ // Dynamic field #0 'Message'
		if viewFn := t.Message.SizeSSZDynView((*altair.BeaconBlock)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *SignedBeaconBlock) sizeSSZView_SignedBeaconBlock_1(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(SignedBeaconBlock)
	}
	// Field #0 'Message' offset (4 bytes)
	// Field #1 'Signature' static (96 bytes)
	size += 100
	{ // Dynamic field #0 'Message'
		if viewFn := t.Message.SizeSSZDynView((*bellatrix.BeaconBlock)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *SignedBeaconBlock) sizeSSZView_SignedBeaconBlock_2(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(SignedBeaconBlock)
	}
	// Field #0 'Message' offset (4 bytes)
	// Field #1 'Signature' static (96 bytes)
	size += 100
	{ // Dynamic field #0 'Message'
		if viewFn := t.Message.SizeSSZDynView((*capella.BeaconBlock)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *SignedBeaconBlock) sizeSSZView_SignedBeaconBlock_3(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(SignedBeaconBlock)
	}
	// Field #0 'Message' offset (4 bytes)
	// Field #1 'Signature' static (96 bytes)
	size += 100
	{ // Dynamic field #0 'Message'
		if viewFn := t.Message.SizeSSZDynView((*deneb.BeaconBlock)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *SignedBeaconBlock) sizeSSZView_SignedBeaconBlock_4(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(SignedBeaconBlock)
	}
	// Field #0 'Message' offset (4 bytes)
	// Field #1 'Signature' static (96 bytes)
	size += 100
	{ // Dynamic field #0 'Message'
		if viewFn := t.Message.SizeSSZDynView((*electra.BeaconBlock)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *SignedBeaconBlock) sizeSSZView_SignedBeaconBlock_5(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(SignedBeaconBlock)
	}
	// Field #0 'Message' offset (4 bytes)
	// Field #1 'Signature' static (96 bytes)
	size += 100
	{ // Dynamic field #0 'Message'
		if viewFn := t.Message.SizeSSZDynView((*gloas.BeaconBlock)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *SignedBeaconBlock) sizeSSZView_SignedBeaconBlock_6(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(SignedBeaconBlock)
	}
	// Field #0 'Message' offset (4 bytes)
	// Field #1 'Signature' static (96 bytes)
	size += 100
	{ // Dynamic field #0 'Message'
		if viewFn := t.Message.SizeSSZDynView((*heze.BeaconBlock)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *SignedBeaconBlock) HashTreeRootWithDynView(view any) func(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	switch view.(type) {
	case *phase0.SignedBeaconBlock:
		return t.hashTreeRootView_SignedBeaconBlock
	case *altair.SignedBeaconBlock:
		return t.hashTreeRootView_SignedBeaconBlock_0
	case *bellatrix.SignedBeaconBlock:
		return t.hashTreeRootView_SignedBeaconBlock_1
	case *capella.SignedBeaconBlock:
		return t.hashTreeRootView_SignedBeaconBlock_2
	case *deneb.SignedBeaconBlock:
		return t.hashTreeRootView_SignedBeaconBlock_3
	case *electra.SignedBeaconBlock:
		return t.hashTreeRootView_SignedBeaconBlock_4
	case *gloas.SignedBeaconBlock:
		return t.hashTreeRootView_SignedBeaconBlock_5
	case *heze.SignedBeaconBlock:
		return t.hashTreeRootView_SignedBeaconBlock_6
	}
	return nil
}
func (t *SignedBeaconBlock) hashTreeRootView_SignedBeaconBlock(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SignedBeaconBlock)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(BeaconBlock)
		}
		if viewFn := t.HashTreeRootWithDynView((*phase0.BeaconBlock)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}

func (t *SignedBeaconBlock) hashTreeRootView_SignedBeaconBlock_0(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SignedBeaconBlock)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(BeaconBlock)
		}
		if viewFn := t.HashTreeRootWithDynView((*altair.BeaconBlock)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}

func (t *SignedBeaconBlock) hashTreeRootView_SignedBeaconBlock_1(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SignedBeaconBlock)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(BeaconBlock)
		}
		if viewFn := t.HashTreeRootWithDynView((*bellatrix.BeaconBlock)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}

func (t *SignedBeaconBlock) hashTreeRootView_SignedBeaconBlock_2(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SignedBeaconBlock)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(BeaconBlock)
		}
		if viewFn := t.HashTreeRootWithDynView((*capella.BeaconBlock)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}

func (t *SignedBeaconBlock) hashTreeRootView_SignedBeaconBlock_3(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SignedBeaconBlock)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(BeaconBlock)
		}
		if viewFn := t.HashTreeRootWithDynView((*deneb.BeaconBlock)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}

func (t *SignedBeaconBlock) hashTreeRootView_SignedBeaconBlock_4(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SignedBeaconBlock)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(BeaconBlock)
		}
		if viewFn := t.HashTreeRootWithDynView((*electra.BeaconBlock)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}

func (t *SignedBeaconBlock) hashTreeRootView_SignedBeaconBlock_5(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SignedBeaconBlock)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(BeaconBlock)
		}
		if viewFn := t.HashTreeRootWithDynView((*gloas.BeaconBlock)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}

func (t *SignedBeaconBlock) hashTreeRootView_SignedBeaconBlock_6(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SignedBeaconBlock)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(BeaconBlock)
		}
		if viewFn := t.HashTreeRootWithDynView((*heze.BeaconBlock)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}
