// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: b1cebfae242eab9dc409aaf1031026077c9e2572fb2e9baf679e1d0952f18249
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package all

import (
	"encoding/binary"

	"github.com/ethpandaops/go-eth2-client/spec/gloas"
	"github.com/ethpandaops/go-eth2-client/spec/heze"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *SignedExecutionPayloadBid) MarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) ([]byte, error) {
	switch view.(type) {
	case *gloas.SignedExecutionPayloadBid:
		return t.marshalSSZView_SignedExecutionPayloadBid
	case *heze.SignedExecutionPayloadBid:
		return t.marshalSSZView_SignedExecutionPayloadBid_0
	}
	return nil
}
func (t *SignedExecutionPayloadBid) marshalSSZView_SignedExecutionPayloadBid(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(SignedExecutionPayloadBid)
	}
	dstlen := len(dst)
	// Offset Field #0 'Message'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	{ // Dynamic Field #0 'Message'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.Message
		if t == nil {
			t = new(ExecutionPayloadBid)
		}
		if viewFn := t.MarshalSSZDynView((*gloas.ExecutionPayloadBid)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *SignedExecutionPayloadBid) marshalSSZView_SignedExecutionPayloadBid_0(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(SignedExecutionPayloadBid)
	}
	dstlen := len(dst)
	// Offset Field #0 'Message'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	{ // Dynamic Field #0 'Message'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.Message
		if t == nil {
			t = new(ExecutionPayloadBid)
		}
		if viewFn := t.MarshalSSZDynView((*heze.ExecutionPayloadBid)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *SignedExecutionPayloadBid) UnmarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) error {
	switch view.(type) {
	case *gloas.SignedExecutionPayloadBid:
		return t.unmarshalSSZView_SignedExecutionPayloadBid
	case *heze.SignedExecutionPayloadBid:
		return t.unmarshalSSZView_SignedExecutionPayloadBid_0
	}
	return nil
}
func (t *SignedExecutionPayloadBid) unmarshalSSZView_SignedExecutionPayloadBid(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 100 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 100)
	}
	// Field #0 'Message' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 100 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 100), "Message:o")
	}
	{ // Field #1 'Signature' (static)
		buf := buf[4:100]
		copy(t.Signature[:], buf)
	}
	{ // Field #0 'Message' (dynamic)
		buf := buf[offset0:]
		if t.Message == nil {
			t.Message = new(ExecutionPayloadBid)
		}
		if viewFn := t.Message.UnmarshalSSZDynView((*gloas.ExecutionPayloadBid)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *SignedExecutionPayloadBid) unmarshalSSZView_SignedExecutionPayloadBid_0(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 100 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 100)
	}
	// Field #0 'Message' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 100 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 100), "Message:o")
	}
	{ // Field #1 'Signature' (static)
		buf := buf[4:100]
		copy(t.Signature[:], buf)
	}
	{ // Field #0 'Message' (dynamic)
		buf := buf[offset0:]
		if t.Message == nil {
			t.Message = new(ExecutionPayloadBid)
		}
		if viewFn := t.Message.UnmarshalSSZDynView((*heze.ExecutionPayloadBid)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *SignedExecutionPayloadBid) SizeSSZDynView(view any) func(ds sszutils.DynamicSpecs) int {
	switch view.(type) {
	case *gloas.SignedExecutionPayloadBid:
		return t.sizeSSZView_SignedExecutionPayloadBid
	case *heze.SignedExecutionPayloadBid:
		return t.sizeSSZView_SignedExecutionPayloadBid_0
	}
	return nil
}
func (t *SignedExecutionPayloadBid) sizeSSZView_SignedExecutionPayloadBid(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(SignedExecutionPayloadBid)
	}
	// Field #0 'Message' offset (4 bytes)
	// Field #1 'Signature' static (96 bytes)
	size += 100
	{ // Dynamic field #0 'Message'
		if viewFn := t.Message.SizeSSZDynView((*gloas.ExecutionPayloadBid)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *SignedExecutionPayloadBid) sizeSSZView_SignedExecutionPayloadBid_0(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(SignedExecutionPayloadBid)
	}
	// Field #0 'Message' offset (4 bytes)
	// Field #1 'Signature' static (96 bytes)
	size += 100
	{ // Dynamic field #0 'Message'
		if viewFn := t.Message.SizeSSZDynView((*heze.ExecutionPayloadBid)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *SignedExecutionPayloadBid) HashTreeRootWithDynView(view any) func(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	switch view.(type) {
	case *gloas.SignedExecutionPayloadBid:
		return t.hashTreeRootView_SignedExecutionPayloadBid
	case *heze.SignedExecutionPayloadBid:
		return t.hashTreeRootView_SignedExecutionPayloadBid_0
	}
	return nil
}
func (t *SignedExecutionPayloadBid) hashTreeRootView_SignedExecutionPayloadBid(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SignedExecutionPayloadBid)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(ExecutionPayloadBid)
		}
		if viewFn := t.HashTreeRootWithDynView((*gloas.ExecutionPayloadBid)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}

func (t *SignedExecutionPayloadBid) hashTreeRootView_SignedExecutionPayloadBid_0(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SignedExecutionPayloadBid)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(ExecutionPayloadBid)
		}
		if viewFn := t.HashTreeRootWithDynView((*heze.ExecutionPayloadBid)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}
