// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: f8b5da54f2824e247bd345281445fa469af90cc3ba108ba6beef83ca9a2e5078
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package all

import (
	"encoding/binary"

	"github.com/ethpandaops/go-eth2-client/spec/electra"
	"github.com/ethpandaops/go-eth2-client/spec/phase0"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *SignedAggregateAndProof) MarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) ([]byte, error) {
	switch view.(type) {
	case *phase0.SignedAggregateAndProof:
		return t.marshalSSZView_SignedAggregateAndProof
	case *electra.SignedAggregateAndProof:
		return t.marshalSSZView_SignedAggregateAndProof_0
	}
	return nil
}
func (t *SignedAggregateAndProof) marshalSSZView_SignedAggregateAndProof(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(SignedAggregateAndProof)
	}
	dstlen := len(dst)
	// Offset Field #0 'Message'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	{ // Dynamic Field #0 'Message'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.Message
		if t == nil {
			t = new(AggregateAndProof)
		}
		if viewFn := t.MarshalSSZDynView((*phase0.AggregateAndProof)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *SignedAggregateAndProof) marshalSSZView_SignedAggregateAndProof_0(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(SignedAggregateAndProof)
	}
	dstlen := len(dst)
	// Offset Field #0 'Message'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	{ // Dynamic Field #0 'Message'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.Message
		if t == nil {
			t = new(AggregateAndProof)
		}
		if viewFn := t.MarshalSSZDynView((*electra.AggregateAndProof)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *SignedAggregateAndProof) UnmarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) error {
	switch view.(type) {
	case *phase0.SignedAggregateAndProof:
		return t.unmarshalSSZView_SignedAggregateAndProof
	case *electra.SignedAggregateAndProof:
		return t.unmarshalSSZView_SignedAggregateAndProof_0
	}
	return nil
}
func (t *SignedAggregateAndProof) unmarshalSSZView_SignedAggregateAndProof(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 100 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 100)
	}
	// Field #0 'Message' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 100 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 100), "Message:o")
	}
	{ // Field #1 'Signature' (static)
		buf := buf[4:100]
		copy(t.Signature[:], buf)
	}
	{ // Field #0 'Message' (dynamic)
		buf := buf[offset0:]
		if t.Message == nil {
			t.Message = new(AggregateAndProof)
		}
		if viewFn := t.Message.UnmarshalSSZDynView((*phase0.AggregateAndProof)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *SignedAggregateAndProof) unmarshalSSZView_SignedAggregateAndProof_0(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 100 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 100)
	}
	// Field #0 'Message' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 100 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 100), "Message:o")
	}
	{ // Field #1 'Signature' (static)
		buf := buf[4:100]
		copy(t.Signature[:], buf)
	}
	{ // Field #0 'Message' (dynamic)
		buf := buf[offset0:]
		if t.Message == nil {
			t.Message = new(AggregateAndProof)
		}
		if viewFn := t.Message.UnmarshalSSZDynView((*electra.AggregateAndProof)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *SignedAggregateAndProof) SizeSSZDynView(view any) func(ds sszutils.DynamicSpecs) int {
	switch view.(type) {
	case *phase0.SignedAggregateAndProof:
		return t.sizeSSZView_SignedAggregateAndProof
	case *electra.SignedAggregateAndProof:
		return t.sizeSSZView_SignedAggregateAndProof_0
	}
	return nil
}
func (t *SignedAggregateAndProof) sizeSSZView_SignedAggregateAndProof(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(SignedAggregateAndProof)
	}
	// Field #0 'Message' offset (4 bytes)
	// Field #1 'Signature' static (96 bytes)
	size += 100
	{ // Dynamic field #0 'Message'
		if viewFn := t.Message.SizeSSZDynView((*phase0.AggregateAndProof)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *SignedAggregateAndProof) sizeSSZView_SignedAggregateAndProof_0(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(SignedAggregateAndProof)
	}
	// Field #0 'Message' offset (4 bytes)
	// Field #1 'Signature' static (96 bytes)
	size += 100
	{ // Dynamic field #0 'Message'
		if viewFn := t.Message.SizeSSZDynView((*electra.AggregateAndProof)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *SignedAggregateAndProof) HashTreeRootWithDynView(view any) func(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	switch view.(type) {
	case *phase0.SignedAggregateAndProof:
		return t.hashTreeRootView_SignedAggregateAndProof
	case *electra.SignedAggregateAndProof:
		return t.hashTreeRootView_SignedAggregateAndProof_0
	}
	return nil
}
func (t *SignedAggregateAndProof) hashTreeRootView_SignedAggregateAndProof(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SignedAggregateAndProof)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(AggregateAndProof)
		}
		if viewFn := t.HashTreeRootWithDynView((*phase0.AggregateAndProof)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}

func (t *SignedAggregateAndProof) hashTreeRootView_SignedAggregateAndProof_0(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SignedAggregateAndProof)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(AggregateAndProof)
		}
		if viewFn := t.HashTreeRootWithDynView((*electra.AggregateAndProof)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}
