// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: a0e84fab429b04f0e4e3f0bf573b6129c1b9daa23a117b3d7517aaa65345deed
// Version: v1.2.1 (https://github.com/pk910/dynamic-ssz)
package api

import (
	"encoding/binary"

	"github.com/attestantio/go-eth2-client/api/v1"
	"github.com/attestantio/go-eth2-client/spec"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *VersionedSignedValidatorRegistration) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *VersionedSignedValidatorRegistration) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(VersionedSignedValidatorRegistration)
	}
	{ // Field #0 'Version'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.Version))
	}
	{ // Field #1 'V1'
		t := t.V1
		if t == nil {
			t = new(v1.SignedValidatorRegistration)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, err
		}
	}
	return dst, nil
}

func (t *VersionedSignedValidatorRegistration) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 188 {
		return sszutils.ErrUnexpectedEOF
	}
	{ // Field #0 'Version' (static)
		buf := buf[0:8]
		t.Version = spec.BuilderVersion(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #1 'V1' (static)
		buf := buf[8:188]
		if t.V1 == nil {
			t.V1 = new(v1.SignedValidatorRegistration)
		}
		if err = t.V1.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return nil
}

func (t *VersionedSignedValidatorRegistration) SizeSSZ() (size int) {
	return 188
}

func (t *VersionedSignedValidatorRegistration) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
func (t *VersionedSignedValidatorRegistration) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(VersionedSignedValidatorRegistration)
	}
	idx := hh.Index()
	{ // Field #0 'Version'
		hh.PutUint64(uint64(t.Version))
	}
	{ // Field #1 'V1'
		t := t.V1
		if t == nil {
			t = new(v1.SignedValidatorRegistration)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return err
		}
	}
	hh.Merkleize(idx)
	return nil
}

